### ISSUE TITLE
Use namespaces with qhub actions to allow for dev/staging/prod

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#100]

**Comment by prasunanand** [comment]
We create 3 branches :
1. dev => dev.jupyter.training.qhub.dev
2. staging => dev.jupyter.training.qhub.dev
3. production => => jupyter.training.qhub.dev

Modify qhub render to render when there is a merge on `master`

Add 3 jupyter-pr actions
1. Merge dev => in terraform actions , add `var namespace = dev` and `endpoint url` as `dev.jupyter`
2. Merge to staging => in terraform actions , add `var namespace = staging` and `endpoint url` as `staging.jupyter`
3. Merge to prod => in terraform actions , add `var namespace = prod` and `endpoint url` as `prod.jupyter`


Note: Make sure the state is maintained and duplicate resources are not created.

cc @dharhas @costrouc @tylerpotts

**Comment by prasunanand** [comment]
This would also required that we output three `IP`s for three namespaces.

**Comment by dharhas** [comment]
What is the cost impact of this? Would dev/staging be running all the time?

**Comment by prasunanand** [comment]
I think only `staging` should do the job. We won't need dev. The cost impact would be an `extra-ip` cost, Also we would need one `node` for general nodegroup that would be running all the time

@costrouc Is this correct ?

**Comment by costrouc** [comment]
On gcp the base additional cost would be $200/month. @prasunanand did you mean for `dev` and `staging` to point to the same url? Also this may take a few steps to get right and I think it would be good to rely on `qhub init` to get it setup right.

**Comment by costrouc** [comment]
@dharhas if we don't want this to run all the time we need to work on testing and automation.

**Comment by dharhas** [comment]
That might be a good long term goal, but it isn't necessary in the short term. We just need to understand costs and communicated that in the docs. i.e. bare cluster with no staging base cost is $200/mo, adding a staging cluster is an extra $200/mo.
