### ISSUE TITLE
Fix docker image build workflows

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1000]
## Describe the bug

The JupyterLab docker image builds have been consistently failing for the past week or two. 

https://github.com/Quansight/qhub/runs/4845380327?check_suite_focus=true#step:8:3189

**Comment by viniciusdc** [comment]
HI @iameskild, thanks for opening this issue. we install code-server during the postbuild phase for the Jupyterlab image, as it seems they made a release that checked their `isntall.sh` download URL. Then we start getting the following error:
```
#22 1.075 Installing vhttps://github.com/coder/code-server/releases/tag/v4.0.1 deb package from GitHub releases.
#22 1.077 
#22 1.079 + mkdir -p ~/.cache/code-server
#22 1.087 + curl -#fL -o ~/.cache/code-server/code-server_https://github.com/coder/code-server/releases/tag/v4.0.1_amd64.deb.incomplete -C - https://github.com/cdr/code-server/releases/download/vhttps://github.com/coder/code-server/releases/tag/v4.0.1/code-server_https://github.com/coder/code-server/releases/tag/v4.0.1_amd64.deb
#22 1.219 #=#=#                                                                         

######################################################################## 100.0%##O#- #                                                                       
curl: (22) The requested URL returned error: 404 
#22 1.380 
#22 ERROR: process "/bin/bash -c /opt/jupyterlab/postBuild" did not complete successfully: exit code: 22
```
I will make a PR updating it :+1:

**Comment by viniciusdc** [comment]
Another issue arises!! (good movie name sksks), it seems that our docker build action has a release yesterday which modified the behavior of handling the [`context` attribute ](https://github.com/Quansight/qhub/blob/a44e759f136322010f74562a4ba5f1d5e55821ef/.github/workflows/image.yaml#L80). It seems that they are handling [Handlebars](https://handlebarsjs.com/guide/) as default now, which on the other hand might be conflicting with our path `./*./{{ cookiecutter.repo_directory }}/image `

**Comment by viniciusdc** [comment]
As per #1003, we will start removing the dependency over cookie-cutter, which should impact the directory path name,  mentioned above. For now, I will update the context path to `./qhub/template/*/image`
