### ISSUE TITLE
[documentation] Overhaul for 0.4

### ISSUE THREAD

**Issue by magsol** [Quansight/qhub#1009]
### This is the checklist of documentation changes we'd like to make for 0.4.

Notes on web docs that don't make sense, aren't clear, or need expanding:

 - [ ] #1031
 - [x] Mention of CentOS [should be struck from docs](https://docs.qhub.dev/en/latest/source/user_guide/experimental.html?highlight=centos#centos-jupyterlab-and-dask-worker-profiles) (as their images have been removed)
 - [x] #1032
 - [x] #1036 
 - [x] #1048 

Some existing documentation related tickets:

- [x] https://github.com/Quansight/qhub/issues/999
- [ ] https://github.com/Quansight/qhub/issues/975
- [ ] https://github.com/Quansight/qhub/issues/971
- [x] https://github.com/Quansight/qhub/issues/935
- [ ] https://github.com/Quansight/qhub/issues/796
- [ ] https://github.com/Quansight/qhub/issues/792
- [ ] https://github.com/Quansight/qhub/issues/634
- [ ] https://github.com/Quansight/qhub/issues/606
- [ ] https://github.com/Quansight/qhub/issues/487
- [x] https://github.com/Quansight/qhub/issues/301

**Comment by iameskild** [comment]
I believe we can close #935, see docs here:
https://docs.qhub.dev/en/latest/source/installation/existing.html

**Comment by iameskild** [comment]
Given that CentOS images have been pulled out, we will need to remove their references in the docs:
https://docs.qhub.dev/en/latest/source/user_guide/experimental.html?highlight=centos#centos-jupyterlab-and-dask-worker-profiles

**Comment by magsol** [comment]
@iameskild I'm realizing #935 seems less like a documentation issue; in fact it seems like the issue is still active, with the [last post from the OP on Dec 17](https://github.com/Quansight/qhub/issues/935#issuecomment-997008164).

Has anyone reproduced this error since?

**Comment by iameskild** [comment]
@magsol I tried reproducing the error awhile back but I was having trouble doing so. Let me follow up with OP and we can go from there.

**Comment by iameskild** [comment]
With the release of `v0.4.0` and issue #1076, I believe we can close this issue.
