### ISSUE TITLE
Scaled down kubessh to clean up logs for debugging

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#101]
Scaled down with `kubectl scale --replicas=0 deployment kubessh-install -n dev`

To re-enable, use `kubectl scale --replicas=1 deployment kubessh-install -n dev`

**Comment by prasunanand** [comment]
This needs to be in FAQ docs.

**Comment by prasunanand** [comment]
@tylerpotts Should this issue be closed ?

**Comment by tylerpotts** [comment]
yes
