### ISSUE TITLE
Add CI/CD pipelines for github and gitlab back

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1013]
With the recent changes from #1003 we removed cookiecutter dependency over the programmatic way qhub was deployed and rendered. That broke the way those actions were generated, we will need to add those back and include `ruamel` for generating those "templates".

**Comment by costrouc** [comment]
@viniciusdc and @iameskild when implementing please take into consideration https://github.com/Quansight/qhub/pull/995/ as well to make sure we have the features that our clients need.
