### ISSUE TITLE
Discuss url naming convention.

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#102]
Given a label say `training` the qhub urls would be:

Less verbose option (make the jhub link primary):

jupyter: `training.qhub.dev`
staging jupyter: `staging.training.qhub.dev`
kubessh: `shell.training.qhub.dev`
staging kubessh: `staging.shell.training.qhub.dev`

OR we could keep what we currently have but add an extra landing page

qhub landing page that links to the others: `training.qhub.dev`
jupyter: `jupyter.training.qhub.dev`
staging jupyter: `staging.jupyter.training.qhub.dev`
kubessh: `shell.training.qhub.dev`
staging kubessh: `staging.shell.training.qhub.dev`

The second would also give us a good way to list available intergrations like grafana etc.

@costrouc @aktech @tylerpotts @prasunanand what do y'all think

**Comment by tylerpotts** [comment]
I think this naming convention works fine.

We also discussed the naming convention for Quansight managed qhub github repos in today's standup. We're thinking:
`qhub-<project>-<cloud>-<deployment>`
Datum's prod deployment github would then be:
`qhub-datum-gcp-prod`

**Comment by dharhas** [comment]
So are you saying the prod/dev env would have different github repos? That sounds like it would be hard to keep in sync.

**Comment by prasunanand** [comment]
I agree with @dharhas .

@tylerpotts, Sorry  I missed the standup today. I am unable to understand the naming convention . I have a few questions. I would like to discuss in the next standup.

**Comment by tylerpotts** [comment]
Issue moved to [Quansight/quansight-internal-support #69](https://github.com/Quansight/quansight-internal-support/issues/69) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tylerpotts** [comment]
Moved this issue here since this is an internal IT question
