### ISSUE TITLE
Dynamically populate environments for cdsdashboards

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1021]
## Description

Currently cdsdashboard environments are populated from qhub-config.yaml. This does not account for all the environments that are created via conda-store. Would be nice to ingrate these together. 

## Value/benefit

Users will have access to all their environments when creating a dashboard.

## Action Items

 - cdsdashboards will need to make the `c.CDSDashboardsConfig.conda_envs` trait `Callable` similar to dask_gateway and their cluster options
 - Create a function that will query conda-store via rest api(not implemented) or checking the filesystem (easier) and probably the right solution for the medium term.

**Comment by iameskild** [comment]
This is now available: https://github.com/Quansight/qhub/pull/1358
