### ISSUE TITLE
[bug] Fix flacky checks in qhub/deploy.py

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1022]
## Describe the bug

The CI is still occasionally failing when waiting for services to come up. Lets adjust the checks to run for a total of 1 minute.

## Expected behaviour

No unexpected failing tests

## Actual behaviour

Don't have enough prs to get a good idea of the failure rate but we have seen 1 so far. 
 - https://github.com/Quansight/qhub/runs/5055664161?check_suite_focus=true

**Comment by viniciusdc** [comment]
The issue might be related to getting `keycloak-server` pod in a `running` state... we can easily add a `null_resource` to wait a certain amount of time right after the helm resource is deployed.
