### ISSUE TITLE
Troubleshooting section (start with devs, mainly with upgrade paths)

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1032]
Important especially with the new release and all the changes coming:

- some common providers/integrations gotchas and how to fix them

Proposed approach:

1. Issue
2. Reason for the observed behaviour
3. Troubleshooting 
4. Optional - resources

**Comment by costrouc** [comment]
@trallard I think this is a large amount of work and hard to define what done is. We have several docs on gcp issues and how to get kubernetes credentials to check on the cluster. 

Are you just suggesting that we have a troubleshooting page?

**Comment by trallard** [comment]
>Are you just suggesting that we have a troubleshooting page?
 
Indeed - writing in-depth guides for all the providers is a great effort.  What I am thinking is something similar to JupyterHub's troubleshooting page <https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html> which are known pain points / commonly seen issues for the project.

**Comment by iameskild** [comment]
Hey @trallard how do you feel if we closed this issue? We now have the troubleshooting section and I agree that we should be adding to it as new "gotchas" are discovered.
