### ISSUE TITLE
[documentation] Add to docs limitations of CDSDashboards for 0.4.0 release

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1034]
Only the environments specified in `qhub-config.yaml` will show up in cdsdashboards. This issue will be properly address in 0.4.x.

**Comment by iameskild** [comment]
Hey @costrouc I don't recall what these limitations were? Perhaps we can include them in the next release?

**Comment by costrouc** [comment]
The limitation is that the environments are not dynamic and the only ones that show up are the ones in the qhub-config.yaml.
