### ISSUE TITLE
Shared folders not mounting (as if no groups) [bug]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#1075]
## Describe the bug

Shared folder problems (encountered when reviewing #1074)

- No shared folders appearing
- Init container initialize-shared-mounts will have empty command when there are no groups

## Expected behaviour

- Each of a user's groups should appear as a shared folder in `shared` in the JupyterLab tree.
- Omit init container if it's not doing anything

## Actual behaviour

As above, it's as though the user is not a member of any groups.

The groups seem to be filtered out because they do not start with `/projects` [here](https://github.com/Quansight/qhub/blob/003921da977ded613da15f3b815e630f58cfed15/qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py#L333).

I'm not too sure why we would expect them to be under `/project` - a fresh install does not create groups in this way. In general, this is all undocumented and confusing.

This [initialize-shared-mounts init container](https://github.com/Quansight/qhub/blob/003921da977ded613da15f3b815e630f58cfed15/qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py#L101) is not needed if groups is empty anyway.

## How to reproduce

I tried the code linked above (branch fix-1035) on a fresh Digital Ocean QHub installation.

**Comment by viniciusdc** [comment]
Hi @danlester thanks for sharing this, I will have a look into this when testing the remaining cloud providers. Were there any modifications that you did to the user you tested the instance with? e.g which group are you assigned to, or do you create a new group?

**Comment by danlester** [comment]
@viniciusdc The user was in the `developer` group, for example.

**Comment by danlester** [comment]
@costrouc Are you saying that I shouldn't expect being a member of the default group(s) to lead to a corresponding shared folder? And that if I want a shared folder I need to create a group called e.g. `/projects/sharedgroup` to get a `sharedgroup` folder in JupyterLab?

I think whatever we choose needs to be obvious out of the box... If they aren't primarily for the creation of shared folders, what are the default groups for? How can we make it obvious what the admin can achieve in the groups section of Keycloak, and what the different group paths can be. Perhaps adding back the `users` shared folder as a default would help guide this...

**Comment by viniciusdc** [comment]
> @viniciusdc The user was in the `developer` group, for example.

Thanks @danlester, I also saw the issue on a recent aws fresh install. The icon does shows up but I got this when accesing it: 
![image](https://user-images.githubusercontent.com/51954708/154759681-251e1896-9fb8-4805-8e76-2bf2179613e1.png)

**Comment by viniciusdc** [comment]
> @viniciusdc that is not related to this issue. This issue you are seeing was fixed by PR #1074. If you rebase this issue should disappear.

I see, didn't saw that PR. Many thanks @costrouc

**Comment by danlester** [comment]
My understanding is that previously, members of `admin` group would have had an `admin` shared folder, so would presumably expect to still see its contents after the upgrade.
