### ISSUE TITLE
[DOC] - Meta issue for Documentation overhaul

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1076]
Opening this issue to keep track of all docs related tasks and progress. Also to keep a history of discussions

### `0.4.0` release 
- #1048
- #1009 

### General reference/explanation 
- #999 
- #1036
- #1030 
- #1034 
- #971 
- #792
- #796 
- #606 
- #971
- #1137
- #1135
- #1276 
- #1298 

### Developer and contribution experience 
- #1032 
- #301 
- #634 
- #1077
- #1101 

### General documentation overhaul
- #975 
- #487 

### Assets - diagrams, screenshots, etc.
- #1134 
- #1031

**Comment by trallard** [comment]
@kcpevey did you check this issue and the current work plan? can this be closed?

**Comment by kcpevey** [comment]
All issues have been resolved or transferred. Cross references to transferred issues are in the individual issues.

**Comment by trallard** [comment]
So can this be closed?
