### ISSUE TITLE
[BUG] - conda-store image does not upgrade correctly to 0.4

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#1104]
### OS system and architecture in which you are running QHub

MacOS, any cloud

### Expected behavior

Run `qhub upgrade -c qhub-config.yaml` on a yaml file from v0.3.14, aiming to upgrade to v0.4.

Before, we had `default_images.conda-store: quansight/qhub-conda-store:v0.3.14`, and we end up with `quansight/qhub-conda-store:v0.4.0` - but that doesn't exist.

For contrast, a new `qhub init` gives `default_images.conda-store: quansight/conda-store-server:v0.3.9` - which is the correct, working image.

### Actual behavior

We are given the wrong image after upgrade, and this won't work with the latest qhub.

### How to Reproduce the problem?

Run `qhub upgrade -c qhub-config.yaml` on a yaml file from v0.3.14, aiming to upgrade to v0.4.

Before, we had `default_images.conda-store: quansight/qhub-conda-store:v0.3.14`, and we now get `quansight/qhub-conda-store:v0.4.0` - but that doesn't exist.

### Command output

```bash session
qhub upgrade -c qhub-config.yaml
```

### Versions and dependencies used.

Qhub version in main

### Compute environment

AWS

**Comment by danlester** [comment]
From @costrouc: This is due to conda-store no longer needing to be built by QHub. When I added conda-store I wanted to avoid breaking changes so I left default-images.conda-store but it is not needed to be specified anymore.

I don't think that you would want to change the conda-store version. So I would be fine with removing it from the schema.

**Comment by danlester** [comment]
I think we just need to work out the easiest thing for now because I need to fix the upgrade process.

It sounds like using older image spec `quansight/qhub-conda-store` isn't going to work, so we at least need to switch it to `quansight/conda-store-server:v0.3.9` as part of `qhub upgrade`. (Except, I then also need to exclude it from future upgrades, but that can be post-0.4)

I think the options are:

# Option 1

- Remove `default_images:conda-store` entirely from the schema
- Use an internally-specified image instead
- Remove `default_images:conda-store` from qhub init too
- Remove `default_images:conda-store` from the yaml file as part of `qhub upgrade` to 0.4

# Option 2

- Keep `default_images:conda-store` in the schema and use it faithfully within QHub
- Modify `qhub upgrade` to replace it with the correct version at this time.
- Make an issue to fix future upgrades from incorrectly advancing the conda-store image version


The first option is definitely easiest, but reduces flexibility for a deployment - which @costrouc and @viniciusdc currently don't feel is an issue. For option 2 to work, I think it would be better to build a qhub-specific image with the same naming convention as the other images, even if we're basically just re-tagging it.

There is an argument that if the user doesn't need to specify conda-store image, maybe they also don't need to specify jupyterhub or dask_gateway either. Maybe that's true, but I can believe that conda-store can be seen as a self-contained component within QHub that is far less likely to need customisation.

**Comment by magsol** [comment]
@HarshCasper We're going with Option 1 above for the fix.
