### ISSUE TITLE
[BUG] - Increase general node default size

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#1111]
### OS system and architecture in which you are running QHub

MacOS / GCP

### Expected behavior

General node should not reach 'critical memory level' after initial deployment.

### Actual behavior

General node has 93% mem usage after deployment, according to K9s.

### How to Reproduce the problem?

`qhub init gcp` and then deploy to GCP.

### Versions and dependencies used.

Qhub main version

### Compute environment

GCP

### Anything else?

This may be the same on the other clouds - I think conda store has pushed it over the edge!

**Comment by danlester** [comment]
After a while, it has settled down to 52% mem usage, so maybe it's OK... a bit disconcerting though!

**Comment by iameskild** [comment]
It might also be worthwhile increasing the default size of:
- the conda-store storage
- the nfs storage
