### ISSUE TITLE
[ENH] - Impose documentation line length automatically

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#1113]
### Feature description

Add pre-commit hooks to retrict the line length of our `md` files, if possible.

@trallard suggests having ~220/180 for md documents.

### Value and/or benefit

This will help PR reviewers, and provide consistency as per Black for our Python code.

**Comment by viniciusdc** [comment]
I agree with adding this, I`ve tried using https://github.com/igorshubovych/markdownlint-cli but its fix functionality does not wrap the lines... I couldn't find another reliable md linter. (there is this one as well https://github.com/executablebooks/mdformat that is worth trying)

Another option might be an action for that, we have much more options for it
