### ISSUE TITLE
Upgrade conda-store v0.3.10 and simplify specification of image

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#1126]
In fixing #1104 through PR #1119, we were left with multiple locations where the conda-store image was specified.

@costrouc 's attempt to upgrade conda-store from v0.3.9 to v0.3.10 within PR #1118 was actually ineffective because of this duplication.

@HarshCasper plans to refactor further to avoid future confusion, and of course in the process land on conda-store v0.3.10 as the true default.

**Comment by costrouc** [comment]
Ah I missed 

```
        "conda-store-image": _split_docker_image_name(
            "quansight/conda-store-server:v0.3.9"
        ),
```

in input_vars. Yeah that should absolutely be deleted :smile:
