### ISSUE TITLE
Include an optional version field within qhub-config.yaml to pin qhub version used for rendering

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#113]
Want to open this for discussion. This work is open for discussion

**Comment by brl0** [comment]
@costrouc, @tylerpotts, @iameskild,

I think this would be a great feature, and I think this change would enable much more extensibility of qhub.  I would like to suggest extending the idea a bit further.

So the goal here, IMO, is to specify the version, branch, or fork, to be installed in CICD... current possibilities for installing qhub would be through pip from pypi or from a git repository, or through conda.

So my suggestion is that the qhub config file should allow something like a `qhub_install_cmd`.  This would allow the user to install qhub from any source via the package manager of their choice.  The sensible default being something like `python -m pip install -U qhub`, probably specifying the version as well.

Looking into this while typing this out, I noticed related references to `pip_install_qhub` and `QHUB_GH_BRANCH`, so it looks like an initial attempt has been made to address this need, although I think some changes would really help bring it all together.

I think the most likely scenario that this supports is using a fork or branch of qhub to be installed in CICD.  This would allow for customization of modules as necessary, or simply updating the Dockerfile for some of the pod images, or configuration of the CICD pipeline, while ensuring that such changes continue to propagate even after re-rendering.

I think this would make it workable to make the type of changes we are doing for troubleshooting this subnet CIDR issue and still have a workable CICD deployment workflow.

Let me know your thoughts.

**Comment by brl0** [comment]
Just a quick note that I think issues like #638 would be somewhat simpler to implement workarounds for in a fork if `qhub_install_cmd` is implemented.
These work arounds may be only temporary if new features are integrated into qhub, but it would make it easier to implement short term fixes in that case.

**Comment by leej3** [comment]
I heartily endorse this addition and am happy to take a stab at implementing it if that moves it along.

**Comment by viniciusdc** [comment]
@danlester @leej3 Any updates on this ?

**Comment by leej3** [comment]
Nothing from me. I addressed my use case with using a branch in the main repo.   It’s convenient but not so reproducible.
