### ISSUE TITLE
[DOC] - Improve screenshots

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/qhub#1134]
The screenshots in the user guide have text that's too small to read. 

[The getting started page](https://docs.qhub.dev/en/latest/source/user_guide/getting_started.html) shows examples of screenshots that should be updated.  There are other pages that are similar and need updates.  I recommend taking screenshots with your browser window less than full width of your monitor.  There is a lot of wasted space in the images and the text is small, like [the Server Options screen](https://docs.qhub.dev/en/latest/_images/qhub_select_profile.png).  The [QHub training cluster page](https://docs.qhub.dev/en/latest/source/user_guide/training.html) has good examples of better screenshots.

The screenshots are also placed before the text descriptions on some pages.

When the screenshot is before the text that describes the screenshot, the guide is awkward to read.  I suggest moving the screenshots after the related text.

Related: #1076

**Comment by costrouc** [comment]
Resolved in #1144
