### ISSUE TITLE
[BUG] - ssh key missing

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/qhub#1136]
### OS system and architecture in which you are running QHub

Ubuntu 20.04.3 LTS (Focal Fossa)

### Expected behavior

- Use `ssh-keygen` to generate a new ssh key
- The ssh key remains in the `.ssh` folder after I logout and back in

### Actual behavior

- After doing the usual steps to generate an ssh key, the key was written to the `/home/jovyan/.ssh` directory and I was able to use git normally to commit and push to GitHub.
- When starting the ssh-agent, this error came up, but the key worked.

```
$ eval "$(ssh-agent -s)"
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Agent pid 194
```

- I logged off for a while.
- I logged back in and my ssh key was missing and I did not have GitHub access.

### How to Reproduce the problem?

- In a new user account, add an ssh key using the following commands

```
ssh-keygen -t ed25519 -C "your_email@example.com"  # writes to the jovyan ssh directory
eval "$(ssh-agent -s)"
ssh-add /home/jovyan/.ssh/id_ed25519
cat /home/jovyan/.ssh/id_ed25519.pub
```

- Test the key by cloning a github repo, committing, and pushing the changes back to github
- log out
- log in
- Try pushing another commit to the same repo

### Command output

```bash session
$ ssh-keygen -t ed25519 -C "e...@gmail.com"
Generating public/private ed25519 key pair.
Enter file in which to save the key (/home/jovyan/.ssh/id_ed25519): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/jovyan/.ssh/id_ed25519
Your public key has been saved in /home/jovyan/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:fYi38...txcI e...@gmail.com
The key's randomart image is:
+--[ED25519 256]--+
|     ..  ..      |
|      .+.+       |
| .. . ..= .      |
|o oE + * o .     |
|+o* + * S = o    |
|.X + . . = + . . |
|=.+ . . . o   o  |
| o.  +.    o  .. |
|   ...o.    .. ..|
+----[SHA256]-----+
$ eval "$(ssh-agent -s)"
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Agent pid 194
$ ssh-add /home/jovyan/.ssh/id_ed25519
Identity added: /home/jovyan/.ssh/id_ed25519 (e...@gmail.com)
$ cat /home/jovyan/.ssh/id_ed25519.pub
ssh-ed25519 AAAA...5qllB e...@gmail.com
```

### Versions and dependencies used.

QHub 0.4

**Comment by costrouc** [comment]
This is now fixed in the 0.4 rc2 release. Going to close for now.
