### ISSUE TITLE
[DOC] - Explain jovyan user directory

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/qhub#1137]
Considering the perspective of someone who may not be familiar with JupyterHub, or maybe even Jupyter, the docs should explain what the jovyan user directory is for. 

This can be a problem when setting up ssh keys for GitHub.  `ssh-keygen` puts the new key in the `/home/jovyan/.ssh` directory.  However, someone not familiar with the jovyan directory will look for the key in the `/home/<user>/.ssh` directory (but it's not there).

Related: #1076

**Comment by trallard** [comment]
Adding these resources for reference:
- https://docs.jupyter.org/en/latest/community/content-community.html#what-is-a-jovyan
- https://discourse.jupyter.org/t/what-is-with-the-weird-jovyan-user/1673

**Comment by costrouc** [comment]
I'm wondering how this is happening since jovyan no longer exists in the docker images (from #1072). Thanks for the issues @ericdatakelly!
