### ISSUE TITLE
Automate oauth provisioning within qhub init for auth0

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#117]

**Comment by costrouc** [comment]
Just one step towards making qhub more automated.

**Comment by yuvipanda** [comment]
Been doing some of that with https://github.com/2i2c-org/pilot-hubs/blob/66511da368e420506955f342550598799b0c71c6/auth.py, has been pretty solid!

**Comment by laisbsc** [comment]
This is currently finished, no? I mean, I'm pretty sure this is the login setup @tylerpotts showed me.

Is it okay if I go ahead and close this one then? :D

**Comment by tylerpotts** [comment]
yep this is done
