### ISSUE TITLE
Supporting multiple environments for deployment

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#118]
Talking with @aktech and @tylerpotts we arrived at a solution after quite a bit of discussion with goals of:
  - minimize changes to the code
  - be as straightforward as possible

We will document that for multiple deployment environments:
  - separate repo per deployment
  - project_id will reflect the environment e.g. `<project>-<environment>`
  - we will remove the `environment` variable from variables.tf to prevent the confusion https://github.com/Quansight/qhub/blob/master/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/variables.tf#L6-L9

**Comment by costrouc** [comment]
We also need documentation about this solution.

**Comment by dharhas** [comment]
What is the process for merging staging into production? Seems like having separate repos would make this workflow harder and make it more likely for staging and production to move out of sync a lot more.

**Comment by costrouc** [comment]
That would require copying over qhub-config.yaml from one repo to the other. @dharhas we could detail here all the solutions we considered. We talked about a lot of different ideas.

**Comment by dharhas** [comment]
I think we should detail the solutions. It is useful for future reference to understand the reasoning.

**Comment by dharhas** [comment]
I guess my question is how do you make sure the rest of the repo stays in sync? i.e. if other parts of the qhub codebase changes or one repo moves to a new version of qhub vs the other.

**Comment by tylerpotts** [comment]
We could put the current version of qhub in the config file, and check the installed version before rendering

**Comment by dharhas** [comment]
That is very fragile. Someone could update qhub and forget to change the version number. Maybe there a way to just depend on a versioned qhub package rather than the current method of copying all the code over using cookiecutter.

**Comment by dharhas** [comment]
i.e currently you are relying of folks to not mess with other parts of the repo.

**Comment by tylerpotts** [comment]
@costrouc I believe this will be enabled when #287 is merged, correct?

**Comment by laisbsc** [comment]
Alright!

I believe we have #287 (local deployment) merged and it is time to chat about this! :D
Do we have a way to make sure this goes through discussion next week? Any specific place I should add this ticket to @tylerpotts @costrouc @aktech?
