### ISSUE TITLE
[BUG] - Minio for Conda-Store needs some way of specifying storage

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1182]
### OS system and architecture in which you are running QHub

Linux (will occur on any OS)

### Expected behavior

Minio storage should be adjustable.

### Actual behavior

Minio storage is fixed to 8 GB.

### How to Reproduce the problem?

Build a lot of conda-store environments.

### Versions and dependencies used.

Latest on main of qhub. 

### Compute environment

GCP

### Integrations

conda-store

**Comment by viniciusdc** [comment]
I see what you mean
```
API: SYSTEM()                                                                                                                                                                               │
│ Time: 15:10:27 UTC 03/23/2022                                                                                                                                                               │
│ DeploymentID: 3821c413-8fef-41a6-840f-03f13e295e87                                                                                                                                          │
│ Error: Storage reached its minimum free disk threshold. (cmd.StorageFull)                                                                                                                   │
│        1: cmd/data-usage.go:56:cmd.storeDataUsageInBackend()        
```

**Comment by viniciusdc** [comment]
Hi @costrouc, it seems we can pass an existing PVC to Minio by https://github.com/minio/minio/blob/fb9b53026d33a35ba6180b415e6e2aa87c75203e/helm/minio/values.yaml#L140, if we create this PVC beforehand and claim it with `dev/qhub-conda-store-minio ` we should be able to control the storage.

**Comment by viniciusdc** [comment]
This is why its using 8Gb, its using the default [K8s PVC storage class](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) 
![image](https://user-images.githubusercontent.com/51954708/159738528-a558150d-f459-4402-b1d2-1f0e9af23295.png)
