### ISSUE TITLE
[BUG] - 0.4 QHub render does not product .gitignore file to ignore terraform produced downloads 

### ISSUE THREAD

**Issue by jkellndorfer** [Quansight/qhub#1204]
### OS system and architecture in which you are running QHub

Linux / AWS 

### Expected behavior

clean redeploy with github actions

### Actual behavior

remote: error: Trace: f7ee2b2e8ee572afea92b84d8b5108190bbd4a9a708bf89976c48eaa9ce39290        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File stages/01-terraform-state/aws/.terraform/providers/registry.terraform.io/hashicorp/aws/3.73.0/linux_amd64/terraform-provider-aws_v3.73.0_x5 is 236.41 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File stages/03-kubernetes-initialize/.terraform/providers/registry.terraform.io/hashicorp/aws/4.7.0/linux_amd64/terraform-provider-aws_v4.7.0_x5 is 238.45 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./        
To https://github.com/ESIPFed/qhub-maple
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ESIPFed/qhub-maple'
Error: Process completed with exit code 1.

### How to Reproduce the problem?

not sure

**Comment by costrouc** [comment]
Ah! Looks like we are missing the gitignore file when we render the directory. Thanks for this catch @jkellndorfer. We will prioritize this next week.
