### ISSUE TITLE
[BUG] - Dask environment not working due to recent package release

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1212]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

When executing the simple dask-gateway [pipeline ](https://docs.qhub.dev/en/stable/source/user_guide/dask_gateway.html?#starting-a-cluster) we should be able to susceffuly launch a dask scheduler pod and a cluster instance.Succesful

### Actual behavior

Executing the `cluster = gateway.new_cluster()` block from the above docs, leads to an unexpected error during spawning of the Dask scheduler. Upon further inspection of the scheduler logs, we can see the same error message as shown in [this issue](https://github.com/dask/distributed/issues/6013).

Even though we currently pin the necessary version so dask within `qhub-dask` meta-package, we still need to add a new exception to avoid the new version of `click` which was the root cause of the problem.

![image](https://user-images.githubusercontent.com/51954708/160916444-e0f5017c-3da1-4d36-aa63-b6b8a0d928fe.png)

### Possible Solution
Add the following to the dask environment upon initialization 
```yaml
 - click ~= 8.1.0 # Or downgrade and pin to 8.0.2
```

### How to Reproduce the problem?

In the description

### Versions and dependencies used.

Latest qhub on main, but the environment build is independent of cli version

**Comment by iameskild** [comment]
Until the issue is resolved upstream, we can pin `click` in our `qhub-dask` meta package. 
https://github.com/conda-forge/qhub-dask-feedstock/pull/11

**Comment by viniciusdc** [comment]
> Until the issue is resolved upstream, we can pin `click` in our `qhub-dask` meta package. [conda-forge/qhub-dask-feedstock#11](https://github.com/conda-forge/qhub-dask-feedstock/pull/11)

Just I quick commented that I only spotted now, we didn`t update `qhub-dask` in the dask-env config to `0.4.0` when we released: https://github.com/Quansight/qhub/blob/56ffa7b8607acd8172b9fb1025bbfeedb80ec6c4/qhub/initialize.py#L214, should this go to post?

**Comment by iameskild** [comment]
That's a good catch! I would say say yes since it's a minor change that should've been caught earlier and will ensure that `click` related issue is actually addressed.
