### ISSUE TITLE
[BUG] - Unable to delete environments that has been created in conda-store

### ISSUE THREAD

**Issue by ychen-ot** [Quansight/qhub#1220]
### OS system and architecture in which you are running QHub

Digital Ocean Kubenetes deployment with QHub 0.4

### Expected behavior

I am part of the "admin" group, and had created an environment via conda-store
When I want to delete the environment, I expect that I can delete it.  Since this is something I had created. 

### Actual behavior

When I click to delete that environment button 

Environment (click on delete from the button) 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/93157550/161325524-33543f69-7eab-4719-896e-36ba4157ef5f.png">

QHub first navigates me out back to my dashboard.  When I went back into conda-store, the environment is still there.  

### How to Reproduce the problem?

1. Create an environment in conda-store - call it filesystem/app
2. After the environment has been created, attempt to delete by selecting the environment, and press the delete button.

### Command output

```bash session
Unfortunately there were no output.
```

### Versions and dependencies used.

- kubectl server version: `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}`

- conda --version:  not sure. `Image:         quansight/conda-store-server:v0.3.10`
- QHUB: `0.4`

### Compute environment

Digital Ocean

### Integrations

conda-store

**Comment by iameskild** [comment]
Hi @ychen-ot, thank you for creating this issue. It appears that we are currently tracking this issue here #1158 and is currently on our roadmap.

Closing this issue. For updates please reference #1158.
