### ISSUE TITLE
Keycloak TF: failed to retrieve cryptographic signature for provider

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1233]
In the past week I have run into the following error a few times when testing the QHub deployment:
- [during the Kubernetes test](https://github.com/Quansight/qhub/runs/5837231631?check_suite_focus=true#step:19:5011)
  - using `mrparker/keycloak v3.7.0`
- [during the end-to-end integration test](https://github.com/Quansight/qhub-integration-test/runs/5856676069?check_suite_focus=true#step:4:8536)
  - using `mrparker/keycloak v3.3.0`

I reran the Kubernetes test again and the issue seemed to go away.

**Comment by viniciusdc** [comment]
Hi @iameskild, it seems to be related to this https://www.terraform.io/cli/plugins/signing#plugin-signing. Maybe during those circumstances, the Hashicorp server was in maintenance (it seems that there are no [recent issues](https://status.hashicorp.com/) with it though)?
