### ISSUE TITLE
[BUG] - "Broken Link Checker" PR Test is Broken

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#1255]
The Broken link checker in PR Test `Documentation linter / check-all-files` seems to be broken.  

Here's an [example](https://github.com/Quansight/qhub/runs/6080617614?check_suite_focus=true).  It appears to be a known [issue](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132).

**Comment by costrouc** [comment]
Wondering if we should disable this task within the tests or just wait it out for it to be fixed?

**Comment by magsol** [comment]
Closing because this has been fixed upstream.
