### ISSUE TITLE
Meta issue for research resource naming restrictions in each cloud provider

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1257]
This is needed to reassure some of our project naming conventions and update any missing constraint present on #761

**Comment by viniciusdc** [comment]
## Naming convention

When you create a new resource on each one of the cloud providers, you will have to provide properties such as a name, project id, bucket, etc... for the resource. As Qhub mainly uses the [`project name`](https://github.com/Quansight/qhub/blob/197121be48e4c0c429e3b4a2c63226d07f2241f9/qhub/initialize.py#L275) from config to populate those attributes, we must ensure that for such cases, the resource attribute/name meets the following conventions (unless specified differently in the documentation for creating that resource):

| Provider | Convention                                                                                                                                                                                                                                                       | Source                                                                                                                                                                                                                                                                                                                                                                                                                               |
|----------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    AWS   | - Must be between 3-47 characters in length;<br>- Must begin with an alphanumeric character, and must only contain alphanumeric lowercase characters, dashes, and underscores;<br>- The name cannot start with AWS or aws.                                       | - [EKS cluster name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#name) <br>- [AWS resource group name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resourcegroups_group#name) <br>- [S3 bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)                                                                             |
|    GCP   | - Be 1-63 characters in length;<br>- Comply with [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt) conventions;<br>- The first character must be a lowercase letter, and all the following characters must be hyphens, lowercase letters, or digits, except the last character, which cannot be a hyphen. | - [google service account id](https://registry.terraform.io/providers/hashicorp/google/4.8.0/docs/resources/google_service_account#account_id); <br>- [google compute network name](https://registry.terraform.io/providers/hashicorp/google/4.8.0/docs/resources/compute_network#name) <br>- [google compute subnetwork name](https://registry.terraform.io/providers/hashicorp/google/4.8.0/docs/resources/compute_subnetwork#name) |
|   Azure  | - Between 3 and 16 characters long;<br>- Start and end with alphanumeric;<br>- lowercase alphanumerics                                                                                                                                                           | - [AKS cluster name](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AKS.Name/) <br>- [Storage Account name](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.Name/) <br>- [Resource Group name](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ResourceGroup.Name/) <br>- [container registry name](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.ACR.Name/)                       |
|    DO    | - Could not find any conventions.                                                                                                                                                                                                                                | - NA                                                                                                                                                                                                                                                                                                                                                                                                                                  |

**Comment by iameskild** [comment]
@viniciusdc thanks a lot for the detailed table!! 

I think it might be worth including the following restrictions as well:
- AWS
  - "Bucket names must not start with the prefix `xn--`."
  - "Bucket names must not end with the suffix `-s3alias`."

Otherwise this looks great :)

**Comment by viniciusdc** [comment]
> @viniciusdc thanks a lot for the detailed table!!
> 
> I think it might be worth including the following restrictions as well:
> 
> * AWS
>   
>   * "Bucket names must not start with the prefix `xn--`."
>   * "Bucket names must not end with the suffix `-s3alias`."
> 
> Otherwise this looks great :)

Hi @iameskild thanks!!! I only looked for the terraform state bucket but didn't [check this one](https://github.com/Quansight/qhub/blob/c3d8d33e1812e26d955824ea61a965c7cb14cfa1/qhub/template/stages/02-infrastructure/aws/modules/s3/main.tf#L1). I will add those to the PR directly. :smile:

**Comment by viniciusdc** [comment]
The only thing that ended up not being added was the restriction for AWS that @iameskild suggested above, once we work on #1267 we can add the missing conventions. For now, I will let this as a comment on the mentioned issue and close this one as the research was used to update #761
