### ISSUE TITLE
[BUG] - Bump Conda-Store to latest version

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1263]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

Uses latest 0.4 version of Conda-Store.

### Actual behavior

Not using the latest conda store version

### How to Reproduce the problem?

Use the latest qhub version

**Comment by iameskild** [comment]
Hey @costrouc do you think we we'll need to bump this version for the next release: https://github.com/Quansight/qhub/issues/1342
