### ISSUE TITLE
`v0.4.1` discussion

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1270]
[Milestone](https://github.com/Quansight/qhub/milestone/9)

Remaining items
- [x] https://github.com/Quansight/qhub/pull/1219
  - Partially dependent on  https://github.com/Quansight/qhub/pull/1234
- [x] https://github.com/Quansight/qhub/pull/1271

**Comment by viniciusdc** [comment]
PR to fix the region issue https://github.com/Quansight/qhub/pull/1271

**Comment by viniciusdc** [comment]
@iameskild @tonyfast @magsol should we let this open for a release postmortem?

**Comment by iameskild** [comment]
That sounds good to me!

**Comment by iameskild** [comment]
Results after upgrading `quansight-beta`:
- [x] GPUs enabled and working (GCP)
  - the gpu node group also scaled down to 0 appropriately   
- [x] panel dashboard working after upgrade to `>0.12.4`
- [x] dask cluster + dashboard tested (not the labextention)
- [ ] Theme `display_version` displaying wrong version (`v0.0.1`)

Results after upgrading `quansight`:
- [x] GPUs enabled and working (GCP)
  - the gpu node group also scaled down to 0 appropriately   
- [ ] panel dashboard not working after upgrade to `>0.12.4`
- [x] dask cluster + dashboard tested (not the labextention)
- [ ] Theme `display_version` displaying wrong version (`v0.0.1`)

The `display_version` is also seems to be layered on top of the "Help" button during creating dashboards:

![Screen Shot 2022-05-10 at 17 23 15](https://user-images.githubusercontent.com/42120229/167746464-b67ccfcd-f54a-4dd6-80b3-257b0099450c.png)

**Comment by viniciusdc** [comment]
Thanks, @iameskild, I think I already know why the version is incorrect, but I didn't take into consideration the help button when adding the theme config.

**Comment by viniciusdc** [comment]
Could you check the output from 'qhub --version' of the installed one?
