### ISSUE TITLE
[BUG] - qhub-conda-store-worker CrashLoopBackoff after updating to QHub 0.4.1 then Enterprise QHub

### ISSUE THREAD

**Issue by MaxTechniche** [Quansight/qhub#1278]
### OS system and architecture in which you are running QHub

Digital Ocean kubernetes deployment via QHub

### Expected behavior

working conda store

### Actual behavior

[qhub-conda-store-worker.log](https://github.com/Quansight/qhub/files/8672263/dev-qhub-conda-store-worker.log)

### How to Reproduce the problem?

update version 0.4.0.post1 -> 0.4.1
then immediately to enterprise qhub 

### Compute environment

Digital Ocean

### Integrations

conda-store

**Comment by viniciusdc** [comment]
Hi @MaxTechniche thanks for opening this issue, and sorry for the inconvenience. One question, do you have direct access to the cluster credentials? If so have you used k9s before?

**Comment by MaxTechniche** [comment]
@viniciusdc Yes. I got the logs via k9s

**Comment by viniciusdc** [comment]
> @viniciusdc Yes. I got the logs via k9s

Great, this seems to me that the available storage for the environments was completely exhausted for minio to create any new ones. One way we could find more details about this is by port-forwarding the Minio Dashboard and checking the current storage usage there.

**Comment by viniciusdc** [comment]
the login and password for Minio dashboard can be found in `secrets` section on k9s by inspecting the yaml config of `qhub-conda-store-minio` (its login is given by `access-key` and pass by `secret-key` in there). They are base64 encoded

**Comment by MaxTechniche** [comment]
>One way we could find more details about this is by port-forwarding the Minio Dashboard and checking the current storage usage there.

@viniciusdc Can you explain to me more of how to port forward that specifically? I don't have much experience with it, although I do know that port forwarding action in k9s.

**Comment by MaxTechniche** [comment]
Thanks @viniciusdc I had forgotten that it forwards from my local machine. Anyway, I was able to get logged in and here is the page when logging in. It shows 5.9 GB used (I believe we have it set up for 60 GiB)
![Minio Login Page](https://user-images.githubusercontent.com/22220702/168403112-87e754d9-5008-409c-905f-57c9910545d8.png)

**Comment by viniciusdc** [comment]
HI @MaxTechniche, sorry for the late feedback. I am not sure, but based on the errors the conda-store worker provider we have two situations:
- The storage for the SQL server might be full or be fully used during the update query above (it seems to be updating a table during a certain request). For a first check, `ssh` into the `conda-store-postgresql-***` pod and go to `/bitnami/postgresql/` and run `df -h data/`, please post the output of that;
- The second error, that might be the cause of the problem is this TImeOut error here `sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00` (which could be timing out due to the above -- not sure), I would recommend to try deleting the worker and SQL pods with `crtl+d` to attempt a re-spawn and check if the errors are the same, be aware that respawning the SQL server might break some cached data.

**Comment by MaxTechniche** [comment]
@viniciusdc Looks like over the weekend the postgresql pod decided to stop working. It shows these logs. Looks like space issues. I have tried deleting the worker and sql pods, but nothing different shows up.
```
postgresql 18:08:40.30 
postgresql 18:08:40.30 Welcome to the Bitnami postgresql container
postgresql 18:08:40.30 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 18:08:40.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 18:08:40.30 
postgresql 18:08:40.32 INFO  ==> ** Starting PostgreSQL setup **
postgresql 18:08:40.34 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 18:08:40.35 INFO  ==> Loading custom pre-init scripts...
postgresql 18:08:40.35 INFO  ==> Initializing PostgreSQL database...
postgresql 18:08:40.37 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 18:08:40.37 INFO  ==> Generating local authentication configuration
postgresql 18:08:40.38 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 18:08:40.41 INFO  ==> Configuring replication parameters
postgresql 18:08:40.44 INFO  ==> Configuring fsync
postgresql 18:08:40.48 INFO  ==> Loading custom scripts...
postgresql 18:08:40.48 INFO  ==> Enabling remote connections
postgresql 18:08:40.50 INFO  ==> ** PostgreSQL setup finished! **

postgresql 18:08:40.52 INFO  ==> ** Starting PostgreSQL **
2022-05-16 18:08:40.539 GMT [1] LOG:  pgaudit extension initialized
2022-05-16 18:08:40.539 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-16 18:08:40.539 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-16 18:08:40.543 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-16 18:08:40.558 GMT [91] LOG:  database system was interrupted while in recovery at 2022-05-16 18:07:54 GMT
2022-05-16 18:08:40.558 GMT [91] HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2022-05-16 18:08:40.610 GMT [91] LOG:  database system was not properly shut down; automatic recovery in progress
2022-05-16 18:08:40.615 GMT [91] LOG:  redo starts at 2/BCA47AF8
2022-05-16 18:08:40.727 GMT [91] LOG:  redo done at 2/BFFFF7F8
2022-05-16 18:08:40.727 GMT [91] LOG:  last completed transaction was at log time 2022-05-14 08:40:38.06008+00
2022-05-16 18:08:40.728 GMT [91] PANIC:  could not write to file "pg_wal/xlogtemp.91": No space left on device
2022-05-16 18:08:40.734 GMT [1] LOG:  startup process (PID 91) was terminated by signal 6: Aborted
2022-05-16 18:08:40.734 GMT [1] LOG:  aborting startup due to startup process failure
2022-05-16 18:08:40.735 GMT [1] LOG:  database system is shut down
Stream closed EOF for dev/qhub-conda-store-postgresql-postgresql-0 (qhub-conda-store-postgresql)
postgresql 18:08:40.30 
postgresql 18:08:40.30 Welcome to the Bitnami postgresql container
postgresql 18:08:40.30 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 18:08:40.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 18:08:40.30 
postgresql 18:08:40.32 INFO  ==> ** Starting PostgreSQL setup **
postgresql 18:08:40.34 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 18:08:40.35 INFO  ==> Loading custom pre-init scripts...
postgresql 18:08:40.35 INFO  ==> Initializing PostgreSQL database...
postgresql 18:08:40.37 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 18:08:40.37 INFO  ==> Generating local authentication configuration
postgresql 18:08:40.38 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 18:08:40.41 INFO  ==> Configuring replication parameters
postgresql 18:08:40.44 INFO  ==> Configuring fsync
postgresql 18:08:40.48 INFO  ==> Loading custom scripts...
postgresql 18:08:40.48 INFO  ==> Enabling remote connections
postgresql 18:08:40.50 INFO  ==> ** PostgreSQL setup finished! **

postgresql 18:08:40.52 INFO  ==> ** Starting PostgreSQL **
2022-05-16 18:08:40.539 GMT [1] LOG:  pgaudit extension initialized
2022-05-16 18:08:40.539 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-16 18:08:40.539 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-16 18:08:40.543 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-16 18:08:40.558 GMT [91] LOG:  database system was interrupted while in recovery at 2022-05-16 18:07:54 GMT
2022-05-16 18:08:40.558 GMT [91] HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2022-05-16 18:08:40.610 GMT [91] LOG:  database system was not properly shut down; automatic recovery in progress
2022-05-16 18:08:40.615 GMT [91] LOG:  redo starts at 2/BCA47AF8
2022-05-16 18:08:40.727 GMT [91] LOG:  redo done at 2/BFFFF7F8
2022-05-16 18:08:40.727 GMT [91] LOG:  last completed transaction was at log time 2022-05-14 08:40:38.06008+00
2022-05-16 18:08:40.728 GMT [91] PANIC:  could not write to file "pg_wal/xlogtemp.91": No space left on device
2022-05-16 18:08:40.734 GMT [1] LOG:  startup process (PID 91) was terminated by signal 6: Aborted
2022-05-16 18:08:40.734 GMT [1] LOG:  aborting startup due to startup process failure
2022-05-16 18:08:40.735 GMT [1] LOG:  database system is shut down
Stream closed EOF for dev/qhub-conda-store-postgresql-postgresql-0 (qhub-conda-store-postgresql)
`

**Comment by MaxTechniche** [comment]
> were you able to run the df -h data/ command above? this should show the amount of space used from the data files.

@viniciusdc I'm unable to because of the pod not being in a running state.

**Comment by viniciusdc** [comment]
> > were you able to run the df -h data/ command above? this should show the amount of space used from the data files.
> 
> @viniciusdc I'm unable to because of the pod not being in a running state.

Oh, of course, my apologies I red thought your comment but lost that part.

**Comment by costrouc** [comment]
@viniciusdc we had this same issue with @rsignell-usgs. @MaxTechniche would you mind listing the storage on all your pvcs. Also could you share the value for your key `storage` in the `qhub-config.yaml` file.

**Comment by MaxTechniche** [comment]
```
storage:
  conda_store: 60Gi
  shared_filesystem: 500Gi
```
Is this what you're talking about @costrouc?
![Screen Shot 2022-05-19 at 9 36 48 PM](https://user-images.githubusercontent.com/22220702/169445640-1526d483-0c1e-4708-a7fa-9cb583480d3b.png)

**Comment by viniciusdc** [comment]
> @costrouc @viniciusdc any update as to why this may be happening, and/or how to get past it? We aren't able to add environments.

Hi @MaxTechniche sorry for the late feedback, with the recent updates we were reviewing old issues and re-prioritizing work. We still haven't had a chance to fully debug this issue. Tomorrow at 10:30 EST we will hold our Dev sync and we will be discussing this. I will also c.c @aktech who is in charge of EQhub to have a look. 

As @costrouc suggested above this looks similar to a previous error where the Minio Storage was not enough to hold the conda-store workers, but as your print above suggests, the current storage for Minio seems reasonable. 

The reason for this bug is still unknown to me, my current guess is that conda-store is requesting a table lookup from its SQL server and that might be corrupted or bugged -- this in return breaks new environments...

Just a quick question, Do the old environments that were built before the migration to EQhub still works? 

I would suggest to:
- Make a backup of all environment yamls present in the current Qhub (this includes user namespace), this will not affect user data. It's only a matter of saving those environments in case you need to rebuild all of them again.
- Permanently delete the PVC for conda-store SQL and redeploy EQhub to re-scale it (thus, requesting  the perspective of @aktech is preferable)

**Comment by aktech** [comment]
Hey @MaxTechniche are you available today or tomorrow for a call? Alternatively you can pick a time for next week here: https://calendly.com/akumar-qs/55min

I think it would be easier to debug with access to the cluster.

**Comment by MaxTechniche** [comment]
@viniciusdc The environments that were there previously do still appear to work.

**Comment by MaxTechniche** [comment]
We spoke with @aktech this morning and he recommended not taking these steps because it might not work with EQhub. We will wait to hear back from him, regarding this issue, on EQhub repo/zendesk.
