### ISSUE TITLE
[ENH] - add a default panel-serve framework in CDSDashboards

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/qhub#1284]
### Feature description

Many panel apps are served using [`panel.serve`](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#serving-multiple-apps), specially multi-page apps.

Serving this kind of app requires a specific CDSDashboards framework, as we already did with @iameskild on another project. To add this, here is the snippet of code to add to `jupyterhub.yaml` : 

```python
      # adding timeout for slow-to-load pages (because of loading time of data and stuff)
      c.VariableMixin.proxy_ready_timeout = 600
      c.VariableMixin.proxy_request_timeout = 600

      # the actual setting that makes it possible : 
      c.CDSDashboardsConfig.extra_presentation_types = ['panel-serve']
      c.VariableMixin.extra_presentation_launchers = {
          'panel-serve': {
              'args': [
                  'python3', '{presentation_path}', '{--}port', '{port}', '{--}address', '{origin_host}'
                  ],
              'debug_args': [],
              'env': {
                  'PYTHONPATH': '/home/jovyan/{presentation_dirname}'
              }
          }
      }
```

This way, the script using `pn.serve` that is given to CDSDashboard, will receive and use 3 important parameters : the port on which to serve the panel app (that is defined by CDSDashboards), the address (useful to build some links) and the origin_host (for websockets origin)

I'll open a follow-up issue to update documentation, to show how to add a panel app with `pn.serve` in CDSDashboards.

### Value and/or benefit

This will allow panel apps served with [`panel.serve`](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#serving-multiple-apps) to work with CDSDashboards. This is specially needed for multi-page apps.

### Anything else?

- This feature is expected to be present by default 
- This has already been done on another project with @iameskild 
- We need this for several of our demo dashboards

**Comment by kcpevey** [comment]
@iameskild can I get an update on this issue?

**Comment by iameskild** [comment]
The associated PR #1070 has been tested and is awaiting final approval :)
