### ISSUE TITLE
[ENH] - Only show conda environments that contain dask in Dask-Gateway options.

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#1295]
### Feature description

Currently all conda environments are shown in the Dask-Gateway options field. If you choose an environment which doesn't contain dask then creating a cluster will fail. 

I propose that only conda environments that contain dask should show up as options in the dask-gateway options choices.

Below, only the `filesystem/dask` is actually usable for Dask jobs. 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/561301/169438195-06090cb9-e650-4277-b1ec-cfb7f25876ae.png">

### Value and/or benefit

combined with #1294, this is the cause of a lot of easy mistakes by the end user. eliminating unusable environments will make usage more robust and less error prone.

**Comment by costrouc** [comment]
@dharhas this is already the case with the following check https://github.com/Quansight/qhub/blob/main/qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/files/gateway_config.py#L113-L117. It only lists the environment if `dask` and `distributed` are within the environment. So I'm going to close this issue.
