### ISSUE TITLE
[ENH] - Upgrade Dask-Gateway to v2022.04

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#1296]
### Feature description

This release is the first in a long time, and with it comes significant improvements and bug fixes. It also brings in a much more recent version of Dask and Distributed. 

### Value and/or benefit

Upgrading to this should make our Dask setup much more stable and is reasonably high priority.

### Anything else?

Changelog: https://gateway.dask.org/changelog.html

**Comment by viniciusdc** [comment]
So inspecting their ([Dask-Gateway](https://github.com/dask/dask-gateway/blob/main/dask-gateway/requirements.txt) and [Distributed](https://github.com/dask/distributed/blob/d6c9dcad7cb4ebdf9643ae1ebb1a1540ada43555/requirements.txt)) respectful requirements, we can get dask pinned automatically in the correct version with only them:
```
dask-gateway == 2022.04
distributed == 2022.04.2
```
Distributed has Dask pinned for each version, so the config above will give us `Dask == 2022.04.2`
