### ISSUE TITLE
[DOC] - Missing information regarding qhub destroy

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1298]
We are currently lacking background information related to the `qhub destroy` command and its functionality in the docs.

The only direct mention of the command and its rough behavior is presented in the [Minukube section for the development guide](https://docs.qhub.dev/en/stable/source/dev_guide/minikube.html?#cleanup), which does not give the user good information on how the command works or what resources if affects.

- So we should start by adding a new section on the User guide page (or admin?), called `cleanup` (to follow the standard) commenting on how to execute the command and which resources it will target for each cloud provider;
-  How State files might affect destroy/redeploy behaviours;
- We might as well, explain how the stages + terraform works on deleting such resources. Also queep in mind that, writing this down could as well affect previous versions of Qhub v0.3.+, trying to get backward compatible documentation would be ideal.

Also, its worth mentioning that even though some "resources" might still exist after deletion, this should be considered an "Exceptional" situation which, if needed, can be covered in a FAQ section -- "" How to manually delete the lingering resource or destroy a Qhub deployment? ""

**Comment by trallard** [comment]
Please x-validate against the [documentation plan](https://www.notion.so/quansightlabs/bc532b6549734ec198454f44f8578188?v=aad438eb66774c6f8481dca61677825d)

**Comment by trallard** [comment]
Thanks @viniciusdc - closing as I have moved to Nebari and will be superseded there
