### ISSUE TITLE
[ENH] - Allow non-filesystem namespaced envs be used in cds dashbords

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1310]
### Feature description

At the moment, only `filesystem` namespaced conda environments can be used when deploying dashboards via CDS dashboards. It would be great to allow users to select any of their own namespaced conda environments as well.

### Value and/or benefit

For instances where the user doesn't have permissions to create `filesystem` namespaced conda environments but still needs to deploy a dashboard, being able to use your own would be extremely convenient!

**Comment by sayantikabanik** [comment]
I am currently facing the same issue. Thanks ✨ having this flexibility would be great
