### ISSUE TITLE
[ENH] - Add Infracost to QHub CI and CLI

### ISSUE THREAD

**Issue by HarshCasper** [Quansight/qhub#1315]
### Feature description

Infracost is a tool that helps us retrieve the difference in monthly cloud cost estimates between the current and planned state of Terraform projects. With wide support for AWS, GCP & Azure, it can be integrated to our QHub CI to help us understand how our costs will change in case we make critical changes to our infrastructure. 

### Value and/or benefit

With the integration to QHub CLI, a user will be able to retrieve the total predicted costs for running QHub on a public cloud provider.

### Anything else?

- [Infracost](https://www.infracost.io/)

**Comment by viniciusdc** [comment]
Hi @dharhas, just to be sure. How do we want this to be included in the OGC sprint, and what should be moved as future work?
- Currently, we have a PR to add this as an action to qhub main repo. Would like to know your thoughts on this as well, just to move accordingly.
