### ISSUE TITLE
[DOC] - Document QHub's CI & CLI Infracost integration

### ISSUE THREAD

**Issue by HarshCasper** [Quansight/qhub#1328]
## Description

Document https://github.com/Quansight/qhub/issues/1315 

Acceptance criteria: 

- Document how QHub's Infracost CI integration computes monthly infrastructure costs
- Document how QHub's Infracost CLI integration computes monthly infrastructure costs locally

**Comment by iameskild** [comment]
Closing in favor of https://github.com/nebari-dev/nebari/issues/57
