### ISSUE TITLE
[BUG] - Flaky `jupyterhub_ssh` test

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1330]
### OS system and architecture in which you are running QHub

Ubuntu

### Expected behavior

The `tests_deployment/test_jupyterhub_ssh.py::test_print_jupyterhub_ssh` test that is run during the Kubernetes test CI seems to occasionally fail for unknown reasons. Rerunning the CI usually results in the test passing. 

[See recent logs for more info.](https://github.com/Quansight/qhub/runs/6884461869?check_suite_focus=true#step:30:87)

### Actual behavior

I expect the behavior to be consistent, either pass consistently or fail consistently. 

I have run into this issue three times in the past week and each time the test appeared to be flaky as running the same test again results in it passing.

### How to Reproduce the problem?

Not known at the moment. Reproducibility seems to be the issue.

### Compute environment

minikube

**Comment by viniciusdc** [comment]
I would suggest increasing the `@pytest.mark.timeout(120)` to `300s`
