### ISSUE TITLE
[MAINT] - Drop Python `3.7`

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1345]
Action plan - drop 3.7 -> push to QHub beta and see how that works out

_Originally posted by @trallard in https://github.com/Quansight/qhub/issues/1341#issuecomment-1164508381_

**Comment by viniciusdc** [comment]
Hi @peytondmurray, just a correction here. We really need to only drop `python == 3.7` for the conda environments that use 'qhub-dask' everything else can still use the other versions of python. The installation of Nebari does not conflicts with the changes made on behalf of 'dask' and 'dask-gateway'.

**Comment by peytondmurray** [comment]
@viniciusdc Yes, we don't strictly speaking _need_ to drop 3.7 entirely - but end of life for 3.7 is rapidly approaching. Is now a good time to drop support across all nebari components?

**Comment by peytondmurray** [comment]
Resolved to only update dask environments for now; fully dropping 3.7 for

* documentation
* JupyterLab
* JupyterHub

will happen later.
