### ISSUE TITLE
[MAINT] - Add Python `3.10` support

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/qhub#1346]
Python 3.10 is stable. This ticket is to collect the requirements around adding support:

- [ ] Add `3.10` to the test matrix
- [ ] Push to qhub-beta
- [ ] ...

**Comment by iameskild** [comment]
Before I forget, another place we'll need to parameterize the python version is in the generated git_ops and linter files:
- [GitLab-CI](https://github.com/Quansight/qhub/blob/38e427b399512c15aca0affbcfe5273ddf5533f8/qhub/provider/cicd/gitlab.py#L39)
- [GitHub-Actions](https://github.com/Quansight/qhub/blob/38e427b399512c15aca0affbcfe5273ddf5533f8/qhub/provider/cicd/github.py#L194)
