### ISSUE TITLE
[ENH] - Add `s3fs` and `pyarrow` to default dask environment

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#1359]
### Feature description

`s3fs` and `pyarrow` are not in the dask environment by default

### Value and/or benefit

You can't access stuff from s3 using dask without `s3fs` and `pyarrow`.

**Comment by trallard** [comment]
@viniciusdc  since we are still in progress with the env work and the docker images can you add this to the `dask` docker image in nebari-dev? 🙏🏽

**Comment by viniciusdc** [comment]
PR created. Once approved, we can have this added to `main` with no issues. Also, our beta deployment uses main so that it can be tested in there as well.

**Comment by trallard** [comment]
This has been merged so we can close this issue!! Thanks folks
