### ISSUE TITLE
[BUG] - Dashboard error: not a conda environment

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/qhub#1376]
### OS system and architecture in which you are running QHub

Ubuntu 20.04.3 LTS (Focal Fossa)

### Expected behavior

Make a dashboard.  Click the link to the dashboard and see the app running.

### Actual behavior

I made a new dashboard for a panel app.  In "Your own dashboards", I clicked the link to the dashboard (https://quansight.qhub.dev/hub/dashboards/openteams-score-demo-app) and the page displayed the error below.

### How to Reproduce the problem?

- Submit a PR to add the conda env to the [config yaml] (https://github.com/Quansight/qhub-deployment-quansight/blob/main/qhub-config.yaml)
- After it is approved and merged, wait a couple of hours to be sure it is built on qhub
- Go to the dashboard page and click "New Dashboard"
- Fill out the name and description, choose All Users and Jupyter Tree, choose bokeh framework (following docs for panel app), choose the conda env from the PR, enter relative path to app.
- Click save
- Under "Your own dashboards", click the link to the dashboard

### Command output

```bash session
Error report from ContainDS Dashboards
Command Running:
python3 -m jhsingle_native_proxy.conda_runner /opt/conda /opt/conda/envs/openteams_score_demo python3 -m bokeh_root_cmd.main /home/ekelly@quansight.com/openteams-score-demo/app.py --port=50133 --allow-websocket-origin=quansight.qhub.dev --prefix=/user/ekelly@quansight.com/dash-openteams-score-demo-app
    
Error output:
None
    
Standard output:
Not a conda environment: /opt/conda/envs/openteams_score_demo
```

### Versions and dependencies used.

conda: 4.12.0
k8s: not able to output the version
qhub: 0.4.3 based on the repo, but whatever is running for quansight right now

**Comment by viniciusdc** [comment]
This error is due to conda-store strict channel list parsing; from the conda-store worker logs we can see the issue with its build:
```
ValueError: Conda channels {'https://conda.anaconda.org/default'} not allowed in specification
```

We are working on a better way of allowing channels, and soon this will not be a problem anymore. Right now though, it's recommended to use `main` or `conda-forge` as the environment channels.

**Comment by ericdatakelly** [comment]
I submitted a new PR with an env build from conda-forge instead.
