### ISSUE TITLE
[BUG] - No module named 'bokeh_root_cmd'

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/qhub#1377]
### OS system and architecture in which you are running QHub

Ubuntu 20.04.3 LTS (Focal Fossa)

### Expected behavior

Open a bokeh/panel app in CDS Dashborads

### Actual behavior

When trying to open the app as a dashboard (by clicking on the link to the dashboard), an error report appears instead.

### How to Reproduce the problem?

Go to `https://quansight.qhub.dev/hub/dashboards/openteams-score-demo-app`

### Command output

```bash session
After clicking the link to the dashboard, I see this page:


Error report from ContainDS Dashboards
Command Running:
python3 -m jhsingle_native_proxy.conda_runner /opt/conda /home/conda/ekelly@quansight.com/envs/openteams_score_demo python3 -m bokeh_root_cmd.main /home/ekelly@quansight.com/openteams-score-demo/app.py --port=35013 --allow-websocket-origin=quansight.qhub.dev --prefix=/user/ekelly@quansight.com/dash-openteams-score-demo-app
    
Error output:
CONDA_PREFIX=/home/conda/ekelly@quansight.com/envs/openteams_score_demo

    
Standard output:
/home/conda/ekelly@quansight.com/envs/openteams_score_demo/bin/python3: Error while finding module specification for 'bokeh_root_cmd.main' (ModuleNotFoundError: No module named 'bokeh_root_cmd')
```
```


### Versions and dependencies used.

It is quansight.qhub.dev.  I don't know how to output all of the versions requested.
conda: 4.12.0


### Compute environment

_No response_

### Integrations

_No response_

### Anything else?

_No response_

**Comment by kcpevey** [comment]
Repo: https://github.com/Quansight/openteams-score-demo

@ericdatakelly are you launching the dashboard from the repo?

Are you launching it with the `panel` option or the `panel serve` option?

**Comment by ericdatakelly** [comment]
I'm not launching from the repo, I cloned the repo to nebari and pointed to the app as a relative path.

- File source: Jupyter Tree
- Framework: bokeh (following suggestion in docs, because it's a panel app)
- Relative path: openteams-score-demo/app.py

Conda env: https://quansight.qhub.dev/conda-store/environment/filesystem/openteams_score_demo/

**Comment by ericdatakelly** [comment]
@kcpevey  I added this to the bottom of `app.py` as a option to use on nebari. 
https://github.com/Quansight/openteams-score-demo/blob/main/app.py#L499

The data file is in a shared directory with read access.

When calling the app from a notebook I just use this:
`app.App(openteams_score=qhub_data_path).layout`

Do you think this can be resolved this week?  We want to discuss the scores on Monday in QShare and it would be helpful for anyone at Quansight to be able to easily view the app.  It would also be a good test of the dashboard for nebari.

**Comment by kcpevey** [comment]
This works as a dashboard shared/users/ekelly/openteams_score_data/OS_ScoreCard_v2.ipynb . Probably the format of the py file is just not acceptable.

**Comment by ericdatakelly** [comment]
Thanks.  I'll ask the team to look at it.

**Comment by ericdatakelly** [comment]
@kcpevey I tried making a dashboard from your notebook but that one failed too.  What environment did you use?  Or perhaps it's a permission issue.

I got this error after trying to create a new dashboard with that notebook:
```
Error report from ContainDS Dashboards
Command Running:
python3 -m jhsingle_native_proxy.conda_runner /opt/conda /home/conda/filesystem/envs/openteams_score_demo python3 /home/ekelly@quansight.com/shared/users/ekelly/openteams_score_data/OS_ScoreCard_v2.ipynb --port 44005 --address quansight.qhub.dev
    
Error output:
CONDA_PREFIX=/home/conda/filesystem/envs/openteams_score_demo

    
Standard output:
Traceback (most recent call last):
  File "/home/ekelly@quansight.com/shared/users/ekelly/openteams_score_data/OS_ScoreCard_v2.ipynb", line 2654, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
```

**Comment by kcpevey** [comment]
@ericdatakelly that error looks more like a formatting issue with the ipynb. Can you run it in jhub? 

I'm using the same environment you are, `openteams_score_demo`

**Comment by ericdatakelly** [comment]
The notebook runs in jlab.  I ran your notebook from the shared folder, and it creates the app in the notebook as expected.

**Comment by trallard** [comment]
So this seems to not be a bug? @ericdatakelly  can we close this issue then?

**Comment by trallard** [comment]
So this seems to not be a bug? @ericdatakelly  can we close this issue then?

**Comment by ericdatakelly** [comment]
Yes.  Thanks for the reminder.  We will figure out what is wrong with our panel app.  It needs to be compatible with CDS Dashboards.
