### ISSUE TITLE
[DOC] Add VS code-server checks to testing checklist

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#1384]
We've had 2 issues recently where vs code updates caused regressions. vscode is a major part of how many devs work on qhub. For me personally, I can't/won't use qhub as a development platform without it. Since its so important, I think we should add some release checks. 

Perhaps:
* VS Code launches correctly
* Python extension installs
* Basic python file can be run through the vs code ui
* Basic python file can be run through the terminal.

**Comment by trallard** [comment]
@iameskild  since this is pertaining to the testing & release checklist will assign to you
