### ISSUE TITLE
[BUG] - Missing `behind_proxy` config for conda-store server

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1403]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

Related to Submit button not properly working from https://github.com/Quansight/conda-store/issues/382. The proper fix requires setting extra server configuration to conda-store.

### Actual behavior

- Button on conda-store does not work

### How to Reproduce the problem?

Attempt to create any new environment on conda-store using the latest version available for Qhub.

**Comment by iameskild** [comment]
closed by #1404
