### ISSUE TITLE
[DOC] - FAQ needs update

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#1411]
In this doc it talks about how users can't create environments, version 0.3 stuff:
https://docs.qhub.dev/en/stable/source/user_guide/faq.html#why-can-t-a-user-just-create-their-own-local-conda-environment-or-edit-the-existing-conda-environments

**Comment by iameskild** [comment]
Hi @rsignell-usgs, thanks for the this find! It definitely looks like this will need to be removed as we migrate our docs to https://github.com/nebari-dev/nebari-docs.

**Comment by trallard** [comment]
Hello again @rsignell-usgs - we have moved our FAQ's to https://www.nebari.dev/faq and will be migrating all of our docs in the upcoming weeks. 

I will go ahead and close this issue as it is resolved now 🙏🏽  thanks for all the helpful feedback and issue reporting you do for QHub
