### ISSUE TITLE
Add `python-dotenv` as a dependency

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1438]
How do people feel about adding [`python-dotenv`](https://github.com/theskumar/python-dotenv) (or something similar) as a dependency for Nebari? 

The motivation for this is to help the user manage their cloud provider credentials and other tokens in a more organized fashion. As Asmi and I have been working on updating the CLI, one useful feature we added is [a way to prompt the user for their credentials if they forgot to set them](https://github.com/Quansight/qhub/blob/a4453893483211a053975eeefef3a44429cf0699/qhub/cli/_init.py#L9). This way the user doesn't need to kill the `init` or `deploy` process just to export these values. It would also be useful for those who manage a lot of deployments (ie. us as developers). I personally use `.envrc` to handle these credentials but I don't think this is a good generic solution to the problem.

However the reason I bring this up now is that the feature Asmi and I worked on (mentioned above) doesn't work on MacOS. This is because running `os.environ` (or `os.putenv`) doesn't permanently store these env vars; once the program exits, these values are flushed ([see python `os` docs for more info](https://docs.python.org/3/library/os.html#os.environ)). See this example:

```python
In [1]: import os

In [2]: os.environ["TEST"] = "hello world"

In [3]: os.environ.get("TEST")
Out[3]: 'hello world'

In [4]: exit
```
Then:
```bash
eskild@MBP21 ~/Documents/sandbox/test qhub-dev
$ env | grep TEST
eskild@MBP21 ~/Documents/sandbox/test qhub-dev
```

If I'm making a silly mistake, please let me know!! Otherwise, I'd be happy to hear what others have to say about adding `python-dotnev`.

**Comment by kcpevey** [comment]
I think dotenv would be a good addition. We'd be able to add a `.env.tpl` to give people an example structure of what to fill out. I feel like that would be very helpful.

**Comment by trallard** [comment]
AFAIK this has now been discarded after our discussions re the CLI and authentication. 
What we could work on instead is a "best practices" section in the docs for credential management WDYT?

**Comment by iameskild** [comment]
@trallard yeah this can be closed now. Adding "best practices" to the docs is a good alternative 🤘
