### ISSUE TITLE
terraform destroy fails - AWS

### ISSUE THREAD

**Issue by filippo82** [Quansight/qhub#144]
Hi all,

after successfully creating a QHub deployment and quickly testing it with my own GitHub user I wanted to try to also tear down the full deployment. There is no existing documentation for this process so I have naively tried this:
```
cd infrastracture
terraform destroy
```
Unfortunately, the "destruction" fails.

The initial issue I see is related to Issue #17. The links provided therein allowed me to manually delete the persistent volumes. Then a subsequent execution of `terraform destroy` hung for 15 minutes till it resulted in another terraform error (unfortunately I do not have the output but was something like "Unauthorised ..."). Then I tried a `terraform plan -destroy` and decided to destroy the last resource shown by the output: `terraform destroy -target module.network.null_resource.dependency_setter`. This ended up tearing down the EKS cluster but then I had to do a lot of house cleaning from the AWS Console (VPCs, resource groups, EBS, EFS, ...).

My guess is that this has to do with:
* the existence of a "protected" storage probably created because I had started a Jupyter server with my user
* the order of the destruction of resources (performed by `terraform destroy`) is not the right one. This might be linked to this [PR from the archived `qhub-ops` repo](https://github.com/Quansight/qhub-ops/pull/31) where @aktech clearly explains that the terraforming process needs appropriate dependences (Kubernetes cluster first, than the rest).

I was wondering if there are any existing instructions on how to properly tear down QHub.

I would be happy to help with further testing.

Thank you.
-Filippo

**Comment by laisbsc** [comment]
Hey @filippo82!

Thank you so much for calling our attention to this. We are currently revamping our docs and would love your input on that, indeed!

I will add the docs for the *standard procedure* for destroying QHub to my to-do list. For now, what may help is that we have a new CLI command `qhub destroy -c qhub-config.yaml` that [destroys the infrastructure](https://github.com/Quansight/qhub/#removing-qhub) created by QHub.

Does that help at all?

Chat soon.

**Comment by laisbsc** [comment]
Hey @filippo82, 

any updates on this issue? Any other problems?

**Comment by filippo82** [comment]
Hi @laisbsc! Thanks a lot for the reminder.

Unfortunately, I was quite busy in the last weeks and I didn't have time to "play" with qhub (I can only do that in my free time 😅). I'll definitely have time for it next week. I'll then get back to you.

Thanks again.
-Filippo

**Comment by laisbsc** [comment]
Hey @filippo82!

Awesome! We had a few breaking changes released on the last version of QHub so if you run into any issues, make sure to let us know.

Thanks a million and hope you're good.

**Comment by rsignell-usgs** [comment]
We generated a new qhub deployment, and just remembered that our old one is still running:
```
(aws) C:\Users\rsignell\Documents\GitHub\qhub-esip>aws eks list-clusters --profile esiplab
{
    "clusters": [
        "esipfed-deployment-dev",
        "esipfed-qhub-dev"
    ]
}
```
We plan to do `terraform destroy` from the old repo to destroy the resources associated with the old deployment.

Is there any chance of destroying something by mistake that is being used in the new deployment?

**Comment by tylerpotts** [comment]
@rsignell-usgs We actually have a `qhub destroy` command now. With your latest qhub-config.yaml file from the repo, run `qhub destroy -c qhub-config.yaml`

**Comment by tylerpotts** [comment]
@rsignell-usgs Though on second thought with the age of your deployment, you might be better off running `terraform destroy` inside of the infrastructure folder

**Comment by tylerpotts** [comment]
Closing this in favor of #605 where we are tracking the need to document manually destroy AWS resources
