### ISSUE TITLE
Rename `qhub-jupyterhub-theme` -> `nebari-jupyterhub-theme` and update colors+logo

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1446]
Source repo - https://github.com/Quansight/qhub-jupyterhub-theme

Should align with nebari/design

**Comment by iameskild** [comment]
Can we also update the colors and default logo (removing the Quansight one) during this same step?

**Comment by pavithraes** [comment]
Shall we include updating the [login page default messages](https://github.com/nebari-dev/nebari-jupyterhub-theme/blob/master/qhub_jupyterhub_theme/templates/login.html) as well?
