### ISSUE TITLE
Update release checklist - replace QHub -> Nebari and swap to CalVer

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1451]
📝  Decision notes: https://www.notion.so/quansightlabs/All-hands-ffb7b83e7a9c4adb92e49356e00aef7b

We agreed to follow the same as Dask - `YY.M.micro` where:
- `micro` number of release per month (starting at 1 - no zero padding)
- `M` month no zero padding

🏷 First release `2022.10.1`

open against https://github.com/Quansight/qhub/tree/release/2022.10.1

**Comment by iameskild** [comment]
@trallard I believe the checklist is ready-to-go :)
