### ISSUE TITLE
END-GAME - Cut last `qhub release`

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1455]

**Comment by trallard** [comment]
@iameskild  and @viniciusdc  we need a release captain for 

1. last qhub release 
2. first nebari release

Do you have any preference? or shall I assign one and one?

**Comment by iameskild** [comment]
@trallard I thought `v0.4.5` was going to be the last qhub release?

**Comment by trallard** [comment]
Yup - adding this step in case there are any hotfixes or patches needed post 0.4.5 release

**Comment by trallard** [comment]
No last release needed

**Comment by trallard** [comment]
No last release needed

**Comment by trallard** [comment]
No last release needed
