### ISSUE TITLE
Ingress throwing time out error on GCP deployment

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#146]
Trying to deploy to GCP with the current branch of qhub master and terraform `v0.13.5` results in the following error:
```
 Error: timed out waiting for the condition

  on .terraform/modules/kubernetes-ingress/modules/kubernetes/ingress/main.tf line 7, in resource "helm_release" "ingress":
   7: resource "helm_release" "ingress" {
```

**Comment by aktech** [comment]
That's a very generic error from helm and can happen due to various reasons. One of the ways to get the root cause is via:
```
kubectl get events --sort-by=.metadata.creationTimestamp
```

**Comment by tylerpotts** [comment]
As of this morning, this is resolved without me actively changing anything. After chatting with @costrouc and @prasunanand, it seems this happens occasionally. The current theory is that the ingress pod wasn't finished deploying in kubernetes and threw this error.

Closing for now
