### ISSUE TITLE
conda-forge create `nebari-dask` and `nebari` feedstocks

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#1466]
Will need to create the two new feedstocks

- [ ] nebari-dask
- [ ] nebari

**Comment by trallard** [comment]
@viniciusdc  do we have nebari-dask in conda-forge?
Might be worth updating this in the docker images too

**Comment by viniciusdc** [comment]
Sorry, @trallard, I just created the PR, but it's easy to get that merged. Once the listed maintainers approve their listing in the PR we are pretty much done. https://github.com/conda-forge/staged-recipes/pull/20879
