### ISSUE TITLE
[ENH] - Add endpoints to JHub control panel

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1479]
### Feature description

When on the jupyterhub control panel, it would be great to link to all of the endpoints (`argo`, `conda-store`, `monitoring`, `auth`). 

### Value and/or benefit

This would make those endpoint discoverable. At the present, it requires remembering what those endpoints are in order to navigate there.

**Comment by aktech** [comment]
Created a PR here: https://github.com/Quansight/qhub-jupyterhub-theme/pull/16
