### ISSUE TITLE
qhub.dev and qhub.readthedocs.io not matching

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#148]
qhub.dev and qhub.readthedocs.io are not matching. Qhub.dev has the latest version of the docs, while qhub.readthedocs.io is on an old version

**Comment by filippo82** [comment]
Hi Tyler, 

I've opened literally the same issue  #145 two days ago.

**Comment by tylerpotts** [comment]
@filippo82 Thanks for pointing this out. Was going off the gitter channel and didn't realize you created one already.

**Comment by filippo82** [comment]
💪🏻💪🏻💪🏻
