### ISSUE TITLE
Testing checklist for v0.4.5

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1482]
# Testing Checklist

*Use/modify this checklist to capture the platform's core services that need to be manually tested .*

## Manual testing: core services

If the integration tests for all of the cloud providers are successful, that is a good sign!
However, the following core services still need to be manually validated (until we can automate them).

At minimum, the following services will need to be tested:
- [x] [Log into keycloak as root user](https://nebari-docs.netlify.app/how-tos/configuring-keycloak#change-keycloak-root-password)
  - [x] [Add a user](https://nebari-docs.netlify.app/how-tos/configuring-keycloak#adding-a-nebari-user)
- [x] [Log into conda-store and create](https://nebari-docs.netlify.app/tutorials/creating-new-environments)
  - [x] a conda environment in a shared namespace and,
  - [x] a conda environment in your personal namespace
- [x] [Launch dask-gateway cluster, test auto-scaler and](https://nebari-docs.netlify.app/tutorials/using_dask)
  - [x] [Validate that the dask-labextention is working](https://nebari-docs.netlify.app/tutorials/using_dask#step-5---viewing-the-dashboard-inside-of-jupyterlab)
- [x] [Create a basic CDS Dashboard](https://nebari-docs.netlify.app/tutorials/creating-cds-dashboard)
- [x] [Open VS-Code extension](https://nebari-docs.netlify.app/tutorials/using-vscode)
  - [x] [Add the Python extension](https://nebari-docs.netlify.app/tutorials/using-vscode#adding-extensions)
  - [x] [Create a `.py` file and run it](https://nebari-docs.netlify.app/tutorials/using-vscode#running-python-code)

**Comment by viniciusdc** [comment]
Couldn't launch VScode from a local deployment: 
![image](https://user-images.githubusercontent.com/51954708/194726822-4c1f1af5-652d-446d-a71a-9c63385c0bbc.png)

**Comment by viniciusdc** [comment]
Its working on a cloud deployment!

**Comment by iameskild** [comment]
Tested all of the above on Azure. Only minor issue was with the VSCode extension library not loading. This might also be the case existing deployments.

**Comment by viniciusdc** [comment]
> Tested all of the above on Azure. Only minor issue was with the VSCode extension library not loading. This might also be the case existing deployments.

Was the error above you saw when launching VScode? if that's the case, the problem was the certs, its the same situations as the dashboards

**Comment by iameskild** [comment]
I tested this again, it seems to be working now...
