### ISSUE TITLE
Error: fatal: could not read Username for 'https://github.com

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#150]
I'm sure this is user error, but I don't know what step I missed or screwed up. 

My qhub is up and running, but when I tried to updated the environment via a Pull Request, the GitHub action "qhub" failed on the "Fetching the repository" step, with "Error: fatal: could not read Username for 'https://github.com":

 ![2020-10-31_16-21-07](https://user-images.githubusercontent.com/1872600/97792929-40819300-1bbb-11eb-8a71-d0a57aed4a09.png)

Hoping this will help not just me but others.

**Comment by dharhas** [comment]
@prasunanand Have you seen this before?

**Comment by rsignell-usgs** [comment]
Could it be because I have a hyphen in my username ("rsignell-usgs")?

**Comment by tylerpotts** [comment]
@rsignell-usgs I actually have seen this before. My username used to be `t-potts` and I specifically removed the hyphen for this reason (a short term hack, admittedly)

I've created issue #152 to track this

**Comment by dharhas** [comment]
@tylerpotts had a lot of issues with the hyphen and finally just changed his GitHub username. Tyler sis you ever find a workaround?

**Comment by tylerpotts** [comment]
> you ever find a workaround?

@dharhas Looks like we commented simultaneously. My workaround was to change my github username

**Comment by rsignell-usgs** [comment]
Guys, I decided to update all four github secrets to make sure they were set correctly, and the problem went away. 

Where is the tail-between-legs emoticon?   😞
