### ISSUE TITLE
Create a bot to pull conversations from QHub Gitter to Github issues

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#154]
When people ask questions in gitter and they get answered (via threaded replies), a bot which on trigger can push the whole conversation with the title of the question to Github issues (obviously closed it, if it was answered).

The benefit of that is when someone google's "how to do X in qhub?" it is found via github issues very easily and also when someone asks a question on slack we can direct them to the solution on one of the Github issues. I think we have a similar bot for pushing things on discourse, we can create/find/add one for QHub gitter channel too.

**Comment by laisbsc** [comment]
This sounds like a very cool idea! I think that since we've decided to use the [GitHub Discussions](https://github.com/Quansight/qhub/discussions) as our main media, I will just close this issue.

Feel free to reopen in case you want to work on it anyhow 😄
