### ISSUE TITLE
add basic user guide notebooks to qhub

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#157]
This issue is intended more as a discussion than a requirement.

It would be nice to have some notebooks either in the repo, or automatically included in the home directory that would walk through some of the basic functionalities of qhub. The most immediate need I see is a notebook on spinning up dask

**Comment by laisbsc** [comment]
My idea is to have a 'training repo'. A place where we have all the material for people to choose use-cases and see applications for QHub.
We can also make them into tutorials (a bit more interactive) and use the material on coding sprints.

For starters, we can have a demo link with the Dask-Notebook in the docs. You reckon we could make this happen? You can code and I can write the docs for it 🚀

I will send you a box of the best Irish chocolates you've ever eaten!
