### ISSUE TITLE
qhub api discussion

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#172]
- get rid of `init`, only have `render, deploy, destroy...`

- [x] create a `qhub destroy` command
- `qhub destroy` will automatically retry the destroy
- if it fails destroys anything with a unique tag
- have warning messages and require user input if it will destroy data

Needs further discussion

**Comment by filippo82** [comment]
Hi, I am linking here issue #143 before closing it since it seems that it will be discussed here too.

**Comment by laisbsc** [comment]
links #219
