### ISSUE TITLE
GPU worker scheduler uses the same nodegroup as the workers

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#186]
Normally it's not a problem that the scheduler is the same nodegroup as a the workers. In the case of GPU workers, this means that an extra GPU will be spun up for the scheduler that can't be used for GPU calculations.

**Comment by prasunanand** [comment]
@tylerpotts AFAIK, we can change the `node-selector` for the pods. We will point those schedulers to be scheduled on `general` nodepool.

**Comment by tylerpotts** [comment]
Not a problem
