### ISSUE TITLE
namespace like feature for qhub for partiioning user and groups

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#19]
This feature was discussed in regards to quansight training and having multiple organizations of people logging into the same cluster. We need a sane way to restrict visibility of one organization from another (including the existence of their shared resources).

The idea is that even though the users are sharing the same resources they should have absolutely no visibility into the fact that they are sharing the resources with another group.

**Comment by tylerpotts** [comment]
Closing because we can write <namespace>-<name>. This should resolve this issue
