### ISSUE TITLE
Single sign on for web apps

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#190]
It would be great to have an ability to have web apps behind the authentication for Jupyterhub.

**Comment by laisbsc** [comment]
Hey @brl0, thank you for the suggestion. I need a little bit more information before making a ticket out of this to add to our list of ideas of possible improvements for QHub.

Is there a reason why you'd like this feature to be added? How would it benefit QHub users?

Any ideas about how we would implement it?

Thanks :)

**Comment by brl0** [comment]
@laisbsc,

This is something that has been discussed with @costrouc and @dharhas in the past, they would probably have a better idea of what is needed to implement.

The idea is to integrate panel apps into qhub in such a way that would allow for those apps to use cluster resources such as the dask gateway to access workers on the cluster, conda store, and nfs, as well as hopefully sharing a common authentication and user management configuration.

The goal would be to make it easy to deploy end user facing big data processing apps.

**Comment by dharhas** [comment]
This is related to #267
