### ISSUE TITLE
Adding resource quotas for users

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#20]
Using https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass. Will need a priority class per user

**Comment by costrouc** [comment]
This issue will depend a lot on unifying the qhub deployment in PR https://github.com/Quansight/qhub-terraform-modules/pull/11. This way we can easily annotate all user resources so they can be covered by these quotas.

**Comment by laisbsc** [comment]
Depends on Removing Helm and Updating Gast Gateway milestones to be completed first.
