### ISSUE TITLE
Deploying without a dask worker defined in config causes cookiecutter to fail

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#203]
Right now a configuration for a dask worker is required under `profiles` or cookiecutter throws an error. A dask worker shouldn't be required for qhub to work

```
cookiecutter.exceptions.UndefinedVariableInTemplate: Unable to create file 'infrastructure/dask-gateway.yaml'. Error message: 'dict object' has no attribute 'dask_worker'
```

**Comment by tylerpotts** [comment]
This is still an issue. When commenting out the default images for dask_gateway and default_images, along with the dask_worker profile this error is thrown:

```
$ qhub render -c qhub-config.yaml -o ./

Problem encountered: 3 validation errors for Main
default_images -> dask_worker
  field required (type=value_error.missing)
default_images -> dask_gateway
  field required (type=value_error.missing)
profiles -> dask_worker
  field required (type=value_error.missing)
```

**Comment by viniciusdc** [comment]
> This is still an issue. When commenting out the default images for dask_gateway and default_images, along with the dask_worker profile this error is thrown:
> 
> ```
> $ qhub render -c qhub-config.yaml -o ./
> 
> Problem encountered: 3 validation errors for Main
> default_images -> dask_worker
>   field required (type=value_error.missing)
> default_images -> dask_gateway
>   field required (type=value_error.missing)
> profiles -> dask_worker
>   field required (type=value_error.missing)
> ```

Should we hardcode the dask-gateway/dask... images and worker profiles to cookiecutter as a preemptive solution? or would be best to transform the dask* integration as an feature flag?
