### ISSUE TITLE
Rebase QHub image from debian to `ubuntu:20.04`

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#205]
I would like to propose that we switch the base image used in QHub from `debian:10.3-slim` to `ubuntu:18.04`.  In terms of image size, the former weighs in at 26.47MB, while the latter is 25.88MB, so this is not an issue.  The reason for this suggestion is that this would more closely match the OS choices available on GitHub Actions based on information available here.  I was looking at this because I am having some issues getting an environment solved on QHub to install in GitHub actions.  Also, I think it would provide more confidence having our tests run through GitHub Actions be in a more similar environment to where we actually run the code.

**Comment by verhulstm** [comment]
I love it :) i have seen many issues related to this on other projects. I try to consolidate more or less everything to ubuntu:18.04 (16.04 for GPU ML). It seems to make things a lot easier. Personally, i don't worry much about image size.

**Comment by verhulstm** [comment]
my firm uses GitHub actions for many repos all with the same ubuntu config framework. https://github.com/terminal-labs/inflation/blob/master/.github/workflows/build.yml

**Comment by laisbsc** [comment]
After tech discussion, we've decided to Rebase to Ubuntu 20.04.

**Comment by brl0** [comment]
I still think this would be a good change to make.

**Comment by viniciusdc** [comment]
@aktech This was solved already right?

**Comment by brl0** [comment]
@viniciusdc, This has not been changed yet.  

The relevant files are in `qhub/qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.*`, for example see [here](https://github.com/Quansight/qhub/blob/0dff7067391d4d46e6863fd6f35ded867dc8f03a/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image/Dockerfile.jupyterlab#L1).

I still think being closer to the GitHub Actions environment is a compelling reason for the change.

Also see PR #319, which had proposed this change along with several other updates and clean ups.  I am going to close that PR since it is so outdated, but the highlights were:
> - Update docker images to ubuntu:20.04
> - Use miniforge rather than miniconda
> - Push docker images to both github sha tag and latest tag
> - Add common tools to jupyterlab image
> - Update to jupyterlab 3

**Comment by toonarmycaptain** [comment]
I attempted to make progress on this:
- I changed the `Dockerfile.dask-worker`, `Dockerfile.jupyterhub`, `Dockerfile.jupyterlab` in that qhub templates directory mentioned above, in the package in my conda install (these were the only images with an OS base.
- Then I deployed qhub.
-  The resulting generated /image directory has the same three Dockerfiles, all showing the same base `FROM ubuntu:20.04


When I go into the running pods and run `cat /etc/os-release`, I find:

| pod name | OS |
|---|---|
| hub-5c66bf8774-ndddd                            |  Debian GNU/Linux 10 (buster)   |
| jupyter-toonarmycaptain-40hotmail-2ecom   |  Debian GNU/Linux 10 (buster)   |
| nfs-server-nfs-5478548cf6-mw898                 |  CentOS Linux 7 (Core)   |
| qhub-conda-store-84775b777f-gmx6g               |  Debian GNU/Linux 10 (buster)   |
| qhub-daskgateway-controller-6b464df8d8-2hwx7    |  Debian GNU/Linux 10 (buster)   |
| qhub-daskgateway-gateway-6ddb74988f-grg4r       |  Debian GNU/Linux 10 (buster)   |
| qhub-jupyterhub-sftp-658687f6c5-rqdf2           |  Ubuntu 20.04.1 LTS   |
| qhub-jupyterhub-ssh-c94b45b57-7lgrt             |  Debian GNU/Linux 10 (buster)   |

I've verified that the installation and it sees to run normally, able to run notebooks etc, but is this what I should expect to see? I expected at least the server for the user `toonarmycaptain` to be a Ubuntu base, as that's what both jupyter Dockerfiles showed.

**Comment by toonarmycaptain** [comment]
The docker images are rebased by #816  - does that close this issue, or are the changes referenced by @viniciusdc regarding pushing Docker images to github/latest tags and adding tools to jupyterlab images needed also?

**Comment by costrouc** [comment]
Yeup we can consider this issue closed. The images will push themselves since they are in main.
