### ISSUE TITLE
Remove Helm

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#224]
We would like to gradually remove [Helm](https://helm.sh/) from QHub's dependencies.

* Why is it necessary?
Because Helm has created several issues, such as the one on [discussion #218](https://github.com/Quansight/qhub/discussions/218).

* How will we do this?
The team suggested Sprints as *modus operandi* since it is a laborious task.
---
### Implication
 Once the Helm dependency is removed we will be able to Upgrade Dask Gateway #62 #215

**Comment by laisbsc** [comment]
This is the epic to track the issue on Helm's removal from QHub. Once we have the initial sprint meeting, we can start creating issues to link to this epic.

@tylerpotts how does that sound?

**Comment by tylerpotts** [comment]
We created a chart showing the current plan for the infrastructure without Helm. We have yet to create issues, but will do that as we spend more time on this

![Removing Helm QHub](https://user-images.githubusercontent.com/49161327/103664003-60289500-4f37-11eb-9753-f7d0886d8d50.png)

**Comment by verhulstm** [comment]
what "deployment pattern" do you want to use instead of helm?

**Comment by costrouc** [comment]
@verhulstm right now we have three template languages in use on qhub:
 - cookiecutter(jinja2)
 - terraform
 - helm

Having these three layers has made it really difficult to onboard people for new development and helping them know where to contribute. Terraform has a kubernetes provider https://github.com/hashicorp/terraform-provider-kubernetes-alpha which has support for crds and required kubernetes version >= 1.18. We're really trying to remove as many layers of abstraction as possible ... that said I'm not a huge fan of terraform kubernetes syntax and translating the charts. 

Most importantly I've found helm charts are often opinionated and dont provide features that we need the two that come to mind are dask-gateway and the zero to jupyterhub helm charts.

**Comment by costrouc** [comment]
To break this into pieces that need to be done:
 - [ ] jupyterhub
 - [X] ingress
 - [ ] dask-gateway
