### ISSUE TITLE
QHub shutdown feature

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#227]
> Similar issue/solution mentioned on #99 

## Description
As a user, I would like to be able to deactivate my notebooks without the need to shut them down and lose all my disks, but they are also expensive to just keep it running.

## Suggestion
A QHub shutdown CLI feature, which would keep the deployment state (i.e., persist the disks) but deactivate all other resources, removing the waste of resources.

## Context
This would be a useful feature for the community since spinning clusters is expensive and having a command to simply 'suspend' the allocated resources without major downsides would be quite useful (internally and externally).

### To be discussed:
- [ ] Where in the roadmap this fits?
- [ ] Implementation ideas (check [comment](https://github.com/Quansight/qhub/issues/227#issuecomment-755384525) with suggestion).

**Comment by costrouc** [comment]
So I think there may be some issues with shutting down while keeping the storage. The storage is associated with the kubernetes cluster itself via pvcs. Ideally this comes down to having a good backup and restore operation.

Id's consider this issue to be resolved by https://github.com/Quansight/qhub/issues/99.

**Comment by tylerpotts** [comment]
Here are my thoughts on how we could make this work by backing up the shared volume to block storage. These would be the steps:
- backup NFS to block storage
- destroy old QHub
- deploy new QHub when ready
- restore data from block storagew to NFS

The NFS volume is quite slow, so it could take upwards of several hours for the data to restore. I wouldn't recommend this solution unless the cluster wasn't needed for more than a month. Diagram below.

![Blank diagram](https://user-images.githubusercontent.com/49161327/103788870-f5458f80-5004-11eb-9742-cdfade1562e2.png)

**Comment by laisbsc** [comment]
> Id's consider this issue to be resolved by #99 when it is completed.

Awesome! I will mark this as a #99's duplicate then and close the issue.
