### ISSUE TITLE
Application-Wide Styling

### ISSUE THREAD

**Issue by anirrudh** [Quansight/qhub#23]
This is an issue to document any discussions had regarding the styles of the application, as well as the documentation. 

Currently, the frontend uses a framework called [vuetify](https://vuetifyjs.com/en/), the Vue-ified version of Material UI. Essentially, the core colors for the theme are put into a client-side plugin;
they can be seen at `/plugins/vuetify.js` when looking at the `frontend` branch. 

This will eventually be moved to a css file to have a consistent color palette across all "Qhub" related applications.

**Comment by tylerpotts** [comment]
Decided not to go with vuetify
