### ISSUE TITLE
Local deployment implementation

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#232]
## As a user, I want to be able to test my QHub projects locally using a Kubernetes cluster.

This will require:
* Password-based authentication
    * OAuth requires certificates, local doesn't have certificates
* Make HTTPS optional
* Ideally it will use MiniKube.
> NOTE: MiniKube can run on Docker, its use will allow for local testing to be done through CI checks.

This is an **epic** ticket, i.e. its purpose is to link all issues related to this implementation.

**Comment by costrouc** [comment]
Closing in favor of epic https://github.com/Quansight/qhub/issues/234
