### ISSUE TITLE
[documentation] How do I update/edit a conda environment

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#242]
I have an existing qhub deployment and I'd like to update the environment and redeploy. I gathered from the docs that I should update `/qhub-config.yaml` which is in the root of my repo. 

I'm confused why the same envs are in `/environments/environment.yml`. Do I need to update those too?

When I updated `qhub-config.yaml` it triggered some gh actions (that I assume came from this qhub setup). It completed several things, but didn't actually update my instance. I'm not sure what I'm missing. 

Last thing - I have dev ops people on my team which can help me resolve these things, but I think we should improve the docs around maintenance of existing qhub deployments.

**Comment by laisbsc** [comment]
Hey there @kcpevey 👋🏽 

Thank you so much for your question! It is a very good one.

> I have an existing qhub deployment and I'd like to update the environment and redeploy. I gathered from the docs that I should update `/qhub-config.yaml` which is in the root of my repo.
> 
> I'm confused why the same envs are in `/environments/environment.yml`. Do I need to update those too?
> 
> When I updated `qhub-config.yaml` it triggered some gh actions (that I assume came from this qhub setup). It completed several things, but didn't actually update my instance. I'm not sure what I'm missing.

When you update or destroy your QHub environment you will need to redeploy the project, which will check the environments and apply Terraform modules.
You can use the command `qhub deploy -c qhub-config.yaml --dns-provider <cloud_provider_name> --dns-auto-provision`.

It can take up to 20 but bear with it.

> Last thing - I have dev ops people on my team which can help me resolve these things, but I think we should improve the docs around maintenance of existing QHub deployments.

I completely agree. I am merging some changes to the README very soon and please, keep the questions coming. This one will go to the FAQ. So thanks a million for your contribution 😄 

Chat soon.

**Comment by tylerpotts** [comment]
@laisbsc I think there is some confusion cause by @kcpevey use of the word `redeploy`. What she's trying to do is add/edit an existing environment in the `qhub-config.yaml`. What you wrote:
> When you update or destroy your QHub environment you will need to redeploy the project, which will check the environments and apply Terraform modules.
> You can use the command qhub deploy -c qhub-config.yaml --dns-provider <cloud_provider_name> --dns-auto-provision.
only applies if a person is trying to delete/redeploy an existing QHub cluster, which would involve tearing down the kubernetes cluster and spinning a new one back up.

Renamed this to `How do I update an environment/edit a conda environment` and re-opening

**Comment by tylerpotts** [comment]
Here's my rough outline of how to create/edit a conda environment:

- Create a new branch
- Make changes to the qhub-config.yaml file under the `environements` key ([yaml](https://yaml.org/) info here. Think of each level as a dictionary key, where indenting by two spaces sets the values for that key.)
- For a new environment, add two spaces below the `environments` key:
```
environments:
  "example.yaml":
```
- Utilize a structure similar to a conda yaml config file for the rest of the config, but indent everything 4 spaces: 
```
environments:
  "example.yaml":
    name: example
    channels:
    - conda-forge
    dependencies:
    - python
    - pandas
```
- Commit the changes, and make PR into master
- Wait 5-30 minutes depending on the complexity of the environment
- If the environment is not available after 30 mins, check the latest log file from a user instance in the `/home/conda/store/.logs` directory

**Comment by tylerpotts** [comment]
re-opening since the PR to close this wasn't finished

**Comment by rsignell-usgs** [comment]
On the ESIP qhub deployment, when we make make modifications to the environments the conda-store pod goes pending for approximately 10 minutes before finally coming back.   Then takes about 10 more minutes for the environment to actually show up. on the conda-store. 

Here's the "describe" from k9s on the conda store pod detailing what is happening.  Is this expected behavior?

```
Name:         conda-store-conda-store-8f8d9bfdc-j7qkl
Namespace:    dev
Priority:     0
Node:         ip-10-10-0-39.us-west-2.compute.internal/10.10.0.39
Start Time:   Fri, 19 Mar 2021 07:06:06 -0400
Labels:       pod-template-hash=8f8d9bfdc
              role=conda-store-conda-store
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.10.0.179
IPs:
  IP:           10.10.0.179
Controlled By:  ReplicaSet/conda-store-conda-store-8f8d9bfdc
Containers:
  conda-store:
    Container ID:  docker://b7b2d6f71eacfb896532c156ac3c16aa5100ca1dc864ec2b4d6b61a8bc681a67
    Image:         quansight/conda-store:e2051a36e60bd3abd9aa44105f240b359ee6bab7
    Image ID:      docker-pullable://quansight/conda-store@sha256:aef86261d549e8490a3d6ec22697c4243b7304408a78df0c0a2b9425ca2abf18
    Port:          <none>
    Host Port:     <none>
    Command:
      python
      /opt/conda-store/conda-store.py
      -e
      /opt/environments
      -o
      /home/conda/environments
      -s
      /home/conda/store
      --uid
      0
      --gid
      0
      --permissions
      775
    State:          Running
      Started:      Fri, 19 Mar 2021 07:15:07 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /home/conda from nfs-export-fast (rw)
      /opt/environments from conda-environments (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lrrqz (ro)
  nfs-server:
    Container ID:   docker://1410a1a65afce65237a8513cbb6ecfdafb33d9271d06e55857ba9aa64e623b13
    Image:          gcr.io/google_containers/volume-nfs:0.8
    Image ID:       docker-pullable://gcr.io/google_containers/volume-nfs@sha256:83ba87be13a6f74361601c8614527e186ca67f49091e2d0d4ae8a8da67c403ee
    Ports:          2049/TCP, 20048/TCP, 111/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 19 Mar 2021 07:15:14 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /exports from nfs-export-fast (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lrrqz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  nfs-export-fast:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  conda-store-conda-store-storage
    ReadOnly:   false
  conda-environments:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      conda-environments
    Optional:  false
  default-token-lrrqz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lrrqz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                                               Message
  ----     ------                  ----               ----                                               -------
  Normal   Scheduled               60m                default-scheduler                                  Successfully assigned dev/conda-store-conda-store-8f8d9bfdc-j7qkl to ip-10-10-0-39.us-west-2.compute.internal
  Warning  FailedAttachVolume      60m                attachdetach-controller                            Multi-Attach error for volume "pvc-23168dff-07c3-4823-a6f6-cbe7b1bac9e4" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             56m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Unable to attach or mount volumes: unmounted volumes=[nfs-export-fast], unattached volumes=[default-token-lrrqz conda-environments nfs-export-fast]: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  54m                attachdetach-controller                            AttachVolume.Attach succeeded for volume "pvc-23168dff-07c3-4823-a6f6-cbe7b1bac9e4"
  Warning  FailedMount             54m (x2 over 58m)  kubelet, ip-10-10-0-39.us-west-2.compute.internal  Unable to attach or mount volumes: unmounted volumes=[nfs-export-fast], unattached volumes=[conda-environments nfs-export-fast default-token-lrrqz]: timed out waiting for the condition
  Normal   Pulling                 52m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Pulling image "quansight/conda-store:e2051a36e60bd3abd9aa44105f240b359ee6bab7"
  Normal   Pulled                  52m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Successfully pulled image "quansight/conda-store:e2051a36e60bd3abd9aa44105f240b359ee6bab7"
  Normal   Created                 51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Created container conda-store
  Normal   Started                 51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Started container conda-store
  Normal   Pulling                 51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Pulling image "gcr.io/google_containers/volume-nfs:0.8"
  Normal   Pulled                  51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Successfully pulled image "gcr.io/google_containers/volume-nfs:0.8"
  Normal   Created                 51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Created container nfs-server
  Normal   Started                 51m                kubelet, ip-10-10-0-39.us-west-2.compute.internal  Started container nfs-server
```
