### ISSUE TITLE
Adding update_date to the deployed website

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#243]
## Description
I just redeployed. Its hard to see if my automated actions have taken effect and the new deployment is now live (since it was up and running previously in a very similar state). 

I imagine there are ways to follow the deploy more closely, but this would also allow the end user, who is not a dev and is not following deployment, to see when the feature they just requested may have been implemented. 

## Suggestion
I'd like to see some information like `updated MM/DD/YYYY HH:MM` somewhere on the deployment. 

We have other auto-deploy systems (`qadmin` internally) that trigger redeploy by gh versioning so we just put the version number in the title bar at the top of the page. That wouldn't work here, but we could use a timestamp to do something similar. 

## Context
This is a `nice to have` feature that would help in the early days with lots of development and also in a crunch time.

**Comment by laisbsc** [comment]
Alright. Thanks for your request!

I will bring this up with the team. Is it something you'd like to contribute to developing?
