### ISSUE TITLE
Documentation Infrastructure

### ISSUE THREAD

**Issue by anirrudh** [Quansight/qhub#25]
This issue tracks the progress of the Sphinx Documentation workflow from within the Documentation tab. 

There are some pending code changes that need to be investigated and redone.

[ ] dynamic documentation screen resizing
[ ] `collapsable-navbar` while scrolling? (unsure if needed) 
[ ]  proper rendering from markdown/rst/notebooks

**Comment by tylerpotts** [comment]
Moved to readthedocs
