### ISSUE TITLE
Comparison between qhub-cloud and qhub-onprem

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#260]
# Motivation:
See https://github.com/Quansight/qhub-cloud/discussions/259. Add documentation comparing QHub Cloud and QHub OnPrem to the docs.

## Acceptance criteria:
- [ ] Descriptive paragraph on the design goals of each product.
- [ ] Feature matrix (see discussion link above) with the specifics of each.

### Description paragraph (general idea):
At its core, the difference between qhub-onprem and qhub-cloud is its focus (cloud vs. on-prem) and job scheduler (kubernetes vs. slurm). There are distinct advantages to both especially with our overarching project goal of enabling scalable compute to smaller teams.

**Comment by laisbsc** [comment]
This ticket is currently blocked until we resolve the name change situation (#421).
