### ISSUE TITLE
permissions for sub-directories created in shared directory

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#268]
Shared directory should be RW for all, which is how the permissions are set.
However, directories created under shared default to RO.  This can cause difficulty when trying to collaborate with others.

**Comment by dharhas** [comment]
Actually, the correct permissions within a shared folder should be `rw` for the group the shared folder belongs to, `rw` for all would mean folks who don't have access to the folder would get access.

**Comment by dharhas** [comment]
This is an old SO post but does describe the behavior needed:

https://superuser.com/questions/277775/ensuring-new-files-in-a-directory-belong-to-the-group

**Comment by dharhas** [comment]
https://blog.superuser.com/2011/04/22/linux-permissions-demystified/

"SetGID, however, is a whole different ball game.  When a directory has the SetGID bit set and a file is created within that directory the group ownership of the file is automatically modified to be the group of the directory."

☝️ can we do this with the nfswrapper qhub is using?

**Comment by laisbsc** [comment]
Shall we add this to the technical discussion meeting tomorrow? @dharhas @tylerpotts @brl0

**Comment by laisbsc** [comment]
This will become easier to implement as soon as we have local testing is implemented.

**Comment by viniciusdc** [comment]
@tylerpotts @aktech could you point me where the nfs configs are? I've saw some of the groups permissions [here](https://github.com/Quansight/qhub-cloud/blob/7f7e8b43a3be46a40bae01c03d76bb3145119540/tests/assets/config_do_additional_node_groups.yaml#L35) and [here](https://github.com/Quansight/qhub-cloud/blob/7f7e8b43a3be46a40bae01c03d76bb3145119540/qhub/initialize.py#L28). I got the idea for the proposed changes using SetGID, but I'm not sure where should I put those changes...

**Comment by costrouc** [comment]
This needs to be modified https://github.com/Quansight/qhub-cloud/blob/f4c30f4f3c4f282cfe0d82a0d90dbeac01cf8e4c/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/templates/jupyterhub_config.py.j2#L91

**Comment by costrouc** [comment]
Reopening as there are still issues with the write permissions.

**Comment by costrouc** [comment]
Moving to 0.4 release since this issue is partially complete but will need more investigation

**Comment by tylerpotts** [comment]
@costrouc says this is fixed.

**Comment by viniciusdc** [comment]
Reopening as there are still issues with the group/users permissions

**Comment by sayantikabanik** [comment]
_I am fairly new to QHub, here are my observations_

- I started with creating a .ipynb file in the shared directory. Which resulted in a permission denied issue. 
- Later I tried opening an exiting file which threw a JSON exception (unreadable notebook)
- I used vscode initially to open and later switched to Jupyter notebook
- After a constant struggle I ended up restarting the QHub instance and was able to create a .ipynb file in my home (haven't tried in shared folder post restarting)

**Comment by viniciusdc** [comment]
Closed as Keycloak will now handle user management which will lesser the related file permissioning issues on QHub
