### ISSUE TITLE
Use JupyterSSH keys on QHub login

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#272]
> original ticket-query left at JupyterSSH by Chris.

## Motivation:
One issue we've seen with several clients is how they don't feel comfortable using password based auth and would prefer ssh keys. That being said, the password the user supplies is used to launch the jupyter server on behalf of the user allowing jupyterhub-ssh to not have a sensitive admin api key. 

## Implementation (initial thoughts):
Often times I find that it is needed to associate metadata (often times not secrets) with a given user in this case public keys. I know that jupyterhub has auth-state but external api's do not have access to this data. If the hub had data about a user that could be queried over an api jupyterhub-ssh would have an easy way to gather associated ssh-keys for a user. This may be a feature that is waiting on rbac permissioning in jupyterhub to be completed https://github.com/jupyterhub/jupyterhub/tree/rbac.

## Requirements:
We would need to associate N ssh public keys with a given username and it would likely require the jupyterhub-ssh server to have an admin api key.

**Comment by tylerpotts** [comment]
Related to #306

**Comment by rsignell-usgs** [comment]
@tylerpotts and @laisbsc, if I want to submit a long-running job today, what approach should I use?   
@costrouc helped me with a method that worked back in November, but I'm not sure that's still the way to go.

**Comment by costrouc** [comment]
@rsignell-usgs for now I would recommend https://github.com/quansight/jhub-client. It is already being used for several other jupyterhub clusters outside of qhub. We do have plans for adding jupyterhub-ssh

**Comment by viniciusdc** [comment]
@tylerpotts I think qhub tokens and jupyterhub-ssh solved this issue right?

**Comment by costrouc** [comment]
@viniciusdc this is refering not to jupyterhub tokens but ssh keys e.g. public/private keys.

Right now this is not an actionable issue. It depends on many other features that are blocking this implementation. Ultimately this is an issue that jupyterhub-ssh needs to solve. There is an open issue https://github.com/yuvipanda/jupyterhub-ssh/issues/25 to track this. Reopen if these features are implemented.
 - first jupyterhub-ssh needs to support ssh keys
 - next jupyterhub needs some way to store and server user public data
