### ISSUE TITLE
[enhancement] Rstudio?

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#273]
On some other Pangeo deployments, like the one for Ocean Hack Week, an Rstudio environment as enabled on the JuptyterHub (@ocefpaf, can you remind me where we have that documented)?

I'm wondering what it would it take to enable it on Qhub?

**Comment by abkfenris** [comment]
I added it to the image build in https://github.com/oceanhackweek/jupyter-image/pull/9 and I believe part of the key was a few packages in `environment.yml` to allow JupyterHub to identify Rstudio as an option:

- `jupyter-rsession-proxy`
- `nb_conda_kernels`

One issue that we found (but didn't play with a lot) was Rstudio wouldn't recognize other conda environments, and any libraries that users installed into the base environment wouldn't get persisted (like our user installed conda environments). This meant that all of of the R packages needed to also be baked into `environment.yml` or `postBuild`.

**Comment by dharhas** [comment]
I was just thinking about rstudio yesterday. https://2i2c.org has it integrated so we might be able to look at how they did it for ideas.

**Comment by ocefpaf** [comment]
Pretty much what @abkfenris, who did most of the work BTW. The only thing I have to add is that conda-forge may have a RStudio package soon. That would allow us to drop the binary install using apt. xref.: https://github.com/conda-forge/staged-recipes/pull/13760

**Comment by dharhas** [comment]
@costrouc is building out [conda-store](https://github.com/Quansight/conda-store) with funding from a client. Not sure that it helps in anyway here but it gives us a better user created conda environment story on kubernetes.

**Comment by rsignell-usgs** [comment]
@abkfenris , awesome, thanks for the info.    Our users can persist environments they create using [this approach](https://github.com/ESIPFed/esiphub-dev/issues/27), which works fine if they don't need those custom packages in Dask, which I guess the R users wouldn't!
