### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#276]
Currently, releases are manual. We could automate this with something like [rever](https://regro.github.io/rever-docs/) and github actions

**Comment by tylerpotts** [comment]
Needs further discussion, specifically to specify what problems this solves and the cost of implementing it.

**Comment by laisbsc** [comment]
I think @danlester was working on something related to this, no?

**Comment by danlester** [comment]
Yes, I think we have a more streamlined release process now, so let's let this issue close.

**Comment by danlester** [comment]
Oh except it won't be closed now because we've commented on it! (That makes it un-stale)
