### ISSUE TITLE
Add/Link CoC and inclusivity documents

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#277]
@trallard noticed that we don't have CoC/Inclusivity docs linked/added in the repos, it would be great to add them. Quoting Tania:

> - Add the Quansight CoC to the qhub repos or at least add a link to it. Having this visible is critical for our community health and safety.
> - Add an inclusivity doc (like the Kubeflow) to help with our community standards for the get go

**Comment by dharhas** [comment]
So the GitHub UI is only surfacing the CoC link in certain pages and not on the main page. We might want to consider adding a link explicitly in the Readme.

https://github.com/Quansight/qhub-cloud/community

**Comment by laisbsc** [comment]
FYI: There is a discussion happening on this [issue](https://github.com/Quansight/.github/issues/11#issuecomment-773313751) about the inclusivity document.
