### ISSUE TITLE
Auto create kube context for cloud deployments

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#291]
This ticket aims to offer an easier solution to monitor their logs on QHub Cloud

## Motivation
Often times users need to debug the cluster when things go wrong. This usually involves checking the Kubernetes logs which require setup of `kube config` and `context`.

## Proposed solution
We would like to initialize the users `kubeconfig` with the credentials to connect to the cluster.

**Comment by tylerpotts** [comment]
First step is to create debug docs. Automating this is a feature request

**Comment by costrouc** [comment]
This will require docs for each provider and will likely be hard to automate. 
 - for gcp https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#interacting-with-kubernetes
