### ISSUE TITLE
Schedule time with existing users to upgrade local testing

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#294]
Local testing in #135 will break current clusters. This change will prevent future breakages from happening.

@rsignell-usgs @jkellndorfer Giving you the heads up that this is coming in the next week or two. I'll create a PR on your QHub that will manage this transition when it's time to merge the changes.

**Comment by rsignell-usgs** [comment]
Sounds good @tylerpotts !     I'm wondering whether we are feeling changes already, as I tried adding a package to my env this morning and the github actions were successful, but no new package appears in my environment.     Is it possible that this package pushed my container size over some limit and there was a failure downstream of the github actions?

Where should I raise this?

**Comment by tylerpotts** [comment]
@rsignell-usgs sounds like either A) conda environment solve is failing, or B) your conda store is out of space. Solutions for those potential problems:

A) check the latest log file from a user instance in the `/home/conda/store/.logs` directory. Note that it can take a while (>30 mins) to build complex environments
B) Increase your storage space for conda store in `qhub-config.yaml`. 

Also, I believe that conda store doesn't currently garbage collect (will double check with @costrouc). If that's still the case, the shared NFS volume can fill up quickly with large environments. If you ssh into the pod, you can manually delete all the old environment builds to get more space. This will be a valid step if B) fixes the problem, and I'll write some docs for that if needed

**Comment by rsignell-usgs** [comment]
@tylerpotts , does this log from the conda store pod give any clues?
![2021-02-03_15-43-26](https://user-images.githubusercontent.com/1872600/106807059-b112d280-6636-11eb-89fa-6e328b260931.png)

**Comment by rsignell-usgs** [comment]
> If you ssh into the pod, you can manually delete all the old environment builds to get more space.

Is there an example or doc on how to do that?

**Comment by jkellndorfer** [comment]
that's right, @rsignell-usgs . Essentially started over.

**Comment by viniciusdc** [comment]
I'm removing the `stale` tag as this issue raises a good faq to handle conda-store common environment errors.

**Comment by tylerpotts** [comment]
@viniciusdc The original purpose of this issue is now complete. We were able to help get the USGS cluster destroyed. If you create a new detailing what you mean about conda-store environment errors and permission restrictions we can take it from there.
