### ISSUE TITLE
Agree on a release strategy

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#296]
## Motivation:

- Currently, upgrading QHub can/will break existing QHub instances (versions) in the wild
- Existing QHubs pull from the `main/master` branches (undesired behaviour)
- Release/staging branches (ref. #295)

## Item to discuss:
- Pin releases to either a GitHub hash or a release?
- Which branch should have changes be pushed to?
- What is the standard procedure to develop on QHub?

**Comment by laisbsc** [comment]
The team had a long discussion after the standup on Feb 3rd and agreed on:
1. create a document detailing how to contribute to QHub's development (Standard workflow practices)

## Decided for now
We will have a `dev` branch that will stack all merged changes. Upon release, those changes will be pushed to a `release` branch, where they will be further tested and finally pushed to the `main` one. Hence, the `main` branch will always keep a stable version of QHub (where PyPI will be linked to).

More details on the procedures can be found on the [linked draft](https://hackmd.io/dQIaLz6USkm0mMw5T1uyfg).

Needs work so feel free to pump it and let me know what you think @aktech @tylerpotts @costrouc.

**Comment by dharhas** [comment]
We currently basically use github flow - https://githubflow.github.io/

The advantage of this is that it is very simple conceptually and to follow but has the disadvantage that it assumes everyone will always deploy master and be able to be on the most updated version. This is a bit problematic when we expect to have many production deployments outside Quansight. Essentially, it is ideal when you need to maintain single version in production.

git-flow (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Git-flow is a well established process but in practice I find it overly complex and difficult to explain to folks and to follow correctly. It also doesn't work well with the github pr model.

What we really need is something that lightweight similar to github flow but allows us to maintain multiple versions.

OR stay with github-flow and have a pretty solid upgrade path from previous versions <- I'm leaning towards this.
