### ISSUE TITLE
[documentation] - 101 Qhub

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#301]
## Idea
As we are working on our docs it would be good to have a 101 on QHub Cloud. For inspiration check out the [SpaCy 101](https://spacy.io/usage/spacy-101).
## Action
Have a dedicated webpage to QHub Cloud 101 on the docs heading.

**Comment by laisbsc** [comment]
It looks very cool! I think this will be an awesome addition to the docs as soon as we have QHub to be a bit more stable. There are some architectural changes coming up that require rework on thse. 

With that in mind, I will add this to our list of [community ideas](https://github.com/Quansight/qhub-cloud/projects/2) for future docs.

Thanks a million, @trallard 🚀
