### ISSUE TITLE
Separate apply operations

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#305]
According to the [docs](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) for the latest Terraform Kubernetes provider:
> The most reliable way to configure the Kubernetes provider is to ensure that the cluster itself and the Kubernetes provider resources can be managed with separate apply operations. Data-sources can be used to convey values between the two stages as needed.

Based on this, it may be desirable to separate the Terraform modules such that one apply operation is run to spin up the cluster, and a second apply operation is run to deploy the resources.

Incidentally, it seems that this separation may be desirable anyway because it would make it simpler to possibly have qhub spin up cluster resources through means other than Terraform, such as Minikube or Vagrant.

@costrouc, @tylerpotts, @aktech, what do you guys think?  I would be happy to jump in on a sprint to help.

**Comment by tylerpotts** [comment]
@brl0 Chris has a PR for local testing #287 that should get you the functionality you are looking for. We're currently testing the local testing and will merge it soon
