### ISSUE TITLE
linuxbrew store [enhancement]

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#310]
Conda-store provides a great solution for serving environments to jupyterlab instances.
Linuxbrew is a user level package manager that stores files in `/home/linuxbrew`.
I was thinking it would be useful to be able to serve up Linuxbrew packages centrally similar to conda-store.  
I am not sure if something like this could be integrated directly into conda-store, or if a separate tool should be created for this.

Any thoughts, ideas, or suggestions would be appreciated.

**Comment by brl0** [comment]
Since HomeBrew includes many development and build tools, I think this could potentially tie in with building or compiling on qhub as mentioned in #551.

Feel free to close if this is not likely to be added to the roadmap for the foreseeable future.

**Comment by viniciusdc** [comment]
@costrouc Any thoughts on this?
