### ISSUE TITLE
Documentation for Azure

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#316]
Blocker before merging https://github.com/Quansight/qhub-cloud/pull/314/files

- Mention dask gateway limitations

**Comment by Adam-D-Lewis** [comment]
@laisbsc I added the documentation to https://github.com/Quansight/qhub-cloud/blob/azure/docs/docs/step-by-step-walkthrough.md

**Comment by tylerpotts** [comment]
- [ ] Needs documentation about dask timeout limitation azure
- [ ] Create an issue to fix the dask timeout limitation on azure

**Comment by Adam-D-Lewis** [comment]
The step by step guide for azure was merged prior to the v0.3 release.  The dedicated guide for azure is not released yet, and is scheduled for v0.4.
