### ISSUE TITLE
Updating stuff

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#320]
@costrouc, @tylerpotts, @dharhas,

I have created several PRs to update stuff.
- Upgrade Dask-Gateway to v0.9.0: #315 and [qhub-terraform-modules-37](https://github.com/Quansight/qhub-terraform-modules/pull/37)
- Upgrade Jupyterhub to v0.11.1: #318 and [qhub-terraform-modules-38](https://github.com/Quansight/qhub-terraform-modules/pull/38)
- Update Docker images to Ubuntu 20.04, Jupyterlab 3, other minor changes: #319

Each PR was tested individually, also the PRs were merged and tested together.  Testing was performed via Kubernetes in Docker (kind).

Notes for upgrading existing clusters:
Existing qhub config files need to be updated to appropriate image tags and dask versions.
Terraform initially failed to update the helm charts in place, however to successfully upgrade a previously deployed cluster I simply had to uninstall the existing helm charts and then Terraform was able to deploy the new versions successfully.

The most pressing pain point I am trying to solve is being stuck on an old version of Dask.

What needs to happen from here to get these PRs reviewed and merged?  I would like to keep this moving forward and am happy to assist however I can.

**Comment by tylerpotts** [comment]
@brl0 Thanks for the PRs!

@aktech Has some time over the next few days, and will be focused on merging #287 and then figuring out the dask gateway story.

With dask gateway, @costrouc has mentioned a few times that removing helm was a pre-requisite. It looks like you may have found a workaround, but I want to double with Chris before making any architectural decisions. I've created #322 to track that.

As for #319, I'll bring this up in our Tuesday internal sync. Upgrading to Jupyterhub 3, in particular, could potentially break things and I'd like to get some more input before making that step.

Thanks again! I'll get back to you here when I have more information

**Comment by brl0** [comment]
@tylerpotts,

Thanks for the response and the update, I really appreciate it.

> Upgrading to Jupyterhub 3, in particular, could potentially break things
Based on my testing Jupyterlab 3 seems to work without issue even with the version of Jupyterhub (0.9.0-beta.3) currently in use by qhub.  That particular PR (#319) is a stand alone and can be considered separately from any of the other PRs I have submitted.

> I'd like to get some more input before making that step.
Understood, no problem.

**Comment by brl0** [comment]
Most of the updates have been completed or are irrelevant, closing.
