### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#336]

**Comment by laisbsc** [comment]
The label `stale` has been removed since this issue is an epic for documentation issues (needed for ZenHub).

**Comment by danlester** [comment]
@laisbsc Well spotted. There is probably a way we can remove certain labels from this 'stale' bot.

Details here: https://github.com/actions/stale

And our workflow file that sets off the bot is here: https://github.com/Quansight/qhub/blob/main/.github/workflows/stale_bot.yml

Anyway, if you have more 'exceptions' or other rules to set like this (exclude 'Epic' issues) then please make a list and we can update the bot.

**Comment by viniciusdc** [comment]
> @laisbsc Well spotted. There is probably a way we can remove certain labels from this 'stale' bot.
> 
> Details here: https://github.com/actions/stale
> 
> And our workflow file that sets off the bot is here: https://github.com/Quansight/qhub/blob/main/.github/workflows/stale_bot.yml
> 
> Anyway, if you have more 'exceptions' or other rules to set like this (exclude 'Epic' issues) then please make a list and we can update the bot.

@costrouc  I think that maintaining the epic label for that might be useful in the end, we could use [`exempt-issue-labels`](https://github.com/actions/stale#exempt-issue-labels) rule for the stale bot then
