### ISSUE TITLE
Strategy for credential's storage

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#37]
Currently github secrets are used for storing aws, gcp, and do credentials. Ideally we move away from this approach since it does not scale. Alternative approaches:

 - [git crypt](https://github.com/AGWA/git-crypt)
 - [sops](https://github.com/mozilla/sops)

Requirements:
  - simple to use (yeah... I know creating gpg keys is not "simple")
  - well adopted tool
  - works with teams

**Comment by viniciusdc** [comment]
@costrouc Was there any updates on this so far?

**Comment by brl0** [comment]
[Hashicorp Vault](https://www.vaultproject.io/) seems like it may be a good consideration.

**Comment by leej3** [comment]
As keycloak starts being used by more deployments, it seems appropriate to consider exploring Vault or some other mechanism to more securely manage credentials. I know @viniciusdc is looking into this.

**Comment by iameskild** [comment]
Superseded by #787
