### ISSUE TITLE
Adding Azure Support

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#371]

**Comment by aktech** [comment]
Can this be closed, as we have merged the following: https://github.com/Quansight/qhub/pull/314, https://github.com/Quansight/qhub/pull/453,  https://github.com/Quansight/qhub/pull/483 ?

**Comment by viniciusdc** [comment]
@aktech @costrouc @tylerpotts, may we close this one?

**Comment by tylerpotts** [comment]
yep
