### ISSUE TITLE
Comment on PR upon change to qhub-config.yaml in github-actions

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#379]
The current linter is run with

https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows/qhub-ops.yaml

Also validation is always run on the qhub-config.yaml even when the validate command is not directly called.

Add validation to 

 - github-actions have the following information https://docs.github.com/en/actions/reference/environment-variables

You'll have GITHUB_TOKEN set which you can use for api requests.

You can find the pull request number

https://github.com/actions/checkout/issues/58#issuecomment-545446510

Submit a comment via

This looks usefull https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request

**Comment by brl0** [comment]
I think comments can also be made using the `gh` cli as shown [here](https://cli.github.com/manual/gh_pr_comment).  It looks like it uses the same `GITHUB_TOKEN` environment variable looking [here](https://cli.github.com/manual/gh_help_environment), and it seems the tool is pre-installed according to [this](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md).

**Comment by viniciusdc** [comment]
woaa, thanks @brl0 for those links. This is exactly what I was looking for!

**Comment by laisbsc** [comment]
Is it relevant to link PR #119 to this issue?

**Comment by viniciusdc** [comment]
We will add a new step into our workflow (qhub-cloud) to execute a `linter.py` (which then would be able to validate the configuration) to post any necessary comments into the PR. This will also allow us to create more features to the linter and give it more independence from GitHub, in the case we use it with GitLab.

Using the `linter.py` will enable us to get more information about linter capabilities.

**Comment by viniciusdc** [comment]
QHub linter #408
