### ISSUE TITLE
Investigate use of Pulumi

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#38]
Pulumi looks like a much nicer approach and will significantly lower the learning curve while allowing much more powerful development with python. It will take discipline to keep the deployments simple since python allows a lot of abstraction. But overall this is a much saner approach. It checks all my boxes.

    CI integration (github actions, azure, gitlab,etc)
    has way to view changes after application
    allows us to develop our own cli for deployment
    supports all cloud providers and uses terraform providers for anything that they do not specifically support
    community looks healthier
    supports crds in kubernetes which terraform is lacking and would allow us to move away from helm

**Comment by tylerpotts** [comment]
Will use terraform CDK directly

**Comment by tylerpotts** [comment]
https://www.hashicorp.com/blog/cdk-for-terraform-enabling-python-and-typescript-support
