### ISSUE TITLE
[documentation] Add `kubectl logs` suggestion to troubleshooting section

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#380]
Add the user question below to the documentation (discussion #378).
Suggestion should be added to the [troubleshooting section](https://github.com/Quansight/qhub-cloud/blob/dev/docs/source/02_get_started/06_troubleshooting.md#general-troubleshooting).

## Story
When QHub returns an error related to failed clusters, such as  `GatewayClusterError: Cluster '<clusterID>' failed to start, see logs for more information`.

Suggest the user to use the command `kubectl logs` to check those logs.
> IDEA: this could be added to the QHub's CLI.

If that fails, try running one of the commands below:
```
kubectl scale --replicas=0 deployment gateway-dask-gateway -n dev
kubectl scale --replicas=1 deployment gateway-dask-gateway -n dev
```
Or check the `.dask` repository to find those logs.

**Comment by laisbsc** [comment]
Waiting for the technical team to find out how to sort this one out to add the instruction to the docs.

- This ticket might be a duplicate of #255. Investigate!
- This could also involve the requirements described on #374.

**Comment by tylerpotts** [comment]
@laisbsc This is separate from #255 and #374

The above commands are specific to "restarting" the dask-gateway pod. It's telling the dask-gateway pod to spin down to 0 replicas and then spin back up to the default 1.

Ideally, we should never have to do this, and we'll have to see if upgrading to dask_gateway v0.9 will make this troubleshooting step outdated

**Comment by tylerpotts** [comment]
This is a problem that may be fixed by the switch to traeffilk and upgrading to dask_gateway 0.9. 

I suggest holding off until users have test the above and still report this problem

**Comment by laisbsc** [comment]
@tylerpotts Do we know if this is still an issue? Are we happy to close?

**Comment by viniciusdc** [comment]
@tylerpotts We are now using `dask-gateway` with the v0.9, may we create another issue task to test if this is still a problem?
