### ISSUE TITLE
Monitoring of cluster stats via grafana and prometheus

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#39]

**Comment by laisbsc** [comment]
According to @costrouc : this is a fun issue!

It is useful for demos, a cool to have. Not sure when the team will be able to implement it.

**Comment by costrouc** [comment]
# Acceptance Criteria:
  - grafana and prometheus deployment in Qhub
  - pre made dashboards in grafana for viewing:
      -  jupyterhub health
      -  kuberenetes pods
      - traefik health and traffic

**Comment by Adam-D-Lewis** [comment]
I'll try to work on this if no one else is planning on working on it at the moment.

**Comment by Adam-D-Lewis** [comment]
I'll probably add these via helm charts similarly to ClearML.
- https://github.com/grafana/helm-charts
- https://github.com/prometheus-community/helm-charts

**Comment by costrouc** [comment]
@Adam-D-Lewis this would be really useful for the 0.4 release and would be awesome if you worked on it. We've needed this feature for awhile!

**Comment by Adam-D-Lewis** [comment]
To update my progress, I was able to deploy the grafana helm chart manually via `helm install ...`, but I'm still working on setting up some traefik routes to access grafana.

**Comment by Adam-D-Lewis** [comment]
To provide further updates, with Chris's help I was able to access grafana at `grafana.myqhub.qhub.dev`, but was not able to access grafana at `myqhub.qhub.dev/monitoring/`.  Also, in consultation with Chris, he advised me we could either strip the /monitoring prefix with a middleware or we can let grafana know its baseUrl similar to how it's done at https://github.com/Quansight/qhub-hpc/blob/main/templates/grafana.ini.j2#L54.  The preference is on doing the latter which needs more discussion.

**Comment by brl0** [comment]
Hey @Adam-D-Lewis, hope all is well.  :)

I am definitely +1 on this idea and am looking forward to trying it out.

I don't know if this is particularly helpful, but I thought it was an interesting project and at least tangentially related: https://github.com/yuvipanda/jupyterhub-grafana
> This project provides some standard Grafana Dashboards as Code

**Comment by brl0** [comment]
Incidentally, it looks like the project I mentioned above just got moved to the jupyterhub organization:
https://github.com/jupyterhub/grafana-dashboards

**Comment by costrouc** [comment]
@brl0 yeup we saw that and certainly want to use that! We'll also be tying in additional stats from other services e.g. traefic

**Comment by Adam-D-Lewis** [comment]
Thanks for the references @brl0, hoping we can tie those in eventually, but I'm still working through proxy routing issues at the moment.

**Comment by Adam-D-Lewis** [comment]
>To provide further updates, with Chris's help I was able to access grafana at grafana.myqhub.qhub.dev, but was not able to access grafana at myqhub.qhub.dev/monitoring/. Also, in consultation with Chris, he advised me we could either strip the /monitoring prefix with a middleware or we can let grafana know its baseUrl similar to how it's done at https://github.com/Quansight/qhub-hpc/blob/main/templates/grafana.ini.j2#L54. The preference is on doing the latter which needs more research on my end to see if the helm chart exposes the grafana.ini somehow.

I've been trying to specify the baseUrl in the grafana config, but I'm getting an infinite loop of redirects rather than the grafana login page being loaded.  I'm continuing to work on this.

**Comment by brl0** [comment]
Another resource that may or may not be helpful... I stumbled across [NeuroHackademy's JupyterHub](https://github.com/neurohackademy/nh2021-jupyterhub) which deploys prometheus and grafana via helm dependencies.

**Comment by Adam-D-Lewis** [comment]
I still am hitting the infinite loop of redirects mentioned in my last comment.  I want to try out using traefik ingress instead of traefik ingressroute and see if that helps.  If not, I may need to just open an issue on grafana's repo and then use the subdomain approach (monitoring.myqhub.qhub.dev) to access grafana instead of prefix paths (myqhub.qhub.dev/monitoring).

**Comment by Adam-D-Lewis** [comment]
Finally got past the infinite loop of redirects.  I had to add a middleware to strip the path prefix, and then it worked.
