### ISSUE TITLE
[enhancement] Only have a single line in the qhub-config.yaml for the url

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#392]
## Description
Having two lines for the the cluster url creates confusion, and has lead to wasted debugging time

## Suggestion
Have a single key in the yaml for the cluster url

## Context
See bullet 4 in https://github.com/Quansight/qhub-cloud/discussions/390

**Comment by danlester** [comment]
I think this is one of Dharhas' pet issues! Also covered in #589

**Comment by viniciusdc** [comment]
Hi @tylerpotts, could you point to the related files with those url's in the issue description?
