### ISSUE TITLE
[enhancement] track conda-lock files

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#398]
## Description
We would like to be able to return to a previous working environment that we might have deleted from the conda-store 

## Suggestion
Commit changes to env in config as usual, but then call a bot to create the conda-lock (this happens already, right?) and commit the locked changes.   The first is for humans, the second is for machine provenance

**Comment by tylerpotts** [comment]
@rsignell-usgs This will be fully fixed when we are able to integrate the new conda-store that @costrouc built. Each environment in the new conda store gets a version number, so it would be trivial to go back to a working version.

The new conda store is currently on the roadmap for the release after `v0.3` (which will update dask_gateway! :tada:)

We're clarifying which issues should be included in `0.3` tomorrow as well as a timeline. I'll post in the gitter channel when we have that

**Comment by viniciusdc** [comment]
Hi @rsignell-usgs, we are working to implement this feature for the next release of [conda-store](https://github.com/Quansight/conda-store)
