### ISSUE TITLE
Use jupyterhub as a single sign-on authentication provider

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#40]
This would allow easy securing of domains served within kubernetes cluster

**Comment by laisbsc** [comment]
Chris would like to tie this to [traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth).

After tech-discussion meeting, this issue was elected as low-priority and related to #267.

**Comment by costrouc** [comment]
@danlester implemented `traefik-forward-auth`. This may solve this issue and we need to look into if this solved the problem.

**Comment by viniciusdc** [comment]
@costrouc @danlester was that solved? If not what could be the best way to verify?

**Comment by costrouc** [comment]
Completed via https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/forwardauth
