### ISSUE TITLE
QHub CI/CD and repository initialization on gitlab

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#406]
This is an issue to bring support for gitlab on QHub.
 - involves setting up gitlab ci runner https://docs.gitlab.com/ee/ci/yaml/:
    - add `.gitlab-ci.yaml` to https://github.com/Quansight/qhub-cloud/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D
    - modify https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/hooks/post_gen_project.py based on if github ci or gitlab ci for certain files to be available
 - Add a similar gitlab auto provision for qhub see for reference https://github.com/Quansight/qhub-cloud/blob/7f7e8b43a3be46a40bae01c03d76bb3145119540/qhub/initialize.py#L280
 - implement https://github.com/Quansight/qhub-cloud/tree/main/qhub/provider/cicd gitlab module for actions to initialize secrets for gitlab actions

**Comment by viniciusdc** [comment]
@costrouc what are the nexts steps for `qhub_auto_provision` function, just need to know if we are able to manage the `secrets` and `keys` for this right now? or is there something I should take care of before that?

**Comment by viniciusdc** [comment]
I almost finished the integration with Gitlab CI, we need to test the cloud deployment for DO and Azure to check if there aren't any errors in there. Also there seems to be an issue with Terraform during the deployment process: 
```python
Error: JSON credentials in "}" are not valid: invalid character '}' looking for beginning of value
```
Whcik then leads to:
```python
Error: Initialization required. Please see the error message above.
```
Also, Gitlab `CI_JOB_TOKEN` don't have write permissions for the project, which then leads to the runner incapacity of pushing the bot commit, a possible solution for this is generating a personal token for the user/client with write permissions.
