### ISSUE TITLE
Pin Docker image tags

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#428]
Once all PRs are merged into dev, Docker images will be built automatically.
Those tags need to be entered into the `qhub init` [default images here](https://github.com/Quansight/qhub-cloud/blob/d45f4c6168742367cd34538599a0fed14f783ceb/qhub/initialize.py#L32).

Although a Docker image should have been built already for the PRs individually, there may be additional packages that need to be brought in from other PRs, so this has to be done at the end.

I will also create another issue to try to do something better in the future.

**Comment by costrouc** [comment]
Resolving since the docker images for the deployment have been built and tested.
