### ISSUE TITLE
Use only a single resource group for azure in qhub-cloud

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#430]
currently a qhub deployment on azure creates ~4 differerent resource groups (1 for terraform state, 1 for nodes, 1 for kubernetes master, and another one I think).  

I think these should all just be in a single resource group for now

**Comment by costrouc** [comment]
Yes completely agree. This will make the resources much easier to find. See the example of this being done for aws.

 - https://github.com/Quansight/qhub-terraform-modules/tree/dev/modules/aws/accounting
 - https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/aws.tf#L6

Also thanks for putting this in the 0.4 milestone already

**Comment by Adam-D-Lewis** [comment]
I cleaned up most of the resource-groups, but I think `node-resource-group` is still being used.

**Comment by Adam-D-Lewis** [comment]
Okay, so the best we can do for the Azure deployment is 2 resource groups.  Terraform's Azure provider documentation (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) says "Azure requires that a new, non-existent Resource Group is used, as otherwise the provisioning of the Kubernetes Service will fail."

I did rename the resource groups to have similar names to each other at least in `node_group` branch.
