### ISSUE TITLE
Sane curated default environment, jupyterlab extensions, and theme for QHub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#45]
Files to change.
  - `qhub_ops/template/{{ cookiecutter.project_name }}/image/jupyterlab/*`

- [ ] Add a README.md to directory with design goals and why etc.

Steps: rinse and repeat

1. cd into the `qhub_ops/template/{{ cookiecutter.project_name }}/image/jupyterlab/` directory
2. build: `docker build -f Dockerfile.jupyterlab . -t qhub-jupyterlab:lastest`
3. `docker run -p 8000:8000 -it qhub-jupyterlab:latest jupyter lab --ip 0.0.0.0 --port 8000`

Other method once you have an image you like we can try it out on the running jupyterhub/qhub cluster at `https://jupyter.do.qhub.dev/`

4. commit the changes to `qhub_ops/template/{{ cookiecutter.project_name }}/image/jupyterlab/`
5. wait for ci/github actions to finish building the docker images (~10 minutes)
6. take the tag of the docker images built or use the git commit sha (they are the same) from step 4
7. use the tag to update https://github.com/Quansight/qhub-ops/blob/master/qhub_ops/template/%7B%7B%20cookiecutter.project_name%20%7D%7D/infrastructure/variables.tf#L61-L85 tags
8. commit those changes to the three tags and wait 10 minutes for it to be deployed on https://jupyter.do.qhub.dev

**Comment by prasunanand** [comment]
Need to add a section for `jupyterlab` extensions in `qhub-ops-config.yaml`

**Comment by tylerpotts** [comment]
Will have users create an issue if they need additional default extensions. Current default extensions seem sufficient
