### ISSUE TITLE
Allow dashboards to served on public URLs

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#457]
It is desirable that the new QHub dashboards allow the user to share them in 2 ways:
1. In a pubic URL without the need for login, as a panel app for example. The aim is to allow users who don't have access to JupyterHub to access the dashboards easily from a URL.
2. Privately but with reduced permissions. The goal here would be to allow users to visualise the boards but have no access to JupyterHub for example.

@dharhas just collecting the thoughts from the brief convo we had at the meeting today. Feel free to edit/rewrite this ticket as wished :)

**Comment by danlester** [comment]
Number 2 makes a lot of sense, where other members of the same 'single sign on' directory may be non-technical users internally who wouldn't want or be allowed to start their own Jupyter servers or dashboards. There are some features of ContainDS Dashboards already that can be brought into QHub.

Number 1 (public) would be technically possible and fairly easy, but I'm not sure it's advisable. If the dashboard is to be shared with the general public, JupyterHub may not be the best way to do it. The URL will be via /user/dan/dash-panelapp or similar, and serving from a user's workspace - so the user would need to be careful not to change files inadvertently. The resource configurations (memory etc) suitable for JupyterLab or a dashboard with a contained set of users is unlikely to be the right size or setup for a public deployment of an app (lacking any load balancing or scalability).

Please could you explain more about the use case? Is it (a) a long-term app deployment that will be shared on Twitter and linked from their website, and should be carefully source controlled, or (b) basically the same as the number 2 colleague/client sharing idea except it's not sensitive and some of the people who need to access it aren't in the single-sign-on directory, and it's probably easier to send a public link than to add them to SSO.

**Comment by tylerpotts** [comment]
This still needs active discussion
