### ISSUE TITLE
Monitor PR on dask-gateway to make traefik ingress resource overridable

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#474]
Wanted to list the current blockers for the 0.3 release now that we have resolved the traefik issues. In the process of resolving the traefik issue the dask-gateway helm chart was replaced by traefik.

Missing features:
  - [ ] dask dashboards not showing up due to needing to add a `tls: {"certResolver": "default"}` to the traefik `IngressRoute` that dask-gateway auto creates. Need to create an issue and PR to resolve this issue https://github.com/dask/dask-gateway/blob/7d1659db8b2122d1a861ea820a459fd045fc3f02/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1241-L1268.
  - [x] when launching dask-gateway clusters the `cluster.get_client()` call fails along with getting the current state of the workers. This is due to not being able to make the tls connection. Need to find the correct way to hook this up (should not be much work just not sure the changes required).
  - [x] need to respect current dask profiles in `qhub-config.yaml` section and respect the default node-pool that workers get launched in.

**Comment by costrouc** [comment]
Going to create an issue specifically about the first bullet point since this cannot be done before the 0.3 release and we can note the workaroun.

**Comment by dharhas** [comment]
@costrouc can you make an issue so we can tag someone to work on the necessary PR to dask-gateway

**Comment by costrouc** [comment]
Link to opened PR https://github.com/dask/dask-gateway/issues/389.

@dharhas in our meeting today I proposed that @aktech work on this since you were looking to get him more involved with dask-gateway. I think this is a reasonable PR to get started on as well.

**Comment by brl0** [comment]
The PR in dask-gateway is still open, this issue should probably be kept open for tracking.

**Comment by viniciusdc** [comment]
@costrouc
