### ISSUE TITLE
Jupyterlab env solve takes too long [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#478]
## Describe the bug
The jupyterlab solve is currently causing the CI to time out because the environment solve takes approximately 1 hour.

## How can we help?

I have discussed this briefly with @viniciusdc as this is making #406 harder to work on. @viniciusdc please post any progress on this.

Some ideas we had on this:
+ Some hackiness could potentially allow us to use docker layer caching so that the solve only happens when environment.yaml changes. I'm not sure whether that is desirable because the image that is built is deployed. Perhaps layer caching could be disabled for deployment though? We could deploy only upon releases and the tests would be substantially faster.
+ There are some suggestions [here](https://www.anaconda.com/blog/understanding-and-improving-condas-performance) for speeding up the solve... possible candidates are `conda config --set channel_priority strict` and more exact version pinning. i don't think there's anything there to get this into the range of a reasonable solve time.
+ Another solution might be to use a conda lock file. This could be updated as required from a local solve using the environment.yaml so CI doesn't have to suffer its way through a solve each time it is triggered.
+ Use mamba... I don't know whether a mamba solve is deterministic... it would have to be to be useful for CI testing. My understanding is that it is not an optimal solve though.... which may be something we want... certainly when deploying.

**Comment by leej3** [comment]
I chatted with @costrouc about this. There is currently a PR to reduce the frequency of this build but agreed that the conda lock file would be a nice way to drop the time of the build. So someone would rebuild from environement.yaml, and update the lock file which would result in a much faster solve on CI.

**Comment by viniciusdc** [comment]
> I chatted with @costrouc about this. There is currently a PR to reduce the frequency of this build but agreed that the conda lock file would be a nice way to drop the time of the build. So someone would rebuild from environement.yaml, and update the lock file which would result in a much faster solve on CI.

I agree with that idea too, so are we going to create the necessary env with `conda-lock` and use that directly (for all the necessary dependencies) or are we removing some packages from the env list to maintain their upgradability?

**Comment by viniciusdc** [comment]
@costrouc if it's just to create a conda-lock file and test it with the Jupyterhub docker image, I might be able to test it this afternoon.

**Comment by leej3** [comment]
I'll sort this out... once the environment actually solves on my laptop :)  the lock file will fully specify the environment. Updates will be to the environment.yaml... which will then be used to create a new environment and lock file that can be used by CI. It means there is no solve on the CI so things should run more smoothly.
