### ISSUE TITLE
Conda-store storage pvc/pv gets stuck when upgrading

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#481]
Longstanding issue with conda-store deployment/pv/pvcs and how they do not upgrade smoothly

**Comment by viniciusdc** [comment]
HI @costrouc do we have more information or PR's associated with this? I've noticed some issues with deploying environments to Qhub  and conda-store being unable to update them in the jupyterlab hub.

**Comment by viniciusdc** [comment]
This might be solved with the next releases of conda-store, I'm right @costrouc ?
