### ISSUE TITLE
auth0 subdomain - better docs or validation

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#484]
In my qhub-config.yaml I entered:

```
security:
  authentication:
    auth0_subdomain: dev-5xltvsfy.eu.auth0.com
```

I wasn't sure whether the subdomain needed the full URL or not. It turns out not. This should be:
```
    auth0_subdomain: dev-5xltvsfy.eu
```

This could be clearer in the docs (of course, it is set automatically when autoprovisioned).

And/or it could accept the full domain anyway, or produce a validation error.

**Comment by costrouc** [comment]
Yeah completely agree that it would be useful to have better docs on this. Right now they lack any description on what the subdomain is https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html#auth0-based-authentication.

**Comment by danlester** [comment]
By the way, as you were discussing on the call, I would have just updated the docs myself at the time but knew they were in a state of flux!

Validation could also be useful on client_id and secret - it is possible to let "PLACEHOLDER" all the way through without really noticing until you can't log in.
