### ISSUE TITLE
[bug] URL inconsistency on QHub - return 404

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub#485]
## Describe the bug
On the deployed QHub (webpage) clicking on `Dashboard` and then trying to access anything else on the navbar, returns a 404.

## How can we help?
I think I've spotted the error (although, I have no idea how to fix it). When I click on anything after accessing the `Dashboards` tab, the URL automatically changes removing the `/hub` part of it. I think that is what is causing the issue.

I tried to illustrate the issue more precisely on the .gif below.

https://user-images.githubusercontent.com/42092770/114626458-a8302400-9cab-11eb-9c61-ff6c5bcb87d2.mp4

> NOTE: The way I found to workaround is to click on the QS logo, which seems to reset the URL paths to the working one.

**Comment by costrouc** [comment]
I see this as well.  I only see the prefix being messed up on the dashboard page when I was testing. @danlester any ideas on why this might be happening?

**Comment by viniciusdc** [comment]
I know that this might be a hack solution but what about adding `../hub/..` for the refs here https://github.com/Quansight/qhub-jupyterhub-theme/blob/master/qhub_jupyterhub_theme/templates/page.html @danlester ?

**Comment by danlester** [comment]
I think JupyterHub has changed the way these URLs work... and/or possibly dropped a redirect that was happening (maybe /token -> /hub/token etc) in the past. Not sure if this depends on the precise config of the installation (and JH version, maybe Traefik does things differently to CHP).

I will do some work to investigate. Hopefully using {{base_url}}/hub/home etc will be fine for all installations.

**Comment by danlester** [comment]
I have made these URLs more consistent with JupyterHub in cdsdashboards 0.5.6, and this is the version now referenced in the environment.yaml files in qhub main (but not changed to reference a relevant Docker image yet).
