### ISSUE TITLE
[bug] qhub-ops WF changes CI scripts to peg to master instead of main

### ISSUE THREAD

**Issue by sahil1105** [Quansight/qhub#493]
## Describe the bug
A clear and concise description of what the problem is.

The primary branch on my QHub deployment repo was `main`. To make the CI scripts work, I changed the CI scripts to run when changes were made to `main` instead of to `master`. However, whenever the `qhub-ops` workflow runs, it seems to change the CI scripts back to `master`.

## How can we help?
Help us help you.
* What are you trying to achieve?
* How can we reproduce the problem?
  Edit the CI scripts to use `main` instead of `master` and then trigger the `qhub-ops` WF.
* What is the expected behaviour?
   It shouldn't change `main` to `master`.
* And what is currently happening?
  It is changing `main` to `master`
* Any error messages?
   No
> If helpful, please add any screenshots and relevant links to the description.

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

N/A

**Comment by dharhas** [comment]
Additional info from @sahil1105 obtained by dm:

> It’s probably because [this function](https://github.com/Quansight/qhub/blob/cb6b2c7c6eefa5bd53b282f78d6bff2e3f2882bb/qhub/render/__init__.py#L77) which is called [here](https://github.com/Quansight/qhub/blob/cb6b2c7c6eefa5bd53b282f78d6bff2e3f2882bb/qhub/cli/render.py#L29) (which is called by qhub render -c qhub-config.yaml in the qhub_ops WF), uses the templates [here](https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows), which all use master

**Comment by costrouc** [comment]
Ah this is from the GitHub transition from `master` -> `main` for the default branch.
