### ISSUE TITLE
Create documentation for backing up cluster manually

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#506]
At least for AWS, a pod with root rights mounted to the shared directories has to be created for this to work:
https://gist.github.com/costrouc/09dab085badd5ab1bc7b62ec8dee4575

**Comment by costrouc** [comment]
@tylerpotts created a PR to address this issue. Docs here https://docs.qhub.dev/en/latest/source/04_how_to_guides/5_system_backup.html?highlight=backup#backups

**Comment by brl0** [comment]
@costrouc, @tylerpotts,

I think @iameskild has been using restic to back up our nfs volume since it supports incremental backups.  I wonder if these docs should be updated with that recommendation?  It seems like it might be more suitable for this task.

**Comment by costrouc** [comment]
@brl0 yeah I would prefer restic as the way to do backups. @tylerpotts is working on a formal backup solution that will use restic under the covers. Issue https://github.com/Quansight/qhub/issues/99 using velero. Which allows for multiple PVC backups
