### ISSUE TITLE
Fix old cruft in the docs from the qhub-repo

### ISSUE THREAD

**Issue by tonyfast** [Quansight/qhub#51]

**Comment by tylerpotts** [comment]
@tonyfast Could you clarify what you mean here?

**Comment by laisbsc** [comment]
I am not sure what this means either.
@tonyfast :)

**Comment by tonyfast** [comment]
theres stuff in here that shouldn't be from our churn. we need to make stuff go away that is irrelevent.

**Comment by laisbsc** [comment]
I am not sure what you mean by "irrelevant" but I am guessing I can just close this issue then.

Right, @tonyfast?

**Comment by tonyfast** [comment]
sure. now that you are on the case
