### ISSUE TITLE
Allow files with leading `.` to appear in file list

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#513]
## Description
Occasionally I need to edit a `.env` or some other `.something` file (with a leading `.`) 

## Suggestion
We can install `vim` which will allow me to edit these files via the terminal, but not everyone is versed in `vim`. If the file browser GUI could show these files, it would allow for the GUI text editor to edit them. This seems like the most optimal solution.

**Comment by aktech** [comment]
Do you mean, being able to see dotfiles in the Jupyter Lab UI? If yes, then it's beyond QHub, isn't it?

**Comment by kcpevey** [comment]
>Do you mean, being able to see dotfiles in the Jupyter Lab UI? 

yes

>it's beyond QHub, isn't it?

I don't know - is it? :)

**Comment by costrouc** [comment]
This shows the solution https://github.com/jupyterlab/jupyterlab/issues/2049 but we would decide how we want to enable this.

**Comment by costrouc** [comment]
This looks like a jupyterlab server configuration that would need to be made and not something that can be configured on the web browser side... maybe the vscode integration makes this less of a pain point? Since jupyterlab isn't an editor anyways.

**Comment by viniciusdc** [comment]
> This looks like a jupyterlab server configuration that would need to be made and not something that can be configured on the web browser side... maybe the vscode integration makes this less of a pain point? Since jupyterlab isn't an editor anyways.

@kcpevey Does the vscode integration helped to lessen the impact of this issue?
