### ISSUE TITLE
Reference to missing file [documentation]

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#516]
The deploy guides in `qhub/docs/source/04_how_to_guides` mention `./scripts/00-guided-install.sh` which doesn't exist in the repo.  Not sure what this should be replaced with.  @laisbsc do you happen to know?

**Comment by laisbsc** [comment]
This is another remain from the old docs. I believe the script was replaced by the `qhub render/deploy` steps, that now is just `qhub deploy`.

Thanks for flagging, will work on fixing this.

**Comment by viniciusdc** [comment]
@Adam-D-Lewis, I think we already solved that within the latest changes of the docs right?

**Comment by Adam-D-Lewis** [comment]
It looks like the docs have been significantly restructured since this issue was opened, solving the issue.
