### ISSUE TITLE
Docker Containers and Conda

### ISSUE THREAD

**Issue by sterlinm** [Quansight/qhub#52]
This looks like a really cool project. I know it's early on so this may be forthcoming but I was looking for some more details on how the docker containers work with conda. My general impression is that rather than including the conda environments in the image it's designed to mount a shared volume where the environments are stored. I can't seem to find the Dockerfiles that are used to define the qhub images. Are there any examples you could point me to? Thanks!

**Comment by costrouc** [comment]
Hey @sterlinm there are many approaches to including conda environments within docker containers. The standard way is usually to include a conda install at `/opt/conda` and include the environments at `/opt/conda/envs`. The dockerfiles that are used to define the qhub images are at https://github.com/Quansight/qhub/tree/master/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image. There are several reasons for using nfs for mounting the conda directory:
 - allows us to update user's conda environments independent of the container (and without restarting the user's image)
 - size of the docker image does not increase when you have multiple conda environments

But there are downsides (specifically with using NFS) and is often seen in hpc deployments. NFS is not a distributed filesystem so the reads/write do not scale well with many containers.

**Comment by costrouc** [comment]
@sterlinm if you are interested in building docker images with conda I'd recommend looking at https://github.com/jupyterhub/repo2docker. Also another approach is to base your docker image on https://hub.docker.com/r/continuumio/miniconda3.

**Comment by sterlinm** [comment]
Thanks so much! Do you think EFS has the same downsides as NFS?

**Comment by scopatz** [comment]
There is also https://github.com/conda-incubator/conda-docker which I think is the best way, personally

**Comment by sterlinm** [comment]
@scopatz I was looking at that last week but didn't quite figure out the details yet, I think mainly due to gaps in my mental model of docker images.

My general understanding is that I could use it to manipulate the layers of the image directly rather than using docker build. So if I have an image where the last layer adds the `/opt/conda` directory I could potentially remove that last layer and replace it with an alternative set of files for the `/opt/conda` directory. Does that sound about right?

**Comment by scopatz** [comment]
Yeah - the idea is that if you have a conda-env you can directly create a docker container.  No dockerfile is needed.  Just try it out! Let me know if you have any other questions!

**Comment by sterlinm** [comment]
Will do! I gave it a quick try this afternoon and got an error but it was from within a docker container and I haven't yet tried to debug it. I suspect it was user error but if it turns out to be reproducible I'll open an issue in the repo. Thanks!

**Comment by scopatz** [comment]
Cool thanks!

**Comment by costrouc** [comment]
Closing this issue @sterlinm as I think it is resolved. Please feel free reopen the issue if you need additional help

**Comment by sterlinm** [comment]
Sorry, I should have closed it. Thanks!
