### ISSUE TITLE
When conda-store can store no more [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#538]
## Describe the bug
Currently when the conda environment store of a QHub deployment (I believe it is an NFS mount?) fills up the failure is not so graceful: Environments don't get built but no error is displayed to the user.

## How can we help?

A kinder failure state would be nice for this. My understanding is that environment creation occurs on QHub after `qhub deploy` has reported success ... perhaps polling the availibility of expected environments before calling "deployment" complete and returning control to the user could be considered... or a report of the storage available for the environments that are not yet created.

Consider what a sensible default for available storage for environments will be. The store can be scaled (very easily on GCP as the mount can expand easily upon redeployment) but inferring that this is the source of the failure to create  environments is not trivial and space is cheap (relative to our time at least). So perhaps 200GB is a sensible default? It seems a lot but 10s of GB are filled pretty quickly with things like pytorch and tensorflow . Also, with the much appreciated versioning of environments that conda-store does under the hood, small tweaks to environments can also balloon the storage requirements very quickly.

**Comment by viniciusdc** [comment]
Hi @leej3, thanks for oppening this issue. This feature will be available with the next versions of [conda-store](https://github.com/Quansight/conda-store) @costrouc
