### ISSUE TITLE
Add ClearML Server Deployment Option in Qhub

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#540]
ClearML is a way to track experiment results for ML Models.  It'd be nice to add to Qhub.

Looks like some instructions for deployment exist at https://allegro.ai/clearml/docs/rst/deploying_clearml/index.html.  Initially

Likely, I'll plan to use the `Helm` deployment option.

More details:
ClearML is broken into roughly 3 parts. A local python package, a ClearML server, and a ClearML Agent for ML-Ops orchestration.  The priority is the ClearML server, if the ClearML agent is not too heavy a lift that would be great too (unclear how it’s orchestration functionality integrates with QHub). 

https://github.com/allegroai/clearml/#clearml-architecture

Ideally, finish this in the next 2 weeks.

# Acceptance Criteria

 - [ ] A PR that demonstrates a successful deployment of ClearML keeping in mind this is an initial deployment.

**Comment by Adam-D-Lewis** [comment]
More details:

ClearML is broken into roughly 3 parts. A local python package, a ClearML server, and a ClearML Agent for ML-Ops orchestration.  The priority is the ClearML server, if the ClearML agent is not too heavy a lift that would be great too (unclear how it’s orchestration functionality integrates with QHub). 

https://github.com/allegroai/clearml/#clearml-architecture

**Comment by Adam-D-Lewis** [comment]
Relevant files to follow (assuming I'm using helm chart)
- /home/balast/CodingProjects/qhub/qhub/template/cookiecutter.json
- qhub-terraform-modules/modules/kubernetes/services/prefect/main.tf

Looks pretty straight forwards

**Comment by Adam-D-Lewis** [comment]
Some useful resources on the ClearML side:
- Installation Instructions (https://github.com/allegroai/clearml-server-k8s/tree/master/clearml-server-cloud-ready)
- ClearML server architecture image (https://github.com/allegroai/clearml-server#launching-the-clearml-server)

Also, they just released v1.0 of ClearML, but the helm chart isn't ready yet.

**Comment by Adam-D-Lewis** [comment]
Looks like we'd need to create some PV's for the various components of ClearML:

>Persistent Volumes for pvc-apiserver.yaml, pvc-fileserver.yaml, and pvc-agentservices.yaml.
Persistent volumes for elasticsearch, mongodb and redis (redis is optional). See relevant information for each chart:
elasticsearch
mongodb
redis Make sure to define the following values for each PV:
elasticsearch - in the values.yaml set elasticsearch.persistence.enabled=true and set elasticsearch.volumeClaimTemplate.storageClassName to the storageClassName used in your elasticsearch PV.
mongodb - in order to define a persistent volume for mongodb, in the values.yaml set mongodb.persistence.enabled=true and set mongodb.persistence.storageClass to the storageClassName used in your mongodb PV. Read here for more details.
redis - in order to define a persistent volume for redis, in the values.yaml set redis.master.persistence.enabled=true and set redis.master.persistence.storageClass to the storageClassName used in your redis PV. Read here for more details.

**Comment by Adam-D-Lewis** [comment]
I tried to deploy ClearML after deploying Qhub.  It didn't work.  It seemed like I needed a `standard` storage class which didn't exist (at least not on Azure).  I tried adding a `standard` storage class that was similar to `default`, but it still didn't seem to work.  I kind of want to try on GCP to see if it that storage class exists there.  I may just need to ping them on their slack channel with my questions, bc I'm not sure why it's not working.

**Comment by vfdev-5** [comment]
@Adam-D-Lewis ping them on the slack they are very active there and can help.

**Comment by Adam-D-Lewis** [comment]
As I suspected, the standard storage class exists on GCP, and the deployment progressed further.  However, the elasticsearch container is still erroring out.  I've pinged clearML team on slack.  I'll post my question below

>Hi, I'm trying to deploy clearML on GKE on google cloud via helm using app version 1.0.2 and chart version 2.0.2+1.  I'm seeing the following Cannot allocate memory warnings and errors in my clearml-elastic-master-0 pod.

>| elasticsearch OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.                                   
│ elasticsearch {"type": "server", "timestamp": "2021-05-28T13:59:54,162Z", "level": "WARN", "component": "o.e.b.JNANatives", "cluster.name": "clearml-elastic", "node.name": "clearml-elas 
│ tic-master-0", "message": "Unable to lock JVM Memory: error=12, reason=Cannot allocate memory" }                                                                                          
│ elasticsearch {"type": "server", "timestamp": "2021-05-28T13:59:54,165Z", "level": "WARN", "component": "o.e.b.JNANatives", "cluster.name": "clearml-elastic", "node.name": "clearml-elas 
│ tic-master-0", "message": "This can result in part of the JVM being swapped out." }                                                                                                       
│ elasticsearch {"type": "server", "timestamp": "2021-05-28T13:59:54,166Z", "level": "WARN", "component": "o.e.b.JNANatives", "cluster.name": "clearml-elastic", "node.name": "clearml-elas 
│ tic-master-0", "message": "Increase RLIMIT_MEMLOCK, soft limit: 16777216, hard limit: 16777216" }                                                                                         
│ elasticsearch {"type": "server", "timestamp": "2021-05-28T13:59:54,166Z", "level": "WARN", "component": "o.e.b.JNANatives", "cluster.name": "clearml-elastic", "node.name": "clearml-elas 
│ tic-master-0", "message": "These can be adjusted by modifying /etc/security/limits.conf, for example: \n\t# allow user 'elasticsearch' mlockall\n\telasticsearch soft memlock unlimited\n 
│ \telasticsearch hard memlock unlimited" }                                                                                                                                                 
│ elasticsearch {"type": "server", "timestamp": "2021-05-28T13:59:54,167Z", "level": "WARN", "component": "o.e.b.JNANatives", "cluster.name": "clearml-elastic", "node.name": "clearml-elas 
│ tic-master-0", "message": "If you are logged in interactively, you will have to re-login for the new limits to take effect." } 

>... later in logs

>| elasticsearch ERROR: [1] bootstrap checks failed                                                                                                                                         │ elasticsearch [1]: memory locking requested for elasticsearch process but memory is not locked                      


>I imagine I could make the changes specified in the warning to /etc/security/limits.conf in my own slightly modified docker image, but I was wondering if anyone has seen this before and if there's something obvious I'm missing.  I'm using all defaults in the values.yaml file currently.

**Comment by Adam-D-Lewis** [comment]
Vini and I also upgraded some nodes to use `n1-standard-8` becase we got some error indicating the `n1-standard-2` instance was too small for ClearML on GCP.

**Comment by Adam-D-Lewis** [comment]
I'm assuming the error is due to ulimit missing:
try adding 16777216 to both soft/hard ulimit
https://github.com/allegroai/clearml-server/blob/09ab2af34cbf9a38f317e15d17454a2eb4c7efd0/docker/docker-compose.yml#L58

**Comment by viniciusdc** [comment]
> From the ClearML developer:
> 
> > I'm assuming the error is due to ulimit missing:
> > try adding 16777216 to both soft/hard ulimit
> > https://github.com/allegroai/clearml-server/blob/09ab2af34cbf9a38f317e15d17454a2eb4c7efd0/docker/docker-compose.yml#L58

Owh, thanks for the feedback on that. I will try twerking that and see if it solves the issue.

**Comment by Adam-D-Lewis** [comment]
@vfdev-5 found this reference to the changes I believe we need to make (but this applies to the single node deployment of clearML only rather than the cloud-ready version as I understand it) https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_server_kubernetes_helm.html

**Comment by Adam-D-Lewis** [comment]
I think I may have found a workaround for the moment.  I created my own docker image based on the original docker image, and created a custom entrypoint to run `ulimit -l unlimited` before running the normal entrypoint as specified in the link below.  https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-288451522

**Comment by viniciusdc** [comment]
> I think I may have found a workaround for the moment. I created my own docker image (balast/elasticsearch:5:56 on DockerHub) based on the original docker image, and created a custom entrypoint to run `ulimit -l unlimited` before running the normal entrypoint as specified in the link below. [kubernetes/kubernetes#3595 (comment)](https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-288451522). I also ran the elasticsearch container as root and added the capabilities IPC_LOCK and SYS_RESOURCE as mentioned in
> [kubernetes/kubernetes#3595 (comment)](https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-403407762).
> 
> Now the issue is that the apiserver isn't discovering the elasticsearch server. I don't see an clearml ingress pod up, maybe we have to create one?

It seems that the docker image was succefully initalized, but it restarts once `elasticsearch /custom-entrypoint.sh: line 5: ulimit: max locked memory: cannot modify limit: Operation not permitted`

**Comment by vfdev-5** [comment]
@Adam-D-Lewis @viniciusdc reading your messages, does it mean that this installation step : https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_server_kubernetes_helm.html#step-1-modify-elasticsearch-default-values-in-the-docker-configuration-file does not work ? Or we are in a bit different situation ?

**Comment by Adam-D-Lewis** [comment]
@aktech and @viniciusdc, can you comment on this?  These are the remaining steps as I see them: 
- Try a daemon set to modify the ulimits on the node
- Set up a new node pool for clearML in qhub
- the rest of integration into qhub (add feature flag, etc.) 
- Support for other cloud providers (will only work on GCP right now AFAIK)
   - Add standard storage class for other cloud providers (Push off for now)

**Comment by Adam-D-Lewis** [comment]
@vfdev-5 Those instructions don't apply to the cloud-ready clearML helm deployment directly (https://github.com/allegroai/clearml-server-k8s/tree/master/clearml-server-cloud-ready).  Those apply to https://github.com/allegroai/clearml-server-k8s/tree/master/clearml-server-chart.  The instructions for the clearML cloud-ready helm deployment is https://github.com/allegroai/clearml-server-k8s/tree/master/clearml-server-cloud-ready, but it didn't work for us off the bat.  First thing to know was you can't use Azure (currently), but GCP should work.  Second thing was how to get around the ulimits manually (which we did via a custom elasticsearch image, but are going to try Daemon Sets to rectify next).

**Comment by aktech** [comment]
> @aktech and @viniciusdc, can you comment on this? These are the remaining steps as I see them:

Looks good to me, other than that the obvious one is organizing the full yaml file into logical pieces.

By the way a trivial example of daemonset to start off with:


```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clearml-limits
  namespace: kube-system
  labels:
    k8s-app: clearml-limits
spec:
  selector:
    matchLabels:
      name: clearml-limits
  template:
    metadata:
      labels:
        name: clearml-limits
    spec:
      nodeSelector:
        app: clearml

      containers:
        - name: clearml-limits
          image: busybox
          volumeMounts:
            - mountPath: host-mount
              name: root-mount
          command: ["sh", "-c"]
          args:
            - cat host-mount/etc/docker/daemon.json;
              echo "vm.max_map_count=262144" > host-mount/tmp/99-clearml.conf;
              mv host-mount/tmp/99-clearml.conf host-mount/etc/sysctl.d/99-clearml.conf;
              cat host-mount/etc/sysctl.d/99-clearml.conf;
          securityContext:
            privileged: true
      volumes:
        - name: root-mount
          hostPath:
            path: /

```

**Comment by viniciusdc** [comment]
> @aktech and @viniciusdc, can you comment on this? These are the remaining steps as I see them:
> 
> * Set up a new node pool for clearML in qhub
> * Try a daemon set to modify the ulimits on the ClearML nodepool nodes
> * the rest of integration into qhub (add feature flag, etc.)
> * Support for other cloud providers (will only work on GCP right now AFAIK)
>   
>   * Add standard storage class for other cloud providers (Push off for now)

Sure, I think you addressed all the general steps needed. Just a quick question, those are related only to get the ClearML server running with QHUb right? Are we considering connecting it to the [ClearML client](https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_config_for_clearml_server.html) too?

**Comment by aktech** [comment]
Status with this: The [clearml branch](https://github.com/Quansight/qhub/tree/clearml) now has the kubernetes manifest in the terraform and it deploys clearml components correctly with QHub. The next step is exposing the webserver via Traefik.

**Comment by aktech** [comment]
Update so far: It seems there isn't a way to access clearml server on a path say `qhub-url/clearml` as the server doesn't redirects the static files to the correct path. I am going to try the subdomain approach as suggested in the doc:
https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_server_kubernetes.html#accessing-clearml-server

**Comment by Adam-D-Lewis** [comment]
@vfdev-5 and I pair programmed for most of today in order to get the feature flag and node labels added.

**Comment by Adam-D-Lewis** [comment]
I fixed some minor terraform formatting on the PR.  The checks on the PR are still failing with the error below and I don't know why. (https://github.com/Quansight/qhub/pull/640/checks?check_run_id=2840961922

>Run nslookup github-actions.qhub.dev
Server:		127.0.0.53
Address:	127.0.0.53#53
** server can't find github-actions.qhub.dev: NXDOMAIN
