### ISSUE TITLE
Add version tag to qhub header

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#555]
## Description
It would be helpful for end users to have insight into when changes have been made on the deployment.

## Suggestion
Given that deployment is automated via CI upon tagging release (at least that’s mostly the case?), I’d like to request that the gh tag be added to the jupyterlab header. We did this in one of the qadmin deployments. Its just helpful for end users to know when a change has been made.

## Context
An example - I asked John to update our env for me this morning (since I have no access). He had other things he was dealing with so he did it later in the day. If I had a version tag on the header, I’d be able to see when a change was implemented.

**Comment by iameskild** [comment]
Question for the team:
- Can we configure the "JupyterLab" name?

**Comment by viniciusdc** [comment]
> Question for the team:
> 
> * Can we configure the "JupyterLab" name? Change to "QHub"?
>   
>   * [Changing Browser Tab Title for JupyterLab jupyterlab/jupyterlab#4422](https://github.com/jupyterlab/jupyterlab/issues/4422)
> * Update the QHub theme as well?

As per the latest discussion on this, there is two addition we can do to benefit the end-user:
- Add the current qhub version to the Jupyterhub theme pages, this would be similar to Qadmin (as @kcpevey  commented)
- The second one is adding another piece of info in the jupyterhub lab session tab, as suggested in the link above. To do so we would need to update the initialization command for the lab user ```jupyter lab --name='n-th lab'``` (I think we are currently adding the user name to that...)

For now, I will submit a PR to address the first point (which is the enchantment requested here) and will open another issue to discuss the second one.
