### ISSUE TITLE
Gitlab integration tests

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#562]

**Comment by rsignell-usgs** [comment]
@danlester , just a note that USGS uses gitlab and are eagerly anticipating this capability.  We would be willing to be alpha/beta testers if you need!

**Comment by dharhas** [comment]
@rsignell-usgs Gitlab Integration is in QHub now 🎉 

Instructions are here: https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html?highlight=ci#continuous-integration-and-continuous-deployment

We've only used it in one place so far so testing is more than welcome. If y'all are up for it why don't you try an install and let us know how it goes.

**Comment by danlester** [comment]
Vini, please note that the GitHub Actions tests are now working!

They should inspire the gitlab versions...

I've also updated the readme.

https://github.com/Quansight/qhub-integration-test/blob/main/.github/workflows/gcp-github.yml

**Comment by costrouc** [comment]
@danlester thanks for getting this working. Does this move this issue to done?

**Comment by viniciusdc** [comment]
> @danlester thanks for getting this working. Does this move this issue to done?

Hi @costrouc, currently by @danlester comment we do have the GitHub integrations tests done, the Gitlab versions still need to be implemented. I've talked with Dan some while ago and I will soon submit a PR.

**Comment by tarundmsharma** [comment]
Hi @viniciusdc, Any update on this issue.
Thank you
