### ISSUE TITLE
Upgrade framework

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#564]
Some kind of upgrade framework, perhaps a `qhub upgrade` command to modify the YAML.
Not sure about e.g. if changes are needed to the NFS itself, that would probably need a check in the code itself, maybe based on a configmap.
Might need a qhub_version entry in the yaml.

**Comment by tylerpotts** [comment]
Also would be helpful to upgrade the docker image tags now that the tags will be based on an QHub release.

Would also be nice for qhub deploy to throw an error if there's a mismatch between the qhub version and docker image version in `qhub_config.yaml`
