### ISSUE TITLE
Documentation for onboarding users to QHub (user focused docs)

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#569]
Currently our documentation is focused towards deploying and maintaining a QHub cluster. We need more docs that focus on onboarding new users for QHub:
  - show new users how to login and use QHub
  - details about ssh and sftp usage
  - details about creating a dashboard
  - details about sharing files with team

**Comment by kcpevey** [comment]
Q&A:
1. I need X package and its not in any available environments - what do I do?
The proper solution is to add the package to the `qhub_config.yml`. If you don't have access to the deployment repo, you will need to contact your QHub maintainer to get the required package. Just to note: you can do a user install for pip packages in a pinch (not recommended).
2. Where do environments come from? Who creates them?
The environments are located in `qhub_config.yml` in the deployment repo. There are no limits to the number of environments that can be included. Do be careful of the yaml indentation as it will differ from a conda `environment.yml`. 
3. I want to use Dask. What needs to be included in my environment?
4. Why can't I just create my own local conda environment?

**Comment by kcpevey** [comment]
5. I have a local package - how can it be installed? Will it be available to my Dask workers?

**Comment by ericdatakelly** [comment]
This might be more appropriate in this issue. https://github.com/Quansight/aes-management/issues/155#issuecomment-845963523

**Comment by kcpevey** [comment]
Thanks @ericdatakelly I will include the items listed there as well. I wanted to open this up a general QHub issue so that we could get broader input.

**Comment by kcpevey** [comment]
7. How do I use my personal credentials on dask works (not loaded via a package)?

**Comment by kcpevey** [comment]
8. I can't see the active conda env in the terminal. Run this `conda config --set changeps1 true` (https://github.com/Quansight/aes-management/issues/154)

**Comment by kcpevey** [comment]
9. I want to use QHub server to compute a new pinned environment (which I'll the serve via the `qhub_config.yml`). I understand it's not recommended I use this environment for working. 
If you need to solve a conda env on a QHub server (not recommended, but there are valid usecases for this), you'll need to specify the prefix. For example, `conda env create -f env_test.yml --prefix /tmp/test-env` where `test-env` will be the env name.

**Comment by kcpevey** [comment]
First pass: https://github.com/Quansight/qhub/pull/616

**Comment by kcpevey** [comment]
These have all been merged. We can open up additional PRs or issues for expanding on this.

**Comment by kcpevey** [comment]
Actually, it just occurred to me that this is @costrouc original issue and I didn't cover all those things in my FAQ...
