### ISSUE TITLE
Openstack Provider for QHub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#578]
Opening this issue to track progress with Openstack support. Right now this would be in the research stage just trying to find out how feasible this is.

There is an [openstack provider](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs) along with some terraform modules:
 - https://github.com/rancher/terraform-provider-rke
 - https://github.com/remche/terraform-openstack-rke

So this looks feasible. Once we have a kubernetes engine provisioned it should be easy to connect to the rest of Kubernetes. The hardest part on our side is how to test this easily since at Quansight we don't have an easy way to spin up openstack clusters. Advice here would be welcome @ChrisLayton.

**Comment by LaytonCC** [comment]
@costrouc  the most common way to "kick the tires" on Openstack is via [Packstack](https://www.rdoproject.org/install/packstack/)  but there are others. One option might be to request a small allocation on a science based public cloud like [Jetstream](https://jetstream-cloud.org/) as the only cost is your time to fill out the paperwork. If you decide to go that route and are interested in some help getting up and running there quickly hit me up on Slack. 


I did a quick checkout of [qhub-hpc](https://github.com/Quansight/qhub-hpc) and it looks like it might also be a good fit for us. Once I get back from vacation I will see about testing it out.

**Comment by costrouc** [comment]
Thanks @LaytonCC! I'm going to be trying out packstack with kvm later this week. qhub-hpc works well with dedicated resources. We haven't yet had the time to integrate the autoscaling capabilities of slurm.
