### ISSUE TITLE
[enhancement] Set `min_node: 0` for QHub deployed on AWS

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#595]
## Description
The new datum QHub deployed on AWS has the limitation that each node groups must have [`min_node: 1` for autoscaling to work](https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html?highlight=autoscaling#amazon-web-services-aws). This means that if we want multiple node groups, we will be charged for all the different EC2 instances that must be running as part of that node group. This will incur costs even when they are not being used (ie. dask-worker related node groups). 

In order to cut down on operating costs, we only created one node-group ("general"). 

## Suggestion
It would be nice to have the ability to set `min_node: 0` for QHub deployed on AWS, like we had on GCP.  

## Context
This is not a show-stopper. Raising this issue here because I imagine this is a feature that many other QHub/AWS users might appreciate as well 😀

### If the request is related to a specific version of Kubernetes or Cloud provider, please provide these details:
Describe your environment:
    - Kubernetes version (use `0kubectl version`): v1.19.8-eks-96780e
    - Cloud provider (e.g. AWS, GCP, DigitalOcean, etc): AWS

> Feel free to add any **additional context** or screenshots about the feature request here.

**Comment by costrouc** [comment]
We would love to support this! This will work out of the box once AWS supports this https://github.com/aws/containers-roadmap/issues/724
