### ISSUE TITLE
Create documentation for manually destroying resources in AWS

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#605]
Document how to destroy resources after looking them up by tag in AWS

**Comment by tylerpotts** [comment]
Somewhate related to #579

**Comment by tylerpotts** [comment]
Basic steps:
- delete EFS
- delete nodegroups
- delete eks cluster
- delete security group

**Comment by rsignell-usgs** [comment]
Yes, these basic steps worked for me!

**Comment by brl0** [comment]
@iameskild, You've been through this a couple of times recently, it would be good to add anything else that you think should be checked to this issue.

**Comment by tylerpotts** [comment]
Converting to a discussion for future posterity
