### ISSUE TITLE
Create docs for destroying manually on GCP via console

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#606]
Document how to destroy resources on Google if terraform fails

**Comment by alimanfoo** [comment]
Just to say this would be very useful, I've needed this. My currently checklist for manual destruction is:

* GKE: Delete cluster
* GKE: Delete services
* GCE: delete all instance groups (shouldn't be necessary if deleted GKE cluster)
* GCE: delete all disks (shouldn't be necessary if deleted GKE cluster)
* GCS: delete terraform state bucket
* IAM: Delete the service account create by qhub

Also I then delete all folders locally created by qhub deploy.

**Comment by iameskild** [comment]
Add troubleshooting section on what resources need to be deleted if `destroy` fails.

**Comment by trallard** [comment]
status update on this please @iameskild

**Comment by iameskild** [comment]
Hey @trallard I was never working on this so I'm not sure. By the looks of it, nothing has been done.

**Comment by trallard** [comment]
closing as I have moved to Nebari and will be superseded there
