### ISSUE TITLE
Pin QHub dependencies 

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#619]
The QHub CLI was broken most likely due to the unpinned version of library `ruamel.yaml`. There are a bunch of libraries in the `setup.py`, which should be pinned to have more stability.

https://github.com/Quansight/qhub/blob/51ed41bd1cc1bb13cb0e3fdb729ef6837c1ffcd3/setup.py#L34-L58

**Comment by costrouc** [comment]
Agreed. Especially for a devops focused tool I think we should favor pinning for stability.

**Comment by viniciusdc** [comment]
Should we pin that directly or give it a lower bound? @costrouc

**Comment by tarundmsharma** [comment]
@costrouc, can you please help me with the pin versions.

**Comment by tarundmsharma** [comment]
https://github.com/Quansight/qhub/pull/724
