### ISSUE TITLE
Hiding envs after they are removed. [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#622]
## Describe the bug
When an environment is removed from the qhub-config.yaml it still appears as an available kernel for notebooks.

## How can we help?

Not sure how  tricky this is  to implement. On face value it is just removing  env symlinks to the store of hashed envs when they do not in the qhub-config.yaml ... but what if someone wants to use an environment that they used to have! Oh the choices. Not sure if there is a perfect solution and may not be worth it before migration to the updated conda-store implementation.

**Comment by viniciusdc** [comment]
Yeah, it seems to be related to conda-store not updating it's `environments` folder (you can inspect the successfully built environments inside `home/conda/environments`, or k9s into the `conda-store` pod to inspect it). A solution to this problem might be addressed in the next release as we are working to add configurable conda-store images to QHub.
@costrouc
