### ISSUE TITLE
Azure needs an available Kubernetes version

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#628]
Available kubernetes versions on Azure are subject to change. Look up a suitable available version, maybe:

https://docs.microsoft.com/en-us/rest/api/aks/agent-pools/get-available-agent-pool-versions

Just like we had to do for Digital Ocean here: https://github.com/Quansight/qhub/blob/main/qhub/provider/cloud/digital_ocean.py

**Comment by costrouc** [comment]
This looks reasonably tricky to automate but would be extremely useful to have. I belive that first action is to create a curl request that can succesfully return the available kubernetes versions.

**Comment by dhirschfeld** [comment]
In case it's useful I use this command to check available AKS versions:
```
> az aks get-versions -l australiaeast -o table
The behavior of this command has been altered by the following extension: aks-preview

KubernetesVersion    Upgrades
-------------------  ------------------------
1.21.2               None available
1.21.1               1.21.2
1.20.7               1.21.1, 1.21.2
1.20.5               1.20.7, 1.21.1, 1.21.2
1.19.11              1.20.5, 1.20.7
1.19.9               1.19.11, 1.20.5, 1.20.7
1.18.19              1.19.9, 1.19.11
1.18.17              1.18.19, 1.19.9, 1.19.11
```

**Comment by costrouc** [comment]
Thanks @dhirschfeld! We're trying to find a way to gather this information without the `az` command as we didn't want to make the install process any trickier for users... but maybe this is the way that it has to be done :/

**Comment by dhirschfeld** [comment]
I suppose you could use the python SDK directly rather than installing the CLI.

**Comment by dhirschfeld** [comment]
Looks like `terraform` is another way to get this info:
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_service_versions

**Comment by trallard** [comment]
@danlester and @iameskild  seems like #927 addresses this issue - can we close now?

**Comment by iameskild** [comment]
@trallard yes we can :)
