### ISSUE TITLE
Create Personas for QHub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#634]
Currently documentation is extremely focused on devops people trying to deployment QHub. Need to have docs that focus on the end-users, etc. And establish personas.

**Comment by kcpevey** [comment]
Started creating user personas here: https://www.notion.so/quansightlabs/a0e30cf0d3d64775afafbb15430ea010?v=701f1cb6def940a5b639768c7bf89706

**Comment by trallard** [comment]
This has been completed will keep this with the rest of the doc work
