### ISSUE TITLE
Upgrade Helm Terraform provider to the latest

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#635]
Currently we use a pretty old version of terraform's helm provider:

https://github.com/Quansight/qhub/blob/7b36352946170d29f9d5f1a13f634ee0961a043c/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/versions.tf#L23

The current version is [2.1.2](https://registry.terraform.io/providers/hashicorp/helm/latest)
The current version has some issues like this one: https://github.com/hashicorp/terraform-provider-helm/issues/497
It would be great to upgrade to the latest version.

**Comment by brl0** [comment]
Funny, version `2.2.0` was released yesterday.

**Comment by costrouc** [comment]
Removed `good first issue` tag since it looks like @aktech has this resolved when the PR is merged.
