### ISSUE TITLE
Make load balancer configurable [enhancement]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#638]
## Description
As discussed in #636 with @danlester I am using a deployment with an internal load balancer. This was previously implemented by @costrouc by modifying the terraform modules:

```
diff --git a/modules/kubernetes/ingress/main.tf b/modules/kubernetes/ingress/main.tf
index bdb4943..4f61cb8 100644
--- a/modules/kubernetes/ingress/main.tf
+++ b/modules/kubernetes/ingress/main.tf
@@ -59,10 +59,13 @@ resource "kubernetes_service" "main" {
   wait_for_load_balancer = true
 
   metadata {
     name      = "${var.name}-traefik-ingress"
     namespace = var.namespace
+    annotations = {
+      "networking.gke.io/load-balancer-type" = "Internal"
+    }
   }
 
   spec {
     selector = {
       "app.kubernetes.io/component" = "traefik-ingress"
@@ -102,10 +105,12 @@ resource "kubernetes_service" "main" {
       port        = 8786
       target_port = 8786
     }
 
     type = "LoadBalancer"
+
+    load_balancer_ip = "10.247.11.22"
   }
 }
```

This modification defines the load balancer as internal and sets the IP. Now that the terraform modules are part of the QHub repo this strategy cannot be used anymore. Could we make this configurable by adding it as an optional section in the qhub-config.yaml or something like that?

**Comment by danlester** [comment]
@costrouc you also mentioned a client with custom terraform_modules - what are their requirements?

**Comment by danlester** [comment]
I also think supporting this as optional in qhub-config.yaml would be fine:

```
load_balancer_type: Internal
load_balancer_ip: 10.247.11.22
```

I think the only question would be if other clouds are different, but this doesn't have to be a heavily-documented feature initially. (Or state only currently understood in GCP.)

Maybe more flexible to say:
```
load_balancer_annotations:
  networking.gke.io/load-balancer-type: "Internal"
load_balancer_ip: 10.247.11.22
```
Either way, I believe HCL can allow these to be optional.

But maybe I'm missing something about why you have concerns here?
