### ISSUE TITLE
AWS VPC (and possibly other clouds) need larger subnets

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#644]
## Description

Create a larger default subnet for AWS. They should be size 10.10.0.0/20 of `/20` 

## Acceptance Criteria

 - [x] AWS Qhub deployment should have a larger default subnets

**Comment by tylerpotts** [comment]
#645 fixes this for AWS

**Comment by costrouc** [comment]
Closing since #645 is resolved.
