### ISSUE TITLE
[enhancement] Optionally add RBAC permissions for AWS EKS cluster

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#648]
## Description
After deploying qhub, additional steps are necessary to grant RBAC permissions to other AWS administrators.

## Suggestion
It would be convenient to have an option to grant permissions to other users.
Another, possibly better approach, would be to take a list of users in the config file and create an IAM group and then grant permissions to that group.
This approach seems likely to be potentially adaptable to providers other than AWS.

## Context
This would help simplify the management of the cluster by ensuring designated IAM users have appropriate access to the cluster.

@iameskild, @tylerpotts, can you provide additional details about how permissions need to be added currently?

**Comment by brl0** [comment]
Possibly related to #12.

**Comment by costrouc** [comment]
> After deploying qhub, additional steps are necessary to grant RBAC permissions to other AWS administrators.

@brl0 do you have any ideas how we could automate this in terraform? From what I remember you have to add/modify a resource in kubernetes.

**Comment by brl0** [comment]
Good question, off the top of my head, I would think we might be able to create the appropriate roles or role bindings needed with the standard kubernetes provider, and if not, perhaps using a `kubernetes_manifest` from the `kubernetes-alpha` provider, at least as a fall back approach.  

I think provisioning a group directly in the cloud provider's IAM and then granting permission to that group would be more maintainable, if that is possible.
