### ISSUE TITLE
Create PR template for QHub development

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#651]
It should be interesting to have a template for PR's too, at least to check if the contributor linked an issue or if the closing keys were included.

PR Checklist:

- [ ] Include reference for the associated issue;
- [ ] note any issues closed by this PR with closing keywords
- [ ] put any other relevant information below

**Comment by costrouc** [comment]
@viniciusdc could you elaborate more on this issue and the purpose?

**Comment by viniciusdc** [comment]
> @viniciusdc could you elaborate more on this issue and the purpose?

@costrouc What do you think?
