### ISSUE TITLE
[bug] 500 : Internal Server Error when starting the server

### ISSUE THREAD

**Issue by emiliom** [Quansight/qhub#654]
## Describe the bug
A clear and concise description of what the problem is.

I've deployed a new QHub cluster on AWS (my first time). The cluster is available and I can log in. But when I try to start the server ("Start My Server" blue button), I get this error in big red letters: 500 : Internal Server Error 

I've tried this twice now with the same outcome, after clearing out all AWS resources from the first try.

## How can we help?
Help us help you.
* What are you trying to achieve? 
> Have a functioning JupyterLab in QHub cluster on AWS, following the step-by-step instructions in the documentation.
* How can we reproduce the problem?
> Not sure. But I can describe all steps.
* What is the expected behaviour?
* And what is currently happening? 
> See above. When I try to start the server ("Start My Server" blue button), I get this error in big red letters: 500 : Internal Server Error 
* Any error messages?
>  500 : Internal Server Error 
* If helpful, please add any screenshots and relevant links to the description.
> I'm not sure this will add anything, but I posted some earlier issues at https://github.com/Quansight/qhub/discussions/625 (and got help on those upstream steps, thanks!)

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

Installed qhub from conda-forge
```bash
$ conda --version
conda 4.10.1

$ qhub --version
0.3.11
```

**Comment by costrouc** [comment]
@emiliom thanks for your issue. 

Would you by any chance have access to the kubernetes cluster status? Here are docs on how to view the logs https://docs.qhub.dev/en/stable/source/02_get_started/06_troubleshooting.html?highlight=k9s#debug-your-kubernetes-cluster. I believe you will need to look at the pod that spawns your jupyterlab server. Would you mind checking that out and showing us the logs or a screenshot when there is that issue.

**Comment by emiliom** [comment]
Thanks @costrouc . I had not used k9s before. I've now set up my kubernetes context for AWS (`aws eks --region us-west-2 update-kubeconfig --name qhubcluster-dev`), then ran k9s [via Docker](https://github.com/derailed/k9s#running-the-official-docker-image). The kubernetes context is read, but the first screen stays in the listing of contexts (just one) and doesn't get to a listing of pods:

![first screen](https://user-images.githubusercontent.com/742403/122487081-3ae08e00-cf8f-11eb-9a83-325fe1af1219.png)

When I hit return, I get a message saying "unable to connect to context " plus my context `arn`. If I let it sit, after 10-20 seconds the k9s logo in the upper right turns purple and starts a countdown that says "Dial K8s Toast [1/5]", counting from 1/5 to 5/5, then exiting k9s:

![Selection_099](https://user-images.githubusercontent.com/742403/122487259-b04c5e80-cf8f-11eb-8212-2ea6f18dc8e3.png)

**Comment by emiliom** [comment]
Just wondering if you have any suggestions for what may be failing or where I could look next. Thanks!

**Comment by aktech** [comment]
@emiliom It's hard to say anything without seeing the kubernetes cluster status. What was the response in the CLI when you ran: `aws eks --region us-west-2 update-kubeconfig --name qhubcluster-dev` ?

Also, were you able to run any `kubectl` commands after setting the context if not `k9s`?

Perhaps you could just try: `kubectl get pods` ?

**Comment by emiliom** [comment]
Thanks for the follow up, @aktech .

> It's hard to say anything without seeing the kubernetes cluster status. What was the response in the CLI when you ran: aws eks --region us-west-2 update-kubeconfig --name qhubcluster-dev ?

I saved the run-time message: "Added new context arn:aws:eks:us-west-2:750544710208:cluster/qhubcluster-dev to /home/mayorga/.kube/config"

> Also, were you able to run any `kubectl` commands after setting the context if not `k9s`? Perhaps you could just try: `kubectl get pods` ?

I'm a newbie with kubernetes, so I didn't try anything else. Just now I tried redeploying the cluster (`qhub deploy -c qhub-config.yaml --dns-provider cloudflare --dns-auto-provision`), but the process failed with an error I hadn't encountered before: `Error: Get "http://localhost/api/v1/namespaces/dev": dial tcp 127.0.0.1:80: connect: connection refused`. I'll try it again tomorrow.

Here's the larger run-time chunk where the error occurs:
```
...
[terraform]: module.kubernetes.aws_eks_cluster.main: Refreshing state... [id=qhubcluster-dev]
[terraform]: module.kubernetes-initialization.kubernetes_namespace.main: Refreshing state... [id=dev]
[terraform]: 
[terraform]: Warning: Resource targeting is in effect
[terraform]: 
[terraform]: You are creating a plan with the -target option, which means that the result
[terraform]: of this plan may not represent all of the changes requested by the current
[terraform]: configuration.
[terraform]: 		
[terraform]: The -target option is not for routine use, and is provided only for
[terraform]: exceptional situations such as recovering from errors or mistakes, or when
[terraform]: Terraform specifically suggests to use it as part of an error message.
[terraform]: 
[terraform]: 
[terraform]: Error: Get "http://localhost/api/v1/namespaces/dev": dial tcp 127.0.0.1:80: connect: connection refused
[terraform]: 
[terraform]: 

Problem encountered: Terraform error
```

**Comment by emiliom** [comment]
I just noticed another error that occurs about half way through the deploy process, though it's not a fatal one: `Error: Cannot import non-existent remote object`. See the context below. I don't remember seeing this in previous deploy attempts. But I'll also add the caveat that in these various attempts, `qhub destroy` often fails and I end up having to manually delete AWS resources that got created during `qhub deploy`, both to clear things for the next attempt and to minimize the risk of leaving active resources on AWS.

```
...
[terraform]: module.terraform-state.aws_dynamodb_table.terraform-state-lock: Importing from ID "qhubcluster-dev-terraform-state-lock"...
[terraform]: module.terraform-state.aws_dynamodb_table.terraform-state-lock: Import prepared!
[terraform]:   Prepared aws_dynamodb_table for import
[terraform]: module.terraform-state.aws_dynamodb_table.terraform-state-lock: Refreshing state... [id=qhubcluster-dev-terraform-state-lock]
[terraform]: 
[terraform]: Error: Cannot import non-existent remote object
[terraform]: 
[terraform]: While attempting to import an existing object to
[terraform]: aws_dynamodb_table.terraform-state-lock, the provider detected that no object
[terraform]: exists with the given id. Only pre-existing objects can be imported; check
[terraform]: that the id is correct and that it is associated with the provider's
[terraform]: configured region or endpoint, or use "terraform apply" to create a new remote
[terraform]: object for this resource.
...
```

**Comment by aktech** [comment]
>I just noticed another error that occurs about half way through the deploy process, though it's not a fatal one: Error: Cannot import non-existent remote object. See the context below. I don't remember seeing this in previous deploy attempts. But I'll also add the caveat that in these various attempts, qhub destroy often fails and I end up having to manually delete AWS resources that got created during qhub deploy, both to clear things for the next attempt and to minimize the risk of leaving active resources on AWS.

Ah, I see. That's kind of expected, when you delete resources manually it's a little hard to make sure that you destroy everything cleanly, we recommend using `destroy` command for the same.

```bash
qhub destroy --config qhub-config.yaml
```

By the way I am happy to get on a quick call to help you get started, feel free to let us know in here:
https://gitter.im/Quansight/qhub

**Comment by emiliom** [comment]
> Ah, I see. That's kind of expected, when you delete resources manually it's a little hard to make sure that you destroy everything cleanly, we recommend using destroy command for the same.
> 
> qhub destroy --config qhub-config.yaml

Yeah, that's exactly what I'm doing; sorry, I said "qhub destroy" as a short hand of the full statement. The trouble is that b/c this statement often ends in error, AWS resources are left stranded and the next `qhub deploy` attempt fails. So I've found that the only way to get back to square one after `qhub destroy --config qhub-config.yaml` fails is to clear the resources manually.

> By the way I am happy to get on a quick call to help you get started, feel free to let us know in here:
> https://gitter.im/Quansight/qhub

Thank you! I'll take you up on it early next week.

**Comment by emiliom** [comment]
FYI, after manually clearing AWS resources (dynamodb table only), I tried deploying the hub again:
```bash
qhub deploy -c qhub-config.yaml --dns-provider cloudflare --dns-auto-provision
```

But hit the same terraform error as before:
```
Error: Get "http://localhost/api/v1/namespaces/dev": dial tcp 127.0.0.1:80: connect: connection refused
```

**Comment by aktech** [comment]
What I have seen is it happens for the first time and disappears the second time you try it.

**Comment by emiliom** [comment]
Thanks for the follow ups. I haven't tried deploying qhub again since my last comment on July 12. At that point, the same error had appeared on two consecutive tries, separated by 4-5 days.

@aktech I haven't taken you up on the offer to connect on gitter. I can post my issue there (hopefully by tomorrow) and when you're online we can follow up live

**Comment by aktech** [comment]
@emiliom Yeah, sure live will be great.
