### ISSUE TITLE
Prefect integration does not seem to honor a non-default namespace [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#655]
## Describe the bug

With `prefect: true` I get the following error during deployment:

```
nding.controller: Refreshing state... [id=qhub-daskgateway-controller]
[terraform]: module.prefect.helm_release.prefect: Creating...
[terraform]: 
[terraform]: Error: namespaces "dev" not found
[terraform]: 
[terraform]:   on modules/kubernetes/services/prefect/main.tf line 1, in resource "helm_release" "prefect":
[terraform]:    1: resource "helm_release" "prefect" {
[terraform]: 
[terraform]: 
Problem encountered: Terraform error
ERROR: Job failed: command terminated with exit code 1
```

The deployment is under a different namespace (set in the qhub config yaml)

**Comment by aktech** [comment]
That's unexpected, the prefect is supposed to deployed with the namespace mentioned here:
https://github.com/Quansight/qhub/blob/b530bc3019acf748034130b3a13519bd11263e15/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/kubernetes.tf#L218

Just to confirm, there is a key in your qhub config yaml like the following, right?
```
namespace: <some-namespace>
```

**Comment by leej3** [comment]
Correct:
```namespace: qhub```

Currently deploying using gitlab integration off: https://github.com/leej3/qhub-cloud/commits/load-balancer-configuration

Using a pre-existing K8s deployment with an internal load-balancer specified in the qhub-config.yml... don't think it's relevant but just in case.
