### ISSUE TITLE
User accessible deployment logs [enhancement]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#657]
## Description
I discussed this briefly yesterday with some of the team. On some deployments we do not have access to the deployment server and so we cannot use k9s for debugging. That makes it trickier to quickly infer the source of deployment issues. Making logs available somewhere on QHub would be very helpful.

@aktech suggested a combination of fluentd and Elasticsearch to provide a convenient interface for the user...

**Comment by costrouc** [comment]
@leej3 this is a complicated issue I think this question is generally about how you would like more insight into what is happening on the Kubernetes cluster. Logging is only part of this. There are solutions out there for log aggregation and on the cloud providers e.g. gcp, aws, and others they actually already aggregate logs for you and expose them via their own monitoring tools.

Ideally your team should be given read only access to the `qhub` deployment namespace and then you can view much more than just logs.

Closing in favor of issue https://github.com/Quansight/qhub/issues/39.
