### ISSUE TITLE
Addition end-user FAQs

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#659]
This issue is to collect FAQs for end users. Commonly hit issues, gotchas, and other things which may affect end users can be reported here and I'll add it to the FAQ page intermittently.

**Comment by kcpevey** [comment]
* I might have pushed my QHub server too much.  Now I can't run any kernels, not even a terminal (I just see a blank terminal).  I stopped the servers and restarted one, but I still can't run a notebook or start a terminal.
  *  You likely hit the memory limits of the pods and crashed python. You'll have to give k8s time to clean out your old pod. If you stop your server and then immediately restart, you will likely just get the old one back. You should give it at least 5 minutes between stopping and restarting. 
  * If you have the old window open in another tab, that may also keep your old pod alive. Be sure to close all tabs you have open on the server.

**Comment by tylerpotts** [comment]
This needs further discussion to decide how to handle github issues vs discussions, and possibly leveraging bots

**Comment by costrouc** [comment]
Some ideas that we talked about in our meeting. We could use github discussions (which we are already using) for these quenstions. We would need documentation to point users to ask questions here. @kcpevey thoughts?

**Comment by tylerpotts** [comment]
Leveraging discussions would create a searchable persistent place for debugging. I think that's also a low-effort place to start with FAQ, so long as the title gets updated to reflect what question the discussion is answering.

This also solves the problem of discussions creating noise when it comes to github issue/project management. I agree with the purpose of issues [described here](https://guides.github.com/features/issues/), which is "[...]a great way to keep track of tasks, enhancements, and bugs for your projects". If a github issue isn't actionable, it should be converted to a discussion. If a discussion requires an action, either create an issue or convert the discussion to an issue.

I like @Adam-D-Lewis 's idea of having a link to discussions in the new issue screen. If someone creates an issue that should be a discussion, or a discussion that should be an issue, it is trivial to convert them by clicking the button on the right side in github:

![image](https://user-images.githubusercontent.com/49161327/122601492-fc061300-d036-11eb-8db0-2f5c0b6bc5c0.png)
![image](https://user-images.githubusercontent.com/49161327/122601527-09230200-d037-11eb-9cb9-ab47ea242f57.png)

**Comment by costrouc** [comment]
Closing this issue since it is not well scoped. We have documentation for a place for users in the user guide https://docs.qhub.dev/en/latest/source/user_guide/faq.html.
