### ISSUE TITLE
prefect image specification

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#662]
@aktech,

I think it would be a good idea to support specifying a prefect image to be used in the qhub config file.  

Currently the prefect image specified by qhub is nearly a year old, version 0.12.2, dated June 30, 2020, as seen [here](https://github.com/Quansight/qhub/blob/b530bc3019acf748034130b3a13519bd11263e15/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/prefect/chart/values.yaml#L1).  The latest version as of this writing is 0.14.22, dated June 16, 2021.

Also, the prefect images are python version specific, and we have moved to using python 3.8.

For precedent, recently a similar feature was added to support conda-store image specification in #623, as was dask gateway in this [commit](https://github.com/Quansight/qhub/commit/d99a4e9b77854181c732f12ad3e31996b27266c3).

## Acceptance Criteria
- User is able to specify optional QHub prefect docker image in the `default_images` key
- Documentation reflects new configuration option

**Comment by costrouc** [comment]
@brl0 this is a great idea. Like you said there is a PR https://github.com/Quansight/qhub/pull/623/ that already serves as a good template for how to implement this. Adding this to good first issues.

**Comment by aktech** [comment]
Fixed here: #667
