### ISSUE TITLE
Checklist for 0.3.12 release

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#679]
## Release 0.3.12
The following tests will be manually run on 4 cloud providers (Azure, AWS, Digital Ocean, GCP)

- [ ] Test Dask can spin up a worker. This has to be done after 10 minutes of waiting so the conda store can create the environments

**Comment by brl0** [comment]
> * This has to be done after 10 minutes of waiting so the conda store can create the environments

It would be possible to test using the `default` environment already included on the jupyterlab images... to make that workable, that environment would need to be added to the dask worker image.

**Comment by costrouc** [comment]
Closed by https://docs.qhub.dev/en/latest/source/dev_guide/release.html

**Comment by costrouc** [comment]
There are detailed release conditions
