### ISSUE TITLE
[bug] general pods running on non-general nodes

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#689]
There are a couple of general pods (meaning not user or worker work loads) on a non-general node group, in particular `cluster-autoscaler-aws-cluster-autoscaler` and `prefect-agent`.  I think these probably should be running on the general node.

These pods probably need to have a node affinity set (or possibly node selector, I am not quite clear).

This is related to a previous issue, #321, in which I also mentioned the idea of setting the taints on the nodes to prevent other workloads from shifting over to them, as 2i2c had done [here](https://github.com/2i2c-org/pilot-hubs/blob/57cd3238fcab4965d1dd8465a8230e6deb9f400f/terraform/main.tf#L145-L157).  

I think that taints (and corresponding tolerations for the appropriate pods) would be the best and most general solution, since it should prevent any new workload additions (such as ClearML, etc) from scheduling on user and worker nodes, which should be exclusive to jupyter and dask work loads.

In the meantime, if implementing taints and tolerations would require more effort (not sure how hard it would be), I think it would be great if someone were able to add the appropriate node affinity for these pods to the general node group.  Some similar or related PRs for reference are #323, and from `qhub-terraform-modules` [PR#37](https://github.com/Quansight/qhub-terraform-modules/pull/37) and [PR#39](https://github.com/Quansight/qhub-terraform-modules/pull/39).

This is an important issue because it can cause increased cloud costs due to scheduling on possibly oversized nodes.

**Comment by tylerpotts** [comment]
@amit will answer this

**Comment by tarundmsharma** [comment]
Hi @aktech @tylerpotts Any update on this.
Thank you.
