### ISSUE TITLE
Add qhub-ops validate command to PR github action

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#7]
1. run qhub-ops validate <filename> in github action
2. post comment to github PR using `GITHUB_TOKEN`

https://github.com/Quansight/qhub-ops/blob/master/qhub_ops/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows/jupyterhub-pr.yaml

**Comment by prasunanand** [comment]
https://github.com/Quansight/qhub-github-actions

https://github.com/Quansight/qhub-gcp-test-deployment/pull/1#issuecomment-707298719

**Comment by costrouc** [comment]
Closing as completed
