### ISSUE TITLE
[enhancement] Avoid returning 404

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#701]
## Description
@costrouc mentioned it would be nice to never return a 404 but instead provide some default page to the user in the scenario where no resource is found.

## Suggestion
Looks like this can be implemented easily enough with a catch all rule:
https://doc.traefik.io/traefik/getting-started/faq/#xxx-instead-of-404

**Comment by costrouc** [comment]
This would be a nice issue to add. I think here we would need to add a default route to traefik that shows a 404 page. This could just be a basic html page.
