### ISSUE TITLE
[bug] Version mismatch with dask-gateway 

### ISSUE THREAD

**Issue by tarundmsharma** [Quansight/qhub#702]
## Describe the bug
Version Mismatch is seen for dask gateway, when conda list command is executed in the jupyterlab  dask-gateway=0.6.1
is seen. which leads to issue in accessing the daskgateway.

## How can we help?
This issue can be resolved by adding below entries in the qhub-config.yaml file generated by qhub init command
- dask==2.30.0
- distributed==2.30.1
 - dask-gateway=0.9.0

## Your environment
This bug is seen currently:
1. local deployment
2. AWS deployment
3. GCP deployment

Issue with version mismatch
![image](https://user-images.githubusercontent.com/85969694/123660014-ea034c00-d850-11eb-9fa6-69b0ab1a6a77.png)
dask-gateway v0.6.1
![image](https://user-images.githubusercontent.com/85969694/123660223-17e89080-d851-11eb-82b9-95445e2aeec2.png)

After updating the qhub-config.yaml file
![image](https://user-images.githubusercontent.com/85969694/123660100-fc7d8580-d850-11eb-8e40-4376fd5bbdfc.png)

![image](https://user-images.githubusercontent.com/85969694/123660154-07d0b100-d851-11eb-92fd-11621ed577b6.png)
![image](https://user-images.githubusercontent.com/85969694/123660162-0acba180-d851-11eb-82c6-1d4205ee3eff.png)

**Comment by viniciusdc** [comment]
Hi @tarundmsharma thanks for opening this issue, it was indeed an error with the qhub-dask metapackage, by some weird issue it was not installing the correct pins for the dependencies that it was built with. But the problem was solved with #700, would you mind trying a new deployment to confirm that those errors have been corrected?

**Comment by tarundmsharma** [comment]
Sure @viniciusdc , Ill do it :)

**Comment by tarundmsharma** [comment]
AWS Testing works Fine:
![image](https://user-images.githubusercontent.com/85969694/123686830-d9150380-d86d-11eb-8925-fc417be8cecf.png)
![image](https://user-images.githubusercontent.com/85969694/123686841-dca88a80-d86d-11eb-8abd-101dc0a660bc.png)
![image](https://user-images.githubusercontent.com/85969694/123686860-e16d3e80-d86d-11eb-9c63-7a66b93e9b53.png)

GCP Testing works fine:
![image](https://user-images.githubusercontent.com/85969694/123687032-0e215600-d86e-11eb-9cd2-9f8484976030.png)
![image](https://user-images.githubusercontent.com/85969694/123687044-1083b000-d86e-11eb-84fb-f3671a84fd29.png)
