### ISSUE TITLE
[bug] unable to access daskgateway when jupyterhub, jupyterlab, dask_worker, dask_gateway, conda_store all picked from main branch images

### ISSUE THREAD

**Issue by tarundmsharma** [Quansight/qhub#703]
## Describe the bug
unable to access daskgateway when jupyterhub, jupyterlab, dask_worker, dask_gateway, conda_store all picked from main branch images
  jupyterhub: quansight/qhub-jupyterhub:main
  jupyterlab: quansight/qhub-jupyterlab:main
  dask_worker: quansight/qhub-dask-worker:main
  dask_gateway: quansight/qhub-dask-gateway:main
  conda_store: quansight/qhub-conda-store:main

## How can we help?

above issue can be resolved when the images is pulled from latest which is v0.3.11 leaving conda store to main branch.

jupyterhub: quansight/qhub-jupyterhub:v0.3.11
  jupyterlab: quansight/qhub-jupyterlab:v0.3.11
  dask_worker: quansight/qhub-dask-worker:v0.3.11
  dask_gateway: quansight/qhub-dask-gateway:v0.3.11
  conda_store: quansight/qhub-conda-store:main

## Your environment
Above issue is seen with 
1. Local deployment
2. AWS
3. GCP
other cloud providers did not try yet

**Comment by viniciusdc** [comment]
Hi @tarundmsharma, some recent updates were made within the main docker files, do you mind testing your deployments again, to determine if this error still persists? I've made a recent deployment with gcp and it worked.

**Comment by tarundmsharma** [comment]
Hi @viniciusdc , Sure i would love to check them.

Should i check it for all three,
1. AWS
2. Local 
3. GCP (which is already tested from you end)- but to be doubly sure.

Thank you

**Comment by viniciusdc** [comment]
> Hi @viniciusdc , Sure i would love to check them.
> 
> Should i check it for all three,
> 
> 1. AWS
> 2. Local
> 3. GCP (which is already tested from you end)- but to be doubly sure.
> 
> Thank you

I think that just double checking GCP would be great! If you have a deployment for AWS, another test with that would be awesome too! Don't worry too much with the local, if it passes for the cloud one then that's okay :smile:

**Comment by tarundmsharma** [comment]
Noted. :)

**Comment by tarundmsharma** [comment]
AWS Testing works Fine:
![image](https://user-images.githubusercontent.com/85969694/123686897-eb8f3d00-d86d-11eb-9c24-e2a7550a01c1.png)
![image](https://user-images.githubusercontent.com/85969694/123686908-edf19700-d86d-11eb-8df5-ace154c1850a.png)
![image](https://user-images.githubusercontent.com/85969694/123686919-f0ec8780-d86d-11eb-8a71-ca5e6614fb5a.png)


GCP Testing works fine:
![image](https://user-images.githubusercontent.com/85969694/123686973-006bd080-d86e-11eb-8a16-e2d3e9af788d.png)
![image](https://user-images.githubusercontent.com/85969694/123686988-0497ee00-d86e-11eb-91f7-ca2d94cf0061.png)

**Comment by viniciusdc** [comment]
@tarundmsharma It seems that the problem was solved, could you close this issue if that's the case?

**Comment by tarundmsharma** [comment]
yes sure. thanks @viniciusdc
