### ISSUE TITLE
[bug]  cqhub-config.yaml filereated using the "qhub init" command has some issues like the worker and user node min_node is set to 0 instead of 1

### ISSUE THREAD

**Issue by tarundmsharma** [Quansight/qhub#704]
## Describe the bug
qhub-config.yaml file created using the "qhub init" command has some issues like the worker and user node min_node is set to 0 instead of 1

this issue is mainly seen with the local and GCP deployment.
This issue is not encountered with the AWS deployment
## How can we help?

To rectify this issue
qhub-confog.yaml file has to be updated with below set of code.

node_groups:
    general:
      instance: n1-standard-2
      min_nodes: 1
      max_nodes: 1
    user:
      instance: n1-standard-2
      min_nodes: 1
      max_nodes: 5
    worker:
      instance: n1-standard-2
      min_nodes: 1
      max_nodes: 5

## Your environment
Local and GCP deployments

**Comment by tylerpotts** [comment]
This was prematurely changed in https://github.com/Quansight/qhub/pull/709/files

The minimum should remain zero for everything except the general nodepool, and currently for AWS nodegroups

**Comment by viniciusdc** [comment]
@tarundmsharma would you mind creating a PR (if it was not created yet) to switch back the correct configuration for the minimum values?

**Comment by tarundmsharma** [comment]
@viniciusdc , there was no PR for reverting the changes, I have created a PR : https://github.com/Quansight/qhub/pull/723.
Though there was one automated test failure for kubernetes test run. this failure of test run is because of the issue CI Failing: Kubernetes Tests #714.

Thank you.

![image](https://user-images.githubusercontent.com/85969694/124759350-2e77a180-df4d-11eb-995c-22c98a8ce1d0.png)
