### ISSUE TITLE
[bug] pod or node "jupyter-example-2duser" created after logging into qhub is not terminated by automation when qhub destroy command is executed

### ISSUE THREAD

**Issue by tarundmsharma** [Quansight/qhub#705]
## Describe the bug
When qhub destroy command is executed all the resource provisioned must be  destroyed.
But  "jupyter-example-2duser" created after logging into qhub is not destroyed and along with this pod qhub conda store is also not destroyed.

## How can we help?
As a turn around pods must be manually deleted using the k9s console delete to complete the qhub destroy process.

## Your environment
1. Local deployment
2. AWS
3. GCP
did not try in Azure and other cloud providers

![image](https://user-images.githubusercontent.com/85969694/123662907-83336200-d853-11eb-91f7-5749ab97b020.png)

**Comment by tylerpotts** [comment]
Ideas:
- Investigate a "force" option with terraform destroy (ideal option)
- Investigate using kubectl to evict user pods before destroying

**Comment by tarundmsharma** [comment]
The issue was validated for AWS and GCP.
"qhub destroy -c qhub-config.yaml" command was initiated after below scenario and the issue was not found.
1. Launched Jupyter pod.
2. Launched Jupyter pod and launched daskworker using normal scaling
3. Launched Jupyter pod and launched daskworker using adaptive scaling
In above 3 scenario and for both AWS and GCP the destroy was completed, though it took close to 15-17 minutes just to terminate the daskworker, jupyter pod and conda-store pods.
