### ISSUE TITLE
[bug] dask-scheduler pod unschedulable due to persistent volume claim "conda-store-dev-share" not found

### ISSUE THREAD

**Issue by alimanfoo** [Quansight/qhub#708]
https://github.com/Quansight/qhub/blob/ee21839c811d8b548ec5d013e9cba40dc6786ff7/qhub/render/__init__.py#L25

I'm using qhub version 0.3.11, deploying to GCP.

In my qhub config file I have changed the namespace from "dev" to "qhub" before deployment.

This deploys and works fine with the vanilla examples in the docs. However, when I add nodegroup selector configuration for the dask workers as described [here](https://docs.qhub.dev/en/stable/source/05_reference/02_system_maintenance.html#setting-specific-dask-workers-to-run-on-a-nodegroup) then redeploy, the dask-scheduler pod becomes unschedulable, due to persistent volume claim "conda-store-dev-share" not found.

I have looked at the persistent volume claims and there is "conda-store-qhub-share" present, so I am guessing this is because the config rendering has "conda-store-dev-share" hard-coded at the line linked above. Perhaps this needs to incorporate the namespace?

**Comment by aktech** [comment]
Thanks for reporting this @alimanfoo I'll take a look at this.

**Comment by alimanfoo** [comment]
Thanks @aktech. I made a tentative PR at #716 but not tested, hope that's useful.
