### ISSUE TITLE
Documentation regarding configuration file is confusing

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#71]
In all the deployment docs it says "the configuration file, `qhub-ops-config.yaml`, written in the YAML syntax, is provided for you.", but that file isn't anywhere in the repo. 

File for GCP: https://github.com/Quansight/qhub/blob/master/docs/docs/gcp/qhub-gcp-deployment.md

I'm not sure if that file is supposed to be in the repo but isn't, or if the documentation needs rewording

**Comment by prasunanand** [comment]
I would suggest having a `qhub init` command that takes in `aws` or `gcp` or `do` as  parameter and generates a `qhub-ops-config.yaml` file

**Comment by dharhas** [comment]
I also think a discussion about a single file vs set of files might be worth having. The single file gets long and confusing to edit.

**Comment by prasunanand** [comment]
Lets discuss it in next meeting .

**Comment by tylerpotts** [comment]
This particular issue regarding docs is resolved
