### ISSUE TITLE
CI Failing: Kubernetes Tests

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#714]
The Kubernetes tests seems to be failing since yesterday:
https://github.com/Quansight/qhub/actions/runs/986745574

```
[terraform]: Warning: Applied changes may be incomplete
[terraform]: 
[terraform]: The plan was created with the -target option in effect, so some changes
[terraform]: requested in the configuration may have been ignored and the output values may
[terraform]: not be fully updated. Run the following command to verify that no other
[terraform]: changes are pending:
[terraform]:     terraform plan
[terraform]: 	
[terraform]: Note that the -target option is not suitable for routine use, and is provided
[terraform]: only for exceptional situations such as recovering from errors or mistakes, or
[terraform]: when Terraform specifically suggests to use it as part of an error message.
[terraform]: 
[terraform]: 
[terraform]: Error: context deadline exceeded
[terraform]: 
[terraform]:   on modules/kubernetes/ingress/main.tf line 58, in resource "kubernetes_service" "main":
[terraform]:   58: resource "kubernetes_service" "main" {
[terraform]: 
[terraform]: 
```

**Comment by leej3** [comment]
This is an intermittent error I believe. I saw this before and rerunning it passed ([here](https://github.com/Quansight/qhub/pull/682)).

Perhaps just extending the timeout for teraform will fix this.

**Comment by aktech** [comment]
Has it passed recently for you, like in last couple of days?

**Comment by leej3** [comment]
Hmmm... no it was 3 days ago.I reran the tests that day and they all passed... Looks like it was a different timeout so I don't know if it is related. Possibly just noise in your issue thread. Sorry!

https://github.com/Quansight/qhub/runs/2916330926?check_suite_focus=true

```
[terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_deployment.controller: Still creating... [10m0s elapsed]
[terraform]: 
[terraform]: Error: Waiting for rollout to finish: 1 replicas wanted; 0 replicas Ready
[terraform]: 
[terraform]:   on modules/kubernetes/services/conda-store/main.tf line 46, in resource "kubernetes_deployment" "main":
[terraform]:   46: resource "kubernetes_deployment" "main" {
[terraform]: 
[terraform]: 
[terraform]: 
[terraform]: Error: Waiting for rollout to finish: 1 replicas wanted; 0 replicas Ready
[terraform]: 
[terraform]:   on modules/kubernetes/services/dask-gateway/controler.tf line 83, in resource "kubernetes_deployment" "controller":
[terraform]:   83: resource "kubernetes_deployment" "controller" {
[terraform]: 
[terraform]: 

Problem encountered: Terraform error
```

**Comment by viniciusdc** [comment]
It's really challenging because the errors are different... For the first one, could it be related to the load balancer generated for the minikube instance? We do have a [wait for load balancer](https://github.com/Quansight/qhub/blob/4cc393ec8ba50fd850b0f07781446229138809f0/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/ingress/main.tf#L59) inside the kubernetes config for that specific ingres service

**Comment by viniciusdc** [comment]
Some debuggin ideas to solve the issue so far:
- [] It should be interesting to use a better resource vm instance to run those tests initialy, just to be sure that they passes under normal conditions;
- [] Maybe we need to inspect the `quansight/qhub-jupyterlab:add_plotly_labextension` image, to check if it was working correctly before;
- [] Dan suggested to [increase the memory and CPU guarantees](https://github.com/Quansight/qhub/blob/28f453560ca125100df3edf9516595e729b67ad0/.github/workflows/test.yaml#L158), cause that might be insufficient to run the `qhub deploy` successfully. We could increase that to `0.25 >> 1.0`

**Comment by tarundmsharma** [comment]
Just an information, i was able to recreate it for local deployment with default values for qhub config.

`project_name: thisisatest
provider: local
domain: github-actions.qhub.dev
certificate:
  type: self-signed
security:
  authentication:
    type: password
  users:
    example-user:
      uid: 1000
      primary_group: admin
      secondary_groups:
      - users
      password: $2b$12$NsbwKvKJVQg5Cj2KodNjReWZdo4qNIDlZopQW6aYpw14bRLQesdGW
  groups:
    users:
      gid: 100
    admin:
      gid: 101
default_images:
  jupyterhub: quansight/qhub-jupyterhub:main
  jupyterlab: quansight/qhub-jupyterlab:main
  dask_worker: quansight/qhub-dask-worker:main
  dask_gateway: quansight/qhub-dask-gateway:main
  conda_store: quansight/qhub-conda-store:main
storage:
  conda_store: 60Gi
  shared_filesystem: 100Gi
theme:
  jupyterhub:
    hub_title: QHub - thisisatest
    hub_subtitle: Autoscaling Compute Environment
    welcome: Welcome to github-actions.qhub.dev. It is maintained by <a href="http://quansight.com">Quansight
      staff</a>. The hub's configuration is stored in a github repository based on
      <a href="https://github.com/Quansight/qhub/">https://github.com/Quansight/qhub/</a>.
      To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub/issues">github
      issue tracker</a>.
    logo: /hub/custom/images/jupyter_qhub_logo.svg
    primary_color: '#4f4173'
    secondary_color: '#957da6'
    accent_color: '#32C574'
    text_color: '#111111'
    h1_color: '#652e8e'
    h2_color: '#652e8e'
cdsdashboards:
  enabled: true
  cds_hide_user_named_servers: true
  cds_hide_user_dashboard_servers: false
terraform_state:
  type: local
namespace: dev
local:
  node_selectors:
    general:
      key: kubernetes.io/os
      value: linux
    user:
      key: kubernetes.io/os
      value: linux
    worker:
      key: kubernetes.io/os
      value: linux
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 4 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 0.75
      mem_limit: 4G
      mem_guarantee: 2.5G
      image: quansight/qhub-jupyterlab:main
  - display_name: Medium Instance
    description: Stable environment with 2 cpu / 8 GB ram
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 1.5
      mem_limit: 8G
      mem_guarantee: 5G
      image: quansight/qhub-jupyterlab:main
  dask_worker:
    Small Worker:
      worker_cores_limit: 1
      worker_cores: 0.75
      worker_memory_limit: 4G
      worker_memory: 2.5G
      worker_threads: 1
      image: quansight/qhub-dask-worker:main
    Medium Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 8G
      worker_memory: 5G
      worker_threads: 2
      image: quansight/qhub-dask-worker:main
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - qhub-dask ==0.2.3
    - python-graphviz
    - numpy
    - numba
    - pandas
  environment-dashboard.yaml:
    name: dashboard
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets >=7.6
    - qhub-dask ==0.2.3
    - param
    - python-graphviz
    - matplotlib >=3.3.4
    - panel >=0.10.3
    - voila >=0.2.7
    - streamlit >=0.76
    - dash >=1.19
    - cdsdashboards-singleuser >=0.5.7`

![image](https://user-images.githubusercontent.com/85969694/124644552-06863080-deb0-11eb-8d31-5eea40b78843.png)

@viniciusdc

**Comment by tarundmsharma** [comment]
I was able to recreate the issue "[terraform]: Error: context deadline exceeded". and even fix is found for local deployments

Steps to recreate the Issue:
Step1: Follow the document to deploy qhub locally "https://docs.qhub.dev/en/latest/source/06_developers_contrib_guide/04_tests.html#deploy-and-render-the-infrastructure"
Step2: Run command "minikube delete" to delete the minikube
Step3: Run command "minikube start --cpus 2 --memory 4096 --driver=docker" to create a minikube.
Step4: Run command "python -m qhub deploy --config qhub-config.yaml --disable-prompt" to deploy infrastructure.

**Findings**: **Error: context deadline exceeded**

Above steps does delete the loadbalancer which is launched using the commands 
1. "python3 minikube-loadbalancer-ip.py" - link for the script "https://github.com/Quansight/qhub/blob/main/tests/scripts/minikube-loadbalancer-ip.py"
2. "minikube addons configure metallb"
3. "minikube addons enable metallb"

Issue can also be recreated by following the local deployment procedure by skipping above 3 command.


FIX FOR ISSUE:

Run below 3 commands

1. "python3 minikube-loadbalancer-ip.py" - link for the script "https://github.com/Quansight/qhub/blob/main/tests/scripts/minikube-loadbalancer-ip.py"
2. "minikube addons configure metallb"
3. "minikube addons enable metallb"

![image](https://user-images.githubusercontent.com/85969694/125201038-1aa0a800-e28b-11eb-83c5-e4c06adf1448.png)
![image](https://user-images.githubusercontent.com/85969694/125201041-1e342f00-e28b-11eb-9616-e85c74f87305.png)
![image](https://user-images.githubusercontent.com/85969694/125201045-22604c80-e28b-11eb-8e42-bdfab245e4e2.png)
![image](https://user-images.githubusercontent.com/85969694/125201050-25f3d380-e28b-11eb-8a16-23f47ea12312.png)
![image](https://user-images.githubusercontent.com/85969694/125201058-28562d80-e28b-11eb-93e8-5fdc812209f3.png)
![image](https://user-images.githubusercontent.com/85969694/125201061-2ab88780-e28b-11eb-81fe-f523c78ded12.png)
![image](https://user-images.githubusercontent.com/85969694/125201066-2db37800-e28b-11eb-9e38-9856e7fdcbf2.png)
![image](https://user-images.githubusercontent.com/85969694/125201069-3146ff00-e28b-11eb-8265-4f2cfde90cd8.png)



Please help me on how this can be checked with CI automated deployment tests.

Thank you.

**Comment by aktech** [comment]
Hey @tarundmsharma thanks for investigating this, you can change the commands in `test.yml` file in the CI to see if that works: https://github.com/Quansight/qhub/blob/07067a1f71f004392b80e41c93af10fe3f8678f4/.github/workflows/test.yaml#L151

**Comment by tylerpotts** [comment]
Fixed by https://github.com/Quansight/qhub/pull/736
