### ISSUE TITLE
Source environments from external files

### ISSUE THREAD

**Issue by alimanfoo** [Quansight/qhub#717]
I have some environment definitions which are quite large with many packages. It would be convenient to have the option to source any such environment from a separate file, rather than including the environment inline within qhub-config.yaml. 

How about if the `environments` section in the config file allowed null values, which means that the content should be pulled from a file with that name in the repository root directory?

```
environments:
  "environment-special.yaml":
    # null value allowed, meaning load from separate file

``` 

It looks like it should be doable with some modifications to the source code around here:

https://github.com/Quansight/qhub/blob/4cc393ec8ba50fd850b0f07781446229138809f0/qhub/template/hooks/post_gen_project.py#L24

**Comment by alimanfoo** [comment]
Just noting that how Dask gateway picks up available environments would also need to be handled somehow.

https://github.com/Quansight/qhub/blob/08c94b91428f68d47270ba003a7461c45ef64f48/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/dask_gateway_config.py.j2#L5

**Comment by alimanfoo** [comment]
Thinking about this some more, FWIW I think it could be better to just let users manage environments by controlling the files in the `environments` directory themselves. I.e., remove the environments section from qhub-config.yaml, and during deployment figure out what environments are present by inspecting the `environments` directory..

**Comment by viniciusdc** [comment]
Hi @alimanfoo thanks for the idea. We are currently discussing new ways to handle the environment files as well as how conda-store will better manage them. 
We are very inclined to switch to this file system approach, but we still need to look in more details about the needed changes for that, so I'm moving this to needs-discussion.

**Comment by alimanfoo** [comment]
Thanks @viniciusdc, sounds good.

On a related note, in case it helps to know, I've also found that for more complicated environments, although I can solve and install them locally, they fail to solve and install on the deployed qhub service, even after waiting many hours. As a workaround I have been solving locally, then exporting the solved environment to a temporary file, then copy-pasting that into the qhub config file, then redeploying.

**Comment by brl0** [comment]
I also like and prefer the idea of externalized environment files.

> for more complicated environments, although I can solve and install them locally, they fail to solve and install on the deployed qhub service, even after waiting many hours

I have encountered this behavior as well and have adopted the same approach as a work around.

An idea just occurred to me, is that maybe a good workflow for qhub/conda-store would be to solve the changed environments in the render phase or in CI prior to deployment, exporting the pinned environments to a managed folder.  This would help catch failed environments earlier and more explicitly, rather than the current experience of deploying and then waiting and hoping the environment solves.  @costrouc, I'd be eager for your thoughts on this idea.

**Comment by alimanfoo** [comment]
Btw when I solve an environment and then export, I then add a date to the fully pinned environment name. This has been a convenient way for me and my colleagues to periodically upgrade an environment but still retain access to earlier versions if needed. 

In other words, I have (or would like) something along the lines of:

* environments
  * source
    * environment-foo.yaml
    * environment-bar.yaml
  * solved
    * environment-foo-20210601.yaml
    * environment-foo-20210701.yaml
    * environment-bar-20210705.yaml
    * ... etc.     

The solved environments with the datestamp in the name are the ones that get deployed to jupyterhub via qhub.

I like the idea that somehow qhub might handle the solving and pinning, but I would want to be able to control when qhub does that. I.e., I would not want all environments to be re-solved and pinned every time I run qhub deploy.
