### ISSUE TITLE
[bug] `JUPYTERHUB_API_TOKEN` incorrectly set for prefect pods

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#719]
## Describe the bug
A clear and concise description of what the problem is.

After enabling the `prefect-agent` and registering a few flows with it, and after getting past the issues described in #707 (by creating a much smaller image), we are still unable to run a flow from end-to-end. The error we are consistently seeing when trying to run a flow is the following: `dask_gateway.client.GatewayServerError: 500 Internal Server Error`

Given all the debugging and testing I've done to this point, I have strong reason to believe that the error arises from how the `JUPYTERHUB_API_TOKEN` is set for all of the pods besides jupyterlab instances. 

To highlight the potential bug more clearly see the print out below. Note, this is while attached to the `prefect-job` pod:
```
### See JUPYTERHUB_API_TOKEN ###
(prefect) root@prefect-job-7e35df5b-pkdmv:/app# env | grep JUPYTERHUB_API
JUPYTERHUB_API_TOKEN=<SAME API TOKEN AS PREFECT-AGENT/DASKGATEWAY-GATEWAY PODS> 
(prefect) root@prefect-job-7e35df5b-pkdmv:/app# python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask_gateway import Gateway
>>> g = Gateway()
>>> g.cluster_options()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/prefect/lib/python3.8/site-packages/dask_gateway/client.py", line 518, in cluster_options
    return self.sync(
  File "/opt/conda/envs/prefect/lib/python3.8/site-packages/dask_gateway/client.py", line 343, in sync
    return future.result()
  File "/opt/conda/envs/prefect/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/conda/envs/prefect/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/envs/prefect/lib/python3.8/site-packages/dask_gateway/client.py", line 497, in _cluster_options
    resp = await self._request("GET", url)
  File "/opt/conda/envs/prefect/lib/python3.8/site-packages/dask_gateway/client.py", line 417, in _request
    raise GatewayServerError(msg)
dask_gateway.client.GatewayServerError: 500 Internal Server Error

Server got itself in trouble
>>> exit()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1d11f97d30>

### JUPYTERHUB_API_TOKEN changed ###
(prefect) root@prefect-job-7e35df5b-pkdmv:/app# export JUPYTERHUB_API_TOKEN=<COPIED FROM USER JUPYTERLAB POD> 
(prefect) root@prefect-job-7e35df5b-pkdmv:/app# python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask_gateway import Gateway
>>> g = Gateway()
>>> g.cluster_options()
<dask_gateway.options.Options object at 0x7f61f3cd78b0>
```

I've tried digging into how the `JUPYTERHUB_API_TOKEN` is set for the user jupyterlab instance vs prefect-agent but I don't have any definitive answers. 
I think each of the pods has it's JUPYTERHUB_API_TOKEN set accordingly:
- `daskgateway-gateway` - [here](https://github.com/Quansight/qhub/blob/08c94b91428f68d47270ba003a7461c45ef64f48/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.infrastructure/modules/kubernetes/services/meta/qhub/main.tf#L107)
  - It is also hidden in the `daskgateway-gateway` pod yaml but with a format that looks *off*:
  ```
  env:
  - name: JUPYTERHUB_API_TOKEN 
    valueFrom:
      secretKeyRef:
        key: jupyterhub_api_token
        name: qhub-daskgateway-gateway
        optional: false 
  ```
- `prefect` - [here](https://github.com/Quansight/qhub/blob/08c94b91428f68d47270ba003a7461c45ef64f48/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/kubernetes.tf#L218)
  - It is also hidden in the `prefect-agent` pod yaml but exposed on in the `prefect-job` pod
  - The `prefect-agent` pod is running on in the `general` node group whereas the `prefect-job` pod is running in the `user_worker` node group
- `jupyterhub` -  [here](https://github.com/Quansight/qhub/blob/08c94b91428f68d47270ba003a7461c45ef64f48/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/meta/qhub/main.tf#L23)
  - This seems to conform to the [dask gateway documentation](https://gateway.dask.org/install-kube.html?highlight=apitoken) and seemds to be relabeled as `JUPYTERHUB_API_TOKEN`

Each time I spin up a jupyterlab instance I get a new `JUPYTERHUB_API_TOKEN` however, the same cannot be said for the `prefect-agent`, `prefect-job` or `qhub-daskgateway-gateway` pods. Even after killing these pods manually, they appear to retain the same `JUPYTERHUB_API_TOKEN` and what's more, this token appear to be the base64 decoded `jupyterHubToken` secret. 

At this point, I've run up against my limited Terraform knowledge. Do you happen to have an insights or ideas on how to get the `JUPYTERHUB_API_TOKEN` properly set on the `prefect-agent` and `prefect-job`? 

### What I have tried thus far?
- Manually exporting the token while attached to those pods (like I did in the above example), however when I disconnect from the pod, the `JUPYTERHUB_API_TOKEN` reverts back. 
- Generating a token from the JupyterHub Control Panel and hard coding it into the flow. This quick and dirty approach allows us to spin up a dask cluster. 

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

**Comment by aktech** [comment]
Adding dask gateway logs for posterity:

```
│ [E 2021-07-12 11:39:56.946 DaskGateway] 500 GET /api/v1/options 76.517ms                                                                                                                                                                   │
│ [W 2021-07-12 11:42:15.304 DaskGateway] 401 GET /api/v1/options 0.573ms                                                                                                                                                                    │
│ [E 2021-07-12 11:42:15.343 aiohttp.server] Error handling request                                                                                                                                                                          │
│ Traceback (most recent call last):                                                                                                                                                                                                         │
│   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request                                                                                                                                      │
│     resp = await self._request_handler(request)                                                                                                                                                                                            │
│   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle                                                                                                                                                   │
│     resp = await handler(request)                                                                                                                                                                                                          │
│   File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 13, in inner                                                                                                                                           │
│     return await handler(request)                                                                                                                                                                                                          │
│   File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 47, in inner                                                                                                                                           │
│     return await auth.authenticate_and_handle(request, handler)                                                                                                                                                                            │
│   File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 95, in authenticate_and_handle                                                                                                                           │
│     user = await self.authenticate(request)                                                                                                                                                                                                │
│   File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 393, in authenticate                                                                                                                                     │
│     return User(data["name"], groups=data["groups"], admin=data["admin"])                                                                                                                                                                  │
│ KeyError: 'groups'
```

**Comment by aktech** [comment]
The reason for the [above error](https://github.com/Quansight/qhub/issues/719#issuecomment-878209877), is due to the missing `groups` key in the api response (for url `/authorizations/token/`) for a service token:

https://github.com/dask/dask-gateway/blob/46cfcbf01343b121b19ae6ada1deeb4cbd8facc8/dask-gateway-server/dask_gateway_server/auth.py#L393

```python
from urllib.parse import quote
import requests

api_url = "https://qhub-amit-gcp.qhub.dev/hub/api/"
token = "value for JUPYTERHUB_API_TOKEN"
url = "%s/authorizations/token/%s" % (api_url, quote(token, safe=""),)
r = requests.get(url, headers={'Authorization': 'token %s' % token}, verify=False)
r.raise_for_status()
users = r.json()
```

* Response of the above, when JUPYTERHUB_API_TOKEN is for the prefect token:

```python
{
  'kind': 'user',
  'name': 'example-user',
  'admin': True,
  'groups': [],
  'server': '/user/example-user/',
  'pending': None,
  'created': '2021-07-12T14:05:42.007939Z',
  'last_activity': '2021-07-12T15:50:10.609851Z',
  'servers': None
}
```

* Response of the above, when JUPYTERHUB_API_TOKEN is for a user's token :

```python
{
  'kind': 'service',
  'name': 'prefect-service',
  'admin': True
}
```

**Comment by aktech** [comment]
Relevant issue: https://github.com/dask/dask-gateway/issues/409

It seems like you cannot authenticate a jupyterhub service via dask gateway, you can only authenticate "users", which is annoying because for prefect we use a service to create dask clusters via dask gateway.

**Comment by tarundmsharma** [comment]
@aktech as per you this is more of a limitation and not an issue.

**Comment by aktech** [comment]
It's fixed in dask gateway, we're waiting for the next release of dask-gateway to close this.

**Comment by iameskild** [comment]
As a temporary workaround, we can either:
1. Generate a `JUPYTEHUB_API_TOKEN` from the QHub token page and set it as an environmental variable before calling the Prefect Flow. 
2. Install `dask-gateway` from Amit's git commit.
