### ISSUE TITLE
[bug] dask-scheduler dies and kills cluster

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#728]
## Describe the bug
A clear and concise description of what the problem is.

We have been having difficulty getting a computationally expensive process running on a dask cluster. Launching a dask-cluster from a jupyter notebook on a jupyterlab instance results in the creation of a new dask-scheduler, followed shortly by the requested number of workers. However after a few minutes, the dask-scheduler mysteriously dies, causing the entire cluster to go down. The most common error we see in the notebook after the cluster fails is:
`concurrent.futures._base.CancelledError:`

After troubleshooting dask in the notebook and playing around in k9s, I think we might have a theory. It appears that the dask-scheduler pod has the memory and number of cores set to the default values of 2 GB and 1 core respectively. The dask-scheduler runs out of memory, crashs and the cluster goes down with it.

dask-scheduler pod yaml:
```
    resources:
      limits:
        cpu: "1"
        memory: "2147483648"
      requests:
        cpu: "1"
        memory: "2147483648"
```

The dask-scheduler can't seem to handle computationally expensive tasks with it's limited memory (and number of cores). 

Digging into the configurations, there appear to be a handful of places where the dask-scheduler (and dask-workers), have their default values set to 1 CPU core and 2GB of memory.
- `variable "cluster"` - [here](https://github.com/Quansight/qhub/blob/4f58740b77b96a20a12a90fd86d3acce784075d2/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/dask-gateway/variables.tf#L124)
- `module "kubernetes-dask-gateway" - [here](https://github.com/Quansight/qhub/blob/4f58740b77b96a20a12a90fd86d3acce784075d2/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/meta/qhub/main.tf#L120) 
- `dask_gateway_config.yaml` (our local copy) - [here](https://github.com/Quansight/qhub/blob/4f58740b77b96a20a12a90fd86d3acce784075d2/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/dask-gateway/templates/gateway_config.py#L22)

Yet they also may have their values overridden by the `dask_gateway_config.py.j2` ([here](https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/dask_gateway_config.py.j2)). 

By looking at the `events` on k9s, I believe can we see two things, first, that the "source" of the dask-scheduler pod is `default-scheduler`. And second, that the dask-scheduler pod starts up with a warning. 

<img width="1647" alt="Screen Shot 2021-07-08 at 23 54 57" src="https://user-images.githubusercontent.com/42120229/125037666-46345000-e049-11eb-88b2-e752d4d70598.png">

These warnings are can be different:
```
0/3 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match node selector, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```
And
```
Readiness probe failed: Get "http://10.10.1.130:8788/api/health": dial tcp 10.10.1.130:8788: connect: connection refused 
```

At this point, I have reason to believe that the source of these issues is with the dask-scheduler's lack of resources and I would suspect that this is bug with how the dask-scheduler gets initialized. I'm not entirely sure how to proceed next. 

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

**Comment by tylerpotts** [comment]
This isn't a bug, these are the default values. Adding the keys `scheduler_memory` and `scheduler_cores` to `qhub-config.yaml` under the `dask_worker` key will edit these defaults. This is an example of how it was done on GCP:
```
  dask_worker:
    "Small Worker":
      worker_cores_limit: 8
      worker_cores: 7
      worker_memory_limit: 57G
      worker_memory: 57G
      scheduler_memory: 57G
      scheduler_cores: 7
      image: "gcr.io/.../qhub-dask-worker:9f85f6ca480b28b451c3702d733318938798b8c2"
      scheduler_extra_pod_config:
        nodeSelector:
          "cloud.google.com/gke-nodepool": worker
      worker_extra_pod_config:
        nodeSelector:
          "cloud.google.com/gke-nodepool": worker
  ```
  
  These extra configurations get rendered out to `terraform/dask-gateway.yaml`?
  
  Closing this out

**Comment by iameskild** [comment]
@tylerpotts this is what that section of our `qhub-config.yaml` looks like currently:
```
  dask_worker:
    "Large Worker":
      worker_cores_limit: 15.5
      worker_cores: 15.5
      worker_memory_limit: 120G
      worker_memory: 96G
      worker_threads: 16
      image: quansight/qhub-dask-worker:v0.3.11
      scheduler_extra_pod_config:
        nodeSelector:
          "eks.amazonaws.com/nodegroup": "user_worker"
      worker_extra_pod_config:
        nodeSelector:
          "eks.amazonaws.com/nodegroup": "user_worker"
```

The node that the dask-scheduler runs on is a `r5.4xlarge` yet the it looks like the memory limit is still artificially limited to 2GB. 

And apologies for not including the minimal reproducible example but here it is:
```python
import datetime as dt

from datum.cluster import qhub_dask_cluster
from datum.readers.quadrant import QUADRANT_DEFAULT_CLUSTER_OPTS, sort_quadrant_files

today = dt.date.today()
d = today - dt.timedelta(days=19)

QUADRANT_DEFAULT_CLUSTER_OPTS["n_workers"] = 20

with qhub_dask_cluster(**QUADRANT_DEFAULT_CLUSTER_OPTS) as client:
    sort_quadrant_files(d)
```

Where `QUADRANT_DEFAULT_CLUSTER_OPTS` is set to:
```python
{'n_workers': 20,
 'process_desc': 'Quadrant default',
 'quorum': 1,
 'worker_type': 'Large Worker',
 'conda_env': 'datum',
 'install_datum': True,
 'branch_name': 'master',
 'retry_count': 5}
```

This consistently produces the following error:
```python
  File "/home/jovyan/.local/lib/python3.8/site-packages/datum/readers/quadrant.py", line 96, in sort_quadrant_files
    ddf_packed = ddf.pack_partitions_to_parquet(
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/spatialpandas/dask.py", line 294, in pack_partitions_to_parquet
    npartitions = self._compute_packing_npartitions(npartitions)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/spatialpandas/dask.py", line 504, in _compute_packing_npartitions
    nrows = len(self)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/dask/dataframe/core.py", line 3880, in __len__
    return len(s)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/dask/dataframe/core.py", line 564, in __len__
    return self.reduction(
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/client.py", line 2707, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/client.py", line 2021, in gather
    return self.sync(
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/client.py", line 862, in sync
    return sync(
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    raise exc.with_traceback(tb)
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/utils.py", line 321, in f
    result[0] = yield future
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-datum/lib/python3.8/site-packages/distributed/client.py", line 1887, in _gather
    raise exc
concurrent.futures._base.CancelledError: ('len-agg-b085641c741cc347239159bbf7665c61', 0)
```

I just ran this and it failed again.

**Comment by iameskild** [comment]
@tylerpotts I made the recommended change but the dask-scheduler failed to even spin up. I ended adding `_limits` and redeployed and that seemed to make the difference. 
```
  dask_worker:
    "Large Worker":
      worker_cores_limit: 15.5
      worker_cores: 15.5
      worker_memory_limit: 120G
      worker_memory: 96G
      worker_threads: 16
      scheduler_cores_limit: 15.5
      scheduler_cores: 15.5
      scheduler_memory_limit: 120G
      scheduler_memory: 96G      
      image: quansight/qhub-dask-worker:v0.3.11
      scheduler_extra_pod_config:
        nodeSelector:
          "eks.amazonaws.com/nodegroup": "user_worker"
      worker_extra_pod_config:
        nodeSelector:
          "eks.amazonaws.com/nodegroup": "user_worker"
```
I am now able to launch a dask-scheduler with the desired resource quantities (at least by checking the dask-scheduler` pod yaml). 

Unfortunately, the issue persists. I tried launching the same example as above and got the same behavior. The dask-scheduler starts up but will die after a few minutes causing the rest of the cluster to go down.

**Comment by iameskild** [comment]
Closing issue. The above changes to the scheduler resource limits along with a few bug fixes in the underlying `spatialpandas` modules (see spatialpandas [PR 78](https://github.com/holoviz/spatialpandas/pull/78) and [PR 79](https://github.com/holoviz/spatialpandas/pull/79)) resolves this issue.
