### ISSUE TITLE
[bug] Jupyterlab instances die 15 mins after the dask-cluster terminates

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#729]
## Describe the bug
A clear and concise description of what the problem is.

In the past week I have spun up many dask-clusters. And from what I can tell, each worker runs on their own node. However after the cluster has completed running (and no new clusters are subsequently launched), the users jupyterlab instance will get killed. This has happened many times while I was in the jupyterlab itself actively working on a notebook. 

The amount of time between the cluster terminating and my jupyterlab instance dying is remarkably consistent at just about 15 minutes. 

From k9s pods point-of-view, I see the `dask-worker` pods terminate and drop away but the `aws-node` and `kube-proxy` pods stick around for the 15 mins. At the 15 minute mark after the cluster terminated, these `aws-node` and `kube-proxy` pods associated with my jupyterlab instance will also die.

Although at this point I have little to go on, it feels like to me that there might be a process which cleans up "unused" pods/nodes and it believes my jupyterlab instance is such a pod/node. 

For reference, we have two node groups, `general` and `user_worker`. This `user_worker` node group is used for both the jupyterlab instances and dask-workers (as a cost saving measure because AWS prevents us from full-scaling down all nodes in a node group, see [issue 595](https://github.com/Quansight/qhub/issues/595)).

Also our idle culler is set as follows in the `jupyterhub.yaml`:

```
cull:
  enabled: true
  timeout: 1800 # cull after 30min of inactivity
  every: 600
```

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

**Comment by aktech** [comment]
>  I have spun up many dask-clusters. 

Does it happen with any dask cluster as in cluster of any size?

**Comment by iameskild** [comment]
I will try to narrow the number down to night but I've noticed when I request 20 or fewer workers, things usually seem fine. However whenever I request many workers, 50+, I can almost guarantee that my jupyterlab instance will get killed.

**Comment by aktech** [comment]
Log from scheduler:

```
│ distributed.core - ERROR - Exception while handling op heartbeat_worker                                                                                                                                                                    │
│ Traceback (most recent call last):                                                                                                                                                                                                         │
│   File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-DT/lib/python3.8/site-packages/distributed/core.py", line 494, in handle_comm                                                                │
│     result = handler(comm, **msg)                                                                                                                                                                                                          │
│   File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-DT/lib/python3.8/site-packages/distributed/scheduler.py", line 3887, in heartbeat_worker                                                     │
│     ws._executing = {                                                                                                                                                                                                                      │
│   File "/home/conda/store/91de068ec9f7aa232681e9e91b95d44050f0b94fec0deb15da53ce08bc6d63ed-DT/lib/python3.8/site-packages/distributed/scheduler.py", line 3888, in <dictcomp>                                                           │
│     parent._tasks[key]: duration for key, duration in executing.items()                                                                                                                                                                    │
│ KeyError: 'concat_parts-0df3a85c-6b0f-4d82-a7d7-4e8730766abb'
```

**Comment by iameskild** [comment]
From my work with @tylerpotts and @aktech, this issue was resolved by suspending the `AZRebalance` feature of the EC2 auto-scaling group, [here AWS documentation here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html).
