### ISSUE TITLE
CI Failing due to CPU limits on Action Runners [bug]

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#756]
Github hosted action runners have 2 cores.  With the latest PR adding Prometheus/Grafana to Qhub by default, the CI is failing because we are requesting ~2.5 cores from our minikube cluster, but as stated, we only have 2 cores.
https://github.com/Quansight/qhub/pull/733

I want to try using CIRun (https://cirun.io/), as an alternative which allows us to spin up Action Runners of various sizes only as needed.   @aktech do we have a Quansight account with access to CIRun?

**Comment by aktech** [comment]
> the CI is failing because we are requesting ~2.5 cores from our minikube cluster

Ah interesting.

> @aktech do we have a Quansight account with access to CIRun?

Yep we do have one via @quansight-bot

**Comment by Adam-D-Lewis** [comment]
Amit let me know that some work has been done on this at https://github.com/aktech/qhub/tree/run-tests-cirun

**Comment by Adam-D-Lewis** [comment]
Also, from Amit
> Also, when you do that, I would suggest to move the kubernetes tests job to a separate file:
https://github.com/Quansight/qhub/blob/528bb850158d78d2eabdb561e1d37040052119a1/.github/workflows/test.yaml#L93

**Comment by Adam-D-Lewis** [comment]
Waiting for a Quansight org owner to add the Cirun github app to the qhub repo

**Comment by aktech** [comment]
This was fixed here: https://github.com/Quansight/qhub/commit/265d6c5b8a1e01032402d4b2c94d12d5365e5e6e
