### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#759]
- [ ] Installation should be simple as possible 
- [ ] Change to use [pydata sphinx theme] (https://github.com/pydata/pydata-sphinx-theme)
- [ ] Docs have parity with QHub features
- [ ] Update FAQ

**Comment by iameskild** [comment]
Hey @tylerpotts, I'm happy to assist with this. I have a [WIP PR I started](https://github.com/Quansight/qhub/pull/739). I have some notes from my recent deployment work that I was trying to weave into the existing docs, but I'm happy to defer on how you would like to proceed.

**Comment by tylerpotts** [comment]
@iamskild Always happy to have help! Let's sync about docs next week

**Comment by tylerpotts** [comment]
Current look when using pydata theme:

![image](https://user-images.githubusercontent.com/49161327/132047426-bdee8a05-6b5a-4953-9f3f-3aa0aa3b72a2.png)
