### ISSUE TITLE
Automated support tool to snapshot QHub health/logs etc.

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#771]
# Summary

A common issue when providing support for clusters is needing to look at the logs and document what services are running and their health. This issue may grow into additionally downloading some of the cluster metrics from prometheus.

# Proposed Implementation

Adding a new command to qhub `qhub support` which will create a zip file with the following stored. The command line should by default create a zip file named `qhub-support.zip` with the filename being configurable.

 - download logs of all the pods running in the qhub namespace (namespace is specified in qhub-config.yaml to `log/<namespace>/<pod-name>.txt`
 - download output from resource definitions for all pods/pvc/pv/deployment/node/crds(traefik,dask) to `resource/<namespace>/<kind>/<name>.yaml`
 - download output from describe all pods/pvc/pv/deployments/nodes/crds(traefik,dask) to `describe/<namespace>/<kind>/<name>.yaml`

This script should be flexible enough to easily add new resource kinds to get resources from. You can assume for this PR that the Kubernetes context has already been setup. `kubernetes-python` package should be added as a dependency and used to get all of this data. As opposed to using the kubectl command.

## Acceptance Criteria

 - [ ] given a kubernetes context is setup for a user running `qhub support` it will generate a snapshot of the cluster in a zipfile that can be easily sent to Quansight for support
 - [ ] "Snapshot" should include logs, similar info to `kubectl describe`, and the yaml spec of the pod
 - [ ] should use the `kubernetes-python` python module for interacting with kubernetes
 - [ ] documenation in Administrator Guide section to detail how support zipfiles can be created. Make sure to mention that logs may need to be scrubbed and consider how you send the logs (most likely they should not be sent in the github issue).

**Comment by tylerpotts** [comment]
Per @Adam-D-Lewis 

This might be helpful to show an alternative to `kubectl describe`. https://stackoverflow.com/questions/56124320/how-to-get-log-and-describe-of-pods-in-kubernetes-by-python-client/56128463

**Comment by costrouc** [comment]
@tarundmsharma any progress on this issue? Is there a linked issue?

**Comment by costrouc** [comment]
Would be nice to have options in the cli to optionally print all information.

**Comment by tarundmsharma** [comment]
![image](https://user-images.githubusercontent.com/85969694/133213046-d450794c-1ca6-47a4-a329-875b9baccb25.png)
PR: https://github.com/Quansight/qhub/pull/818

**Comment by tarundmsharma** [comment]
PR: #818
