### ISSUE TITLE
Deploy helm chart for prometheus and granana and expose to `/monitoring`

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#772]
## Summary

Monitoring has been a longstanding issue with QHub. Would like a simple deployment and expose at `https://<qhub-url>/monitoring`

## Proposed implementation

Create a grafana/prometheus directory within https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services. The grafana/prometheus helm chart should follow a pattern very similar to https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/jupyterhub. The charts should additionally take an external-url variable similar to https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/clearml/variables.tf#L20 such that an ingress resource is created as following and enabled. The node group selector should be the general node pool. Additionally there should be an integration added to the qhub-config.yaml with. Enabled should be false by default. Ensure to add the new option to qhub/schema.py.

```yaml
monitoring:
   enabled: true/false
```

## Acceptance Criteria

 - [ ] grafana is accesible via https://<qhub-url>/monitoring and is functional and able to visit and login to keycloak

## Tasks to complete

 - 

## Related to
 - epic https://github.com/Quansight/qhub-internal/issues/7

**Comment by costrouc** [comment]
Closing since completed https://github.com/Quansight/qhub/pull/733
