### ISSUE TITLE
Launching spark clusters in QHub

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#789]
per Chris:

Create a general launcher for launching various clusters. IE Spark, MPI, Dask

Similar to kubernetes launcher. Have a CRD (https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that launches higher level objects. Could be leveraged for CDS dashboards and the above. Does lock us into using Kubernetes. There already exists a pyspark CRD.

**Comment by trallard** [comment]
@tylerpotts @costrouc can you please confirm the status of this? the linked issue seems to be open so this should too?
