### ISSUE TITLE
Documentation on kubernetes resources and functions for each provider to calculate resources

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#792]
## Description

A common problem that we have had with QHub deployments is getting the memory and cpu right for the jupyterhub and dask gateway profiles. In an effort to further automate this process we would like qhub to be aware of cpu/memory usage of nodes in given kubernetes deployments. Example:
 - https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#memory_cpu

## Success Criterial

 - [x] #796
 - [x] #795

```python
def allocatable_memory(total_memory):
     return 0.75 * total_memory

def allocatable_cpu(total_cpu):
      return 0.9 * total_cpu
```

**Comment by viniciusdc** [comment]
I've tested it by comparing the output fomr the`kubectl` command showed above withint the results for the gcp allocation formula... the difference is not too much (~0.6 VCPU or 200~800 Mb ).

**Comment by costrouc** [comment]
> The difference is not too much (0.6 VCPU or 200/800 Mb)

This is still quite a bit. Do you have a document that you are compiling that shows what you have measured?

**Comment by tylerpotts** [comment]
Note that Google may be using Mebibytes: https://simple.wikipedia.org/wiki/Mebibyte

**Comment by viniciusdc** [comment]
Ephemeral storage: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#local_ephemeral_storage

Eviction threshold for GCP:
https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#local_ephemeral_storage

**Comment by costrouc** [comment]
Looks like the formulas check out and get nearly exactly right.


```python
# kubernetes units
# E,P,T,G,M,K   10^3, 10^6, ... bytes
# Ei, Pi, Ti, Gi, Mi, Ki = 2^10, 2^20, ... bytes

# https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#node_allocatable

import math

def available_cpu(cpu : int):
    # 6% of the first core
    reserved = 0.06
    if cpu > 1:
       reserved = reserved + 0.01
    if cpu > 2:
       reserved = reserved + 0.005
    if cpu > 3:
       reserved = reserved + 0.005
    if cpu > 4:
       reserved = reserved + 0.0025 * (cpu - 4)
    return cpu - reserved

def available_memory(memory : int):
    # memory in bytes
    Gi = 2**30
    Mi = 2**20
    Ki = 2**10

    eviction_threshold = 100*Mi

    if memory < Gi:
        return memory - (255 * Mi)

    reserved = min(memory, 4*Gi) * 0.25
    if memory > 4*Gi:
        reserved = reserved + min(memory - 4*Gi, 4*Gi) * 0.20
    if memory > 8*Gi:
        reserved = reserved + min(memory - 8*Gi, 8*Gi) * 0.10
    if memory > 16*Gi:
        reserved = reserved + min(memory - 16*Gi, 112*Gi) * 0.06
    if memory > 128*Gi:
        reserved = reserved + (memory - 128*Gi) * 0.02

    return memory - reserved - eviction_threshold

print(available_cpu(4))
print(available_memory(16399092 * 1024) / 1024)

print(available_cpu(8))
print(available_memory(32888740 * 1024) / 1024)
```

**Comment by costrouc** [comment]
Incoming long description of how we can estimate the allocatable memory and cpu for a given instance size. There are two parts to this problem.

1. When you provision say a 2 Gi x 1 cpu instance only a fraction of the 2 Gi is actually usable since the linux kernel consumes some memory along with devices that are connected. This is a non-negligible amount. Here is a table with my findings. This problem will exist on every cloud provider. This was checked by provisioning a vm on each cloud provider of different sizes and checking `cat /proc/meminfo | grep MemTotal`

```
| Kb Available | Physical Storage | place |
|--------------+------------------+-------|
|     32898016 |               32 | pc    |
|     32823188 |               32 | pc    |
|    263856156 |              256 | pc    |
|     65480752 |               64 | pc    |
|    131716428 |              128 | pc    |
|    131947532 |              128 | pc    |
|    131838128 |              128 | pc    |
|     16269920 |               16 | pc    |
|     16296824 |               16 | pc    |
|     16254080 |               16 | pc    |
|     16399092 |               16 | gcp   |
|     32888740 |               32 | gcp   |
|      1004852 |                1 | do    |
|      2035508 |                2 | do    |
|      4030664 |                4 | do    |
|      8152848 |                8 | do    |
|    263945852 |              256 | do    |
|      4040796 |                4 | gcp   |
|     65969820 |               64 | gcp   |
|      1009616 |                1 | gcp   |
|      2041808 |                2 | gcp   |
|      8152988 |                8 | azure |
|     32887408 |               32 | azure |
|      8166288 |                8 | aws   |
|     61811360 |               60 | aws   |
|    193680648 |              192 | aws   |
|     15807620 |               16 | aws   |
|     32525428 |               32 | aws   |
|     32938904 |               32 | aws   |
```

When I did a linear fit I got `0.9833x - 1.205e8` where x is the physical number of bytes of the machine and the result is the available memory. 

2. Next cloud providers with their kubernetes implementations reserve a set amount of ram and cpu. Many example are seen in this issue. The formula for calculation on gpu is above and quite accurate within 10Mi. 

With this approach we should reliably get the available memory within 150Mi. There are a few outliers. The OS/distro does seem to have a significant impact on the available memory. This was especially clear on aws ubuntu.

**Comment by costrouc** [comment]
Without any tweaking this got the available kubernetes memory within 20Mi. So I think a 200Mi fudge factor would be more than enough.

```python
# kubernetes units
# E,P,T,G,M,K   10^3, 10^6, ... bytes
# Ei, Pi, Ti, Gi, Mi, Ki = 2^10, 2^20, ... bytes

# https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#node_allocatable

import math

def available_cpu(cpu : int):
    # 6% of the first core
    reserved = 0.06
    if cpu > 1:
       reserved = reserved + 0.01
    if cpu > 2:
       reserved = reserved + 0.005
    if cpu > 3:
       reserved = reserved + 0.005
    if cpu > 4:
       reserved = reserved + 0.0025 * (cpu - 4)
    return cpu - reserved

def available_memory(memory : int):
    # memory in bytes
    Gi = 2**30
    Mi = 2**20
    Ki = 2**10

    # using linux kernel requirements
    memory = memory * 0.9833 - 1.205e8

    eviction_threshold = 100*Mi

    if memory < Gi:
        return memory - (255 * Mi)

    reserved = min(memory, 4*Gi) * 0.25
    if memory > 4*Gi:
        reserved = reserved + min(memory - 4*Gi, 4*Gi) * 0.20
    if memory > 8*Gi:
        reserved = reserved + min(memory - 8*Gi, 8*Gi) * 0.10
    if memory > 16*Gi:
        reserved = reserved + min(memory - 16*Gi, 112*Gi) * 0.06
    if memory > 128*Gi:
        reserved = reserved + (memory - 128*Gi) * 0.02

    return memory - reserved - eviction_threshold

print(available_cpu(4))
print(16 * 2**30 / 1024 - 16399092)
print(available_memory(16 * 2**30) / 1024 - 13610740)

print(available_cpu(8))
print(32 * 2**30 / 1024 - 32888740)
print(available_memory(32 * 2**30) / 1024 - 29093796)

# so within the 20Mi for the estimate
```

**Comment by viniciusdc** [comment]
> Without any tweaking this got the available kubernetes memory within 20Mi. So I think a 200Mi fudge factor would be more than enough.
> 
> ```python
> # kubernetes units
> # E,P,T,G,M,K   10^3, 10^6, ... bytes
> # Ei, Pi, Ti, Gi, Mi, Ki = 2^10, 2^20, ... bytes
> 
> # https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#node_allocatable
> 
> import math
> 
> def available_cpu(cpu : int):
>     # 6% of the first core
>     reserved = 0.06
>     if cpu > 1:
>        reserved = reserved + 0.01
>     if cpu > 2:
>        reserved = reserved + 0.005
>     if cpu > 3:
>        reserved = reserved + 0.005
>     if cpu > 4:
>        reserved = reserved + 0.0025 * (cpu - 4)
>     return cpu - reserved
> 
> def available_memory(memory : int):
>     # memory in bytes
>     Gi = 2**30
>     Mi = 2**20
>     Ki = 2**10
> 
>     # using linux kernel requirements
>     memory = memory * 0.9833 - 1.205e8
> 
>     eviction_threshold = 100*Mi
> 
>     if memory < Gi:
>         return memory - (255 * Mi)
> 
>     reserved = min(memory, 4*Gi) * 0.25
>     if memory > 4*Gi:
>         reserved = reserved + min(memory - 4*Gi, 4*Gi) * 0.20
>     if memory > 8*Gi:
>         reserved = reserved + min(memory - 8*Gi, 8*Gi) * 0.10
>     if memory > 16*Gi:
>         reserved = reserved + min(memory - 16*Gi, 112*Gi) * 0.06
>     if memory > 128*Gi:
>         reserved = reserved + (memory - 128*Gi) * 0.02
> 
>     return memory - reserved - eviction_threshold
> 
> print(available_cpu(4))
> print(16 * 2**30 / 1024 - 16399092)
> print(available_memory(16 * 2**30) / 1024 - 13610740)
> 
> print(available_cpu(8))
> print(32 * 2**30 / 1024 - 32888740)
> print(available_memory(32 * 2**30) / 1024 - 29093796)
> 
> # so within the 20Mi for the estimate
> ```

Amazing! Thank you so much for this data as well as the python template. May I ask if you tested a QHub deployment with those resources specs?

**Comment by viniciusdc** [comment]
> @costrouc @viniciusdc can you update this issue and include additional action items?
> 
> Also, should we close #796 in favor of this issue?

Hi Kim, some context here, some clients and users related that it would be beneficial to qhub to:
- have a tool to identify system mem/cpu usage, need to instantiate a determined profile. Right now we suppose some values that are `good enough to create each user/worker pod, but they don't reflect the total capabilities of the machine type and cluster node assigned to the profile.

So @costrouc and I worked on getting an automatic tool to generate the qhub profiles based on the machine type the user requests with the most efficient resource utilization. Chris came with the prototype within the above comment to address #795  (which was closed by the stale bot), and some docs should then be added to inform the user about this.

We have the prototype, but now:
- we need to implement this by taking into consideration the new structure of qhub (post 0.4.0)
- test and debug as each cloud provider has a different way to inquire machine type data (that's why only a few of the cloud providers would get this initially)
- then test with an end-to-end deployment:
- [this comment ](https://github.com/Quansight/qhub/issues/792#issuecomment-914905698) sumirezes the most important information regarding this issue.

**Comment by kcpevey** [comment]
Closing in favor of https://github.com/nebari-dev/nebari/issues/35
