### ISSUE TITLE
Add premade dashboard to monitor Traefik [enhancement]

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#794]
I'm looking into adding https://github.com/tcheronneau/grafana_dashboard to the qhub deployment for Traefik.  The dashboard doesn't work off the bat.  I'm still working on making the changes to get it working.

**Comment by Adam-D-Lewis** [comment]
I was able to get this working using a helm chart (see prom_values.yaml in https://github.com/Quansight/grafana-prometheus-qhub).  Next, I just need to transfer the prom_values.yaml file into the terraform format in `qhub/qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/monitoring/main.tf`.

**Comment by Adam-D-Lewis** [comment]
Alright so the `prometheus_grafana` sets up traefik as a prometheus target correctly now.  The dashboard still needs to be added.

**Comment by Adam-D-Lewis** [comment]
We can add a grafana dashboard via a configmap or a secret.  Now I need to determine which dashboard we want added or make a sensible dashboard.

**Comment by costrouc** [comment]
Thanks @Adam-D-Lewis. Would you mind turning this into a PR? I'd like to review it and be able to merge it before you get too busy with other projects.

**Comment by costrouc** [comment]
@tylerpotts schedule a time to sync up with @Adam-D-Lewis to pick up this issue.
