### ISSUE TITLE
Docker builds failing due to apt/apt-get changes

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#812]
This applies to conda-store build: e.g. 
https://github.com/Quansight/qhub/actions/runs/1199495024

and also the private integration tests repo.

**Comment by danlester** [comment]
Have fixed conda-store docker image build by using:
```
apt-get --allow-releaseinfo-change update
```

See [here](https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease).

All images build for now, but possibly apt-gets need to be changed elsewhere - and in any case maybe we need to upgrade to the latest debian repos or something. @costrouc ?

**Comment by costrouc** [comment]
Thanks for fixing this @danlester. We definitely will have to move to a newer base image soon. I'll be updating this with conda-store.
