### ISSUE TITLE
Make zero to jupyterhub configuration overidable

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#814]
## Description

Related to issue https://github.com/Quansight/qhub/issues/476. Right now it is not possible to easily customize the zero to jupyterhub helm chart with QHub. It would be nice to expose the helm overrides in the `qhub-config.yaml`. This issue will follow very similarly to https://github.com/Quansight/qhub/pull/813.

## Steps

 - the qhub module exposes `jupyterhub-overrides` via https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/meta/qhub/variables.tf#L86. 
 - need to add a `{{ jupyterhub.overrides | jsonify }}` to https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/kubernetes.tf#L203. 
 - add jupyterhub.overrides key to qhub-config.yaml 
 - must be specificed in schema.py https://github.com/Quansight/qhub/blob/main/qhub/schema.py

**Comment by danlester** [comment]
@costrouc Would you be happy for me to reinstate this (and implement it)? Or do you know if you ended up implementing any of this?

I would like to provide the [option to enable_auth_state](https://github.com/Quansight/qhub/issues/929) and this could be best if just a generic z2jh override.

**Comment by danlester** [comment]
Closes #929
