### ISSUE TITLE
Auth0 Depreciation Warning - Upgrade from Node.js 8 to Node.js 12

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#838]
I'm getting depreciation warnings from Auth0. Looks like a couple of our qhub instances are connected to Auth0 accounts running Node.js 8

> Reminder - Action Required: Update your global tenant settings to Node.js 12
> --
> 
> How are you affected?
> 
> We noticed you are still running Node 8 as the extensibility setting on your Auth0 tenant. Long-term support (LTS) for Node 8 ended in December 2019, which means the Node.js development team no longer back-ports critical security fixes to this version. Continuing to run with Node.js 8 could potentially expose your extensibility code to security vulnerabilities. We will be removing the Node 8 runtime on February 25, 2022. After that date, tenants remaining set to use Node 8 may incur a service interruption.
> 
> What action do you need to take?
> 
> Update your global tenant settings to Node 12 and either:Migrate your Custom Database Scripts, Rules and Hooks to Auth0 Actions on the Node 16 runtime or, at a minimum,Update your Rules and Hooks to be Node 12 runtime compatible. Since long-term support for Node 12 will be ending in April 2022, we strongly recommend you begin to migrate to Auth0 Actions, which will allow you to stay on a supported Node version without additional future action.Note that there are some limitations with Actions, make sure you review them before migrating.
> > 
> >

**Comment by iameskild** [comment]
I believe this was discussed during a recent call, and If I recall correctly, it wasn't a concern for us? Am I remembering that correctly @costrouc?

**Comment by trallard** [comment]
ping @costrouc  is this still applicable or does this issue need closing?

**Comment by costrouc** [comment]
We don't use nodejs for our clients. So this issue isn't relevant to us. Going to close.
