### ISSUE TITLE
[bug] Error upgrading from 0.3.11 to 0.3.12

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#842]
### Discussed in https://github.com/Quansight/qhub/discussions/841

<div type='discussions-op-text'>

<sup>Originally posted by **rsignell-usgs** October  7, 2021</sup>
We tried to follow the [Qhub upgrade instructions](https://docs.qhub.dev/en/latest/source/admin_guide/upgrade.html?highlight=upgrade) to advance from 0.3.11 to 0.3.12 on a development deployment of Qhub (not the ESIP qhub).

After making the changes to 2 files (see screenshot below), the Github Action failed in "Render Changes to Template" step with:
```
Run qhub render -c qhub-config.yaml
Error: The schema validation of the qhub-config.yaml failed. The following error message may be helpful in determining what went wrong:

1 validation error for Main
default_images -> conda_store
  field required (type=value_error.missing)
Error: Process completed with exit code 1.
```
The changes we made that triggered the error are shown here: 

![2021-10-07_15-39-48](https://user-images.githubusercontent.com/1872600/136482363-c4680f4f-ac8e-4f95-999f-fe1590eb67ef.png)

What did we do wrong?   

What does `value_error.missing` mean?  
Is there a new parameter we need to include now?

We could provide access to the private repo if desired. 

</div>

**Comment by iameskild** [comment]
Hey @rsignell-usgs, I just wanted to confirm that the solution @Adam-D-Lewis provided resolved this issue and that we are good to close it? Thank you :)
