### ISSUE TITLE
Deployment to AWS - 404 page not found

### ISSUE THREAD

**Issue by rileyhun** [Quansight/qhub#855]
## Describe the bug
I did manage to get deploy qhub successfully on AWS I think. I get the following output:

```
[terraform]: Apply complete! Resources: 57 added, 0 changed, 0 destroyed.
[terraform]: 
[terraform]: Outputs:
[terraform]: 
[terraform]: ingress_jupyter = {
[terraform]:   "hostname" = "ad5b4f7f779df42da8f47f86f9b322a0-1977726728.us-west-2.elb.amazonaws.com"
[terraform]:   "ip" = ""
[terraform]: }
```

When I try to access the hostname, I'm getting a `404 page not found `. Furthermore, on CloudFlare I've set the DNS as follows:
<img width="1016" alt="Screen Shot 2021-10-13 at 6 41 39 PM" src="https://user-images.githubusercontent.com/20649466/137236226-02134f60-97d4-4bef-b58e-c5456afdef15.png">

But `jupyter.rhun.ca` doesn't seem to return anything.

**Comment by rileyhun** [comment]
> Hey @rileyhun, I apologize that this hasn't been a smooth deployment. From our previous discussion, did you destroy the cluster and begin start anew (deploying twice like you mentioned)? And if you did destroy the cluster, did you happen to check if there were any lingering AWS resources still active? Running `qhub deploy` twice with the dns flags might cause some issues. Have you tried redeploying without those dns flags?

Hi @iameskild , I did in fact destroy everything and start anew. I didn't throughly check for lingering resources but I can verify that the cluster was terminated after running the `qhub destroy...` command. I have tried redeploying with the flags and it usually returns a 404 Page Not Found. I could try it again though.

**Comment by rileyhun** [comment]
Hi @iameskild, after omitting the dns flags, the k8s pods look healthier now.

<img width="701" alt="Screen Shot 2021-10-14 at 1 13 56 AM" src="https://user-images.githubusercontent.com/20649466/137278304-f11771a3-f436-462b-a041-a0f7b77eaf90.png">

However, I'm not able to access the url I set (I was able to if I added the dns flags in the `qhub deploy` command

<img width="1045" alt="Screen Shot 2021-10-14 at 1 14 25 AM" src="https://user-images.githubusercontent.com/20649466/137278522-821b7acb-7825-4dd8-bbaf-428617777369.png">

<img width="1357" alt="Screen Shot 2021-10-14 at 1 17 18 AM" src="https://user-images.githubusercontent.com/20649466/137278610-0658ed00-f5ae-4890-bdab-379bdb6fa24e.png">

**Comment by rileyhun** [comment]
I see the error in the logs. Not sure what it means. Could someone please kindly advise?

```
[E 2021-10-14 21:29:31.288 JupyterHub web:1793] Uncaught exception GET /hub/spawn/rileyrhun@gmail.com (10.10.5.9)
    HTTPServerRequest(protocol='http', host='daskhub.rhun.ca', method='GET', uri='/hub/spawn/rileyrhun@gmail.com', version='HTTP/1.1', remote_ip='10.10.5.9')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/pages.py", line 207, in get
        spawner_options_form = await spawner.get_options_form()
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/spawner.py", line 351, in get_options_form
        options_form = await maybe_future(self.options_form(self))
      File "<string>", line 206, in custom_options_form
      File "<string>", line 177, in qhub_list_available_profiles
      File "<string>", line 94, in qhub_list_user_groups
    KeyError: 'rileyrhun@gmail.com'
    
[E 2021-10-14 21:29:31.290 JupyterHub log:181] {
      "X-Real-Ip": "10.10.5.9",
      "X-Forwarded-Server": "qhub-traefik-ingress-7bb8cc4c6b-sh5bc",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "daskhub.rhun.ca",
      "X-Forwarded-For": "10.10.5.9,10.10.26.179",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua": "\"Chromium\";v=\"94\", \"Google Chrome\";v=\"94\", \";Not A Brand\";v=\"99\"",
      "Referer": "https://daskhub.rhun.ca/hub/home",
      "Cookie": "jupyterhub-hub-login=[secret]; jupyterhub-session-id=[secret]",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
      "Host": "daskhub.rhun.ca",
      "Connection": "close"
    }

```

**Comment by iameskild** [comment]
Hey @rileyhun, you can set `AWS_DEFAULT_REGION` environment variable:
`export AWS_DEFAULT_REGION="us-east-2"`

**Comment by rileyhun** [comment]
Okay, after I updated the security user group in the config file, it worked. Yay. 

<img width="437" alt="Screen Shot 2021-10-15 at 12 56 27 AM" src="https://user-images.githubusercontent.com/20649466/137452757-58d01229-9de4-4869-93c5-a2e59755a235.png">

**Comment by iameskild** [comment]
Hi @rileyhun, glad to hear it working and thanks for following up!

Closing issue.
