### ISSUE TITLE
Use conda metapackages for environment consistency

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#86]
We have been facing the problems described at [this medium article](https://medium.com/pangeo/managing-environments-5604d848367a) regarding Management of Virtual Environments.

We already have this problem and are enforcing it manually when creating new conda envs. This is typically the primary reason dask etc fails on new environments etc. The metapackage approach is the only real solution at this point and will also allow us to build a good linter (#119) that can check pull requests.

## Further discussion
There is probably a discussion in terms of whether the conda-store story changes the way we do this. What is the best way to integrate it with conda-store?

**Comment by laisbsc** [comment]
Under technical discussion we've decided that for this issue we need to create a conda metapackage that pins the following packages:             
           "dask==2.14.0",
            "distributed==2.14",
            "dask-gateway=0.6.1",

**Comment by costrouc** [comment]
Proposed names:
 - qhub-dask-meta

Check what pango does to stay consistent.

**Comment by brl0** [comment]
Here is the recipe for the [pangeo-dask](https://github.com/conda-forge/pangeo-dask-feedstock/blob/master/recipe/meta.yaml) metapackage.  There is also a [pangeo-notebook](https://github.com/conda-forge/pangeo-notebook-feedstock/blob/master/recipe/meta.yaml) metapackage.

**Comment by costrouc** [comment]
Thanks @brl0 for that link. This is exactly what we will use `qhub-dask` and `qhub-notebook`. @viniciusdc will be working on this later in the week

**Comment by costrouc** [comment]
Were meeting this afternoon to start this.

**Comment by viniciusdc** [comment]
`[qhub-dask-meta](https://github.com/conda-forge/qhub-dask-meta-feedstock)` packages created at conda-forge, waiting for it's build process complete to check  availability on environment.

**Comment by viniciusdc** [comment]
```bash
Loading channels: done
# Name                       Version           Build  Channel             
qhub-dask-meta            2021.03.04      hd8ed1ab_0  conda-forge  
```
We now have qhub-dask metapackages available! :tada:

**Comment by costrouc** [comment]
So we have found that `qhub-dask` has already been created. Need to updated e.g. https://github.com/Quansight/qhub-cloud/blob/2461bded85de59d2936edfcecf3720319d263583/qhub/initialize.py#L163-L165 to poing to qhub-dask instead. Additionally there need to be docs around the requirement of qhub-dask. Also we need qhub-dask to follow the qhub version with the pinning requirements. e.g. version 0.2.3 of `qhub` will require `qhub-dask` 0.2.3

**Comment by viniciusdc** [comment]
> So we have found that `qhub-dask` has already been created. Need to updated e.g.
> 
> https://github.com/Quansight/qhub-cloud/blob/2461bded85de59d2936edfcecf3720319d263583/qhub/initialize.py#L163-L165
> 
> to poing to qhub-dask instead. Additionally there need to be docs around the requirement of qhub-dask. Also we need qhub-dask to follow the qhub version with the pinning requirements. e.g. version 0.2.3 of `qhub` will require `qhub-dask` 0.2.3

Great! I will update the pinning versions of the current requirements for qhub-dask... but I didn't follow your last comment though

**Comment by costrouc** [comment]
We need some sane way for users to know what versions of dask have been tested for a specific qhub. Not saying the versions need to be equal but it would be easier to manage

**Comment by viniciusdc** [comment]
Need to add `bokeh=2.2.3` into `qhub-dask` meta and test if the environments works.

**Comment by viniciusdc** [comment]
waiting for the next release of qhub `v0.3` to insert these modifications.
