### ISSUE TITLE
Add xvfb to default image so that pyvista can work

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#862]
## Description

https://docs.pyvista.org/user-guide/jupyter/panel.html#configuration-considerations

**Comment by rsignell-usgs** [comment]
@iameskild , seems this should be a 5 min operation, no?  Would love to try pyvista out.

**Comment by iameskild** [comment]
Completed here: https://github.com/nebari-dev/nebari-docker-images/pull/20
