### ISSUE TITLE
Availability Issues on AWS

### ISSUE THREAD

**Issue by rileyhun** [Quansight/qhub#866]
## Describe the bug
I had qhub working yesterday and was able to access JupyterHub and start my own kernel, but unfortunately, the hub and conda-store pods died. This seems to be a recurring problem in that the pods aren't stable and are perpetually stuck in "pending" after a couple hours. Would really appreciate some help on this!

<img width="701" alt="Screen Shot 2021-10-15 at 10 22 30 AM" src="https://user-images.githubusercontent.com/20649466/137528658-7c1bed30-8d34-4be6-9d41-1b5b8756a09a.png">

<img width="1383" alt="Screen Shot 2021-10-15 at 10 23 31 AM" src="https://user-images.githubusercontent.com/20649466/137528716-4058409e-4329-4a1c-9d3e-b4380ecdb6ce.png">

## Your environment
Conda version is 4.10.1
Qhub version is 0.3.11

**Comment by iameskild** [comment]
Hey @rileyhun, have you had a chance to deploy a fresh QHub with the latest version (0.3.13)? We're hoping this resolves a lot of the issues you've been seeing :)

**Comment by rileyhun** [comment]
Hello @iameskild, I deployed and seems to be okay so far. Will know for sure tomorrow after more time has elapsed. 

One follow-up question: are we supposed to install `dask_gateway` separately. From the installation instructions, I thought it would be out of the box working, but it's saying `ModuleNotFoundError: No module named 'dask_gateway'`

**Comment by rileyhun** [comment]
One follow-up question: 

I'm trying to scale my dask cluster but I am not sure if it's working. The # workers and memory are still stuck at 0. 

<img width="806" alt="Screen Shot 2021-10-20 at 10 50 34 PM" src="https://user-images.githubusercontent.com/20649466/138219231-8f89cf65-ab0a-4c61-88a5-726fb4a6306c.png">

**Comment by iameskild** [comment]
Hi @rileyhun, I'm glad to hear that things are working for you! Checkout this gist to get started using Dask:
https://gist.github.com/iameskild/1a45cbd114595fa371d2d127448c5e33

Closing issue.
