### ISSUE TITLE
[bug] term not properly initialized when starting server from SSH

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/qhub#868]
## Reproducing scenario : 
- I have set up a token to login via SSH
- My server is stopped
- I connect to it via SSH, it starts my server, and then I get an error message telling me that `shopt` is not found
- Everything works but my term is not initialized : no colored output, no tab completion, ...

Console output : 
```
$ ssh -o User=(...) -p 8022
Password:
Starting your server..............done!
/usr/bin/sh: 16: /etc/profile.d/term_settings.sh: shopt: not found
/usr/bin/sh: 24: /etc/profile.d/term_settings.sh: shopt: not found
/usr/bin/sh: 58: /etc/profile.d/term_settings.sh: Syntax error: Bad fd number
$ 
```

## Environment
- Qhub 0.3.13
- Python 3.9.7
- Conda version : 4.9.2
- Kubernetes version : `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}`
- Cloud provider : AWS
- Operating system and version : MacOS 11.4

**Comment by viniciusdc** [comment]
@iameskild could you check what is the current status of this?

**Comment by iameskild** [comment]
I was able to successfully spin up and connect to my JupyterLab pod via SSH:
```
ssh -o User=eeriksen@quansight.com quansight.qhub.dev -p 8022
```

I did have to clear the existing entry for `quansight.qhub.dev` from the `~/.ssh/known_hosts` file but otherwise it seems to be working as expected. 

@pierrotsmnrd I'm closing this issue for now. Feel free to reopen this issue if you're still experiencing problems.
