### ISSUE TITLE
[documentation] Fix Vale errors, warnings and suggestions

### ISSUE THREAD

**Issue by HarshCasper** [Quansight/qhub#875]
# Description

PR https://github.com/Quansight/qhub/pull/871 and https://github.com/Quansight/qhub/pull/873 integrated the Vale CI to the GitHub Actions and added the Google developer documentation style guide for language checks.

However, we have a lot of errors, warnings and suggestions generated and we did not get the opportunity to fix all of them. Currently, the CI runs only on modified lines, hence we don't generate a lot of noise but for local usage, we would ideally like it to be fixed.

## Recommended steps

To have a stab at fixing these issues, here are some recommended steps: 

- Install Vale CLI: https://docs.errata.ai/vale/install
- Run Vale on the documentation source: `vale docs/` 
- Find and fix the issues in batches and open a PR after a significant change.
- If you discover an anti-pattern, make a fix on the Vale configuration hosted over `tests/vale/styles/`
    - If Vale detects a typo issue, that isn't actually one, add it to the `vocab.txt`. 
    - If Vale detects grammatical issues, find the relevant YAML that defines the style and add exceptions.
 
For more background on working with Vale, please refer: https://docs.errata.ai/vale/styles

**Comment by sounix000** [comment]
@HarshCasper - I am interested in this issue, so please assign it to me. I will start working on it starting next week. Thanks!

**Comment by HarshCasper** [comment]
All Vale errors have been fixed and merged.
