### ISSUE TITLE
Use keycloak oauth2 client with grafana

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#879]
This appears to be doable with an example already in the grafana helm chart.  https://github.com/grafana/helm-charts/blob/f57f20bb4219c30a9bbe652ec8fbea811e5c0049/charts/grafana/values.yaml#L243

Once keycloak is added, this will be useful to add.

This may be relevant (https://linuxblog.xyz/posts/grafana-auth-proxy/)

**Comment by costrouc** [comment]
Resolved in #981

**Comment by magsol** [comment]
Closed by #1003
