### ISSUE TITLE
[enhancement] Add better metadata to the Docker images

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#892]
## Description
As part of the Docker over-haul currently going on it would be good to add better metadata for the Docker images, to facilitate findability, reproducibility and trust
Right now the Docker images have a single label `maintainer` 

## Suggestion
Add more `OCI` compliant annotations to the Docker images see<https://github.com/opencontainers/image-spec/blob/main/annotations.md>

## Context
This adheres to industry-standard best practices and increases the end-user confidence

**Comment by iameskild** [comment]
Hey @trallard, thanks for the suggestion! I'm only faintly aware of OCI, but I started with adding the following labels:
```
LABEL org.opencontainers.image.authors="Quansight" \
      org.opencontainers.image.source="https://github.com/Quansight/qhub"
```

Are there any others that you would recommend? Perhaps a description for each of image in question?

**Comment by trallard** [comment]
I would suggest adding the following on top of source and maintainer:

- description 
- created (previous build-date from label schema) - this can be updated through GH actions
- license 

Also it is advisable that the `author` label has a contact option (email, github handle, etc)

**Comment by iameskild** [comment]
@trallard @HarshCasper I just realized that we already set OCI-compliant labels :)

https://github.com/Quansight/qhub/runs/4111162873?check_suite_focus=true#step:5:32

Who should we add as `author`? @costrouc?

**Comment by trallard** [comment]
Maybe the QHub development team? - do we have a qhub email or something?

**Comment by trallard** [comment]
@iameskild  are you still working on items related to this or shall we close the issue?

**Comment by iameskild** [comment]
Hey @trallard, I believe that we can. Here are the labels currently being applied:

```
      "org.opencontainers.image.title": "qhub",
      "org.opencontainers.image.description": "QHub deployment tool",
      "org.opencontainers.image.url": "https://github.com/Quansight/qhub",
      "org.opencontainers.image.source": "https://github.com/Quansight/qhub",
      "org.opencontainers.image.version": "docs-update-cleanup",
      "org.opencontainers.image.created": "2021-12-13T18:02:27.414Z",
      "org.opencontainers.image.revision": "7bcfa7e72875102025276298168c8a95e2518f5c",
      "org.opencontainers.image.licenses": "BSD-3-Clause"
```

I didn't find "email" as a predefined OCI key but we can add another field/key if you would like to include it. Otherwise this issue can be closed.

**Comment by trallard** [comment]
that should be enough - will go ahead and close this issue
