### ISSUE TITLE
[bug] Cypress Tests are failing

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#895]
## Describe the bug

Cypress tests are failing in the main branch.

## Screenshot and Video

![First Test -- Check QHub login and start JupyterLab (failed)](https://user-images.githubusercontent.com/5647941/139941976-e339dc06-d13f-44f7-b856-cc338ee2ea64.png)

https://user-images.githubusercontent.com/5647941/139941996-cdc64d58-c6a1-4a14-93a4-1765036cb3fa.mp4

**Comment by costrouc** [comment]
Tests are now passing now.
