### ISSUE TITLE
No resource group created when using the Azure provider with a local terraform state

### ISSUE THREAD

**Issue by roman-kouzmenko** [Quansight/qhub#906]
Steps to reproduce on qhub 0.3.13:
1. qhub init azure --project qhub --domain example.com --ci-provider none --auth-provider password
2. Change terraform_state type to local in qhub-config.yaml
3. qhub deploy -c qhub-config.yaml

Resulting error message:
```
Error: creating Managed Kubernetes Cluster "qhub-dev" (Resource Group "qhub-dev"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'qhub-dev' could not be found."
```

**Comment by Adam-D-Lewis** [comment]
Thanks for documenting this for us, @roman-kouzmenko.  I saw you were able to get around this issue for now, I believe, but we will take a look at fixing this issue next week.

**Comment by danlester** [comment]
Thanks for this. If this is still relevant in qhub 0.4 then please let us know.
