### ISSUE TITLE
[enhancement] Enable custom resource options in qhub-config

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#913]
## Description
As QHUb normally takes care of the full cycle of its deployment in the cloud, from initial setup, infra deployment, app deployment, CI/CD, and monitoring. It's also important to consider custom management over the creation of the resource from the user (Admin) perspective.

Given that some cloud infrastructures may have their own set of policies and/or naming conventions for resources - it is important to give the user ability over the services creation process, which includes:

- Custom naming for mode group services, Kubernetes cluster, and helm chart services;
- Add resource labeling, for easier management of strict security configuration settings in each cloud provider ecosystem.
- Enable external and internal load balancer configuration for QHub IP services:
   - adding an option to pin the load balancer IP (useful for internal and external clusters)
   - adding an option to specify if the VPC network was internal or external
 
## Key Considerations
 - Some users might have installed security policies over the resources created in their cloud providers, handing over control over these settings to users will help satisfy those restrictions and evade unnecessary burdens over QHUb maintenance.
- Tags are also an incredibly useful tool as they let you manage your infrastructure more effectively by providing the ability to filter resources and perform tasks and actions based on nominated tag values.
- Will solve burden issues attained to QHub maintenance workflows related to custom configurations settings.

## Value/benefit

> I will be updating this issue with more details, in the meantime feel free to add any **additional context** or valuable considerations to this.

C.c @dharhas @costrouc @tylerpotts @Adam-D-Lewis

**Comment by viniciusdc** [comment]
@Quansight/qhub

**Comment by costrouc** [comment]
For this issue I'd like to discuss possible solutions.

**Comment by costrouc** [comment]
https://github.com/Quansight/qhub/issues/327

**Comment by viniciusdc** [comment]
A combination of overwriting and #1003 now creates a good tooling system for those requests. I think we can close this issue and open a 'extension mechanism' enhancement now.

c.c @costrouc

**Comment by danlester** [comment]
Closing in favor of #865
