### ISSUE TITLE
[Discussion] - QHub OSS website

### ISSUE THREAD

**Issue by trallard** [Quansight/qhub#918]
🎨  The site WIP can be found at: https://www.figma.com/file/09YBlmN93sxFSVPFznVfGT/QHub-Website-Template---Landing-Page?node-id=223%3A568 

## Updates 
 - The design was internally discussed and pre-approved 
 - There are a number of comments by @laisbsc  aimed at aligning the sections and some content
 
## Needs discussion 

- [ ] Need to align with Irina to develop some illustrations for some of the sections 
- [ ] Right now we only have the mock of the site but we have not agreed on the final content - while @HarshCasper  has some experience working on landing page content this should be a team effort and the content should be agreed upon all
- [ ] Final audience scoping - since it is the OSS version my impression is that we are targeting the following scenarios
    - Folks deploying QHub instances on their own at their institutions/orgs/etc (regardless of what their title is)
    - The broader community - in the sense of contributors or potential contributors, folks looking for the right JupyterHub distribution for a. above thus comparing among different options.
- [ ] What are we using for the site? @HarshCasper  has suggested using [docusaurus](https://docusaurus.io/) 

✨ Identifying the personas or scenarios we are targeting is super important as that will set the tone and the content of the site. And while I think @HarshCasper  and @gabalafou  could start working on the technical side of the site straight away it would be more beneficial to have the broader picture all laid out from the beginning to avoid big hiccups

**Comment by trallard** [comment]
- *docusaurus*: I am not familiar with this tool but it seems to be gaining some traction on [the GitHub repo](https://github.com/facebook/docusaurus) have we considered other alternatives and if so what are the advantages of docusaurus vs others?

**Comment by danlester** [comment]
Need to reconsider as part of renaming the qhub project.
