### ISSUE TITLE
[enhancement] Update to JupyterHub 1.5.0

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/qhub#926]
## Description

JupyterHub 1.5.0 has been released and contains a security fix :

> JupyterHub 1.5 is a security release, fixing a vulnerability ghsa-cw7p-q79f-m2v7 where JupyterLab users with multiple tabs open could fail to logout completely, leaving their browser with valid credentials until they logout again.

QHub must be updated to use JupyterHub 1.5.0 to include this fix.

**Comment by danlester** [comment]
This would mean upgrading to use z2jh Helm chart version 1.2.0 - see https://jupyterhub.github.io/helm-chart/

**Comment by danlester** [comment]
By the way, to fix the vulnerability we (only) need to update the jupyterhub in the user environment:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/04de3447397bb85b495d0302984d36c61bc75da5/CHANGELOG.md

**Comment by danlester** [comment]
The new Helm chart is available in my `authstate` branch if anyone wants to try it. Seems to work so far on GCP.

But for some reason on Digital Ocean, JupyterHub couldn't reach the Keycloak API. Will try again.
