### ISSUE TITLE
qhub upgrade should reject custom authenticators [bug]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#931]
## Describe the bug

If the qhub-config.yaml contains:
```
security:
  authentication:
    type: custom
```
when running `qhub upgrade` from 0.3.13, the resulting qhub-config.yaml will be invalid (since it will not change the 'custom' entry which is no longer supported).

## Expected behaviour

It should warn the user about the problem - maybe error out and say they first need to change to `type: password` or something else (probably easiest and failsafe).

Or we could just warn since `qhub deploy` will break anyway, and they'll have to do something to move forward.

## Actual behaviour

I believe `qhub upgrade` will allow through the invalid config which will then break `qhub deploy`.

**Comment by viniciusdc** [comment]
Agree, we could put a note on the docs commenting that this is no longer supported, and at the same time add a schema validator to check which type of authentication was passed in the config.

Just out of curiosity, was the Traitlets configuration removed for these custom cases?

**Comment by danlester** [comment]
@viniciusdc if you mean the relevant code in the `templates/jupyterhub_config.py.j2` file then yes - everything is now using the Keycloak OAuth2 provider, which in turn may be configured for password, Auth0, GitHub, or anything else.

**Comment by viniciusdc** [comment]
> @viniciusdc if you mean the relevant code in the `templates/jupyterhub_config.py.j2` file then yes - everything is now using the Keycloak OAuth2 provider, which in turn may be configured for password, Auth0, GitHub, or anything else.

Cool, thanks! :+1:
