### ISSUE TITLE
Move to Terraform v.13.x

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#94]

**Comment by tylerpotts** [comment]
Run `terraform 0.13upgrade` on all directories with terraform files. Also needs to be done in the modules rep

**Comment by tylerpotts** [comment]
complete

**Comment by rsignell-usgs** [comment]
@tylerpotts , I got qhub installed yesterday and when I tried my first PR today, I got this failure:
```
Error refreshing state: state snapshot was created by Terraform v0.13.5, which is newer than current v0.13.4; upgrade to Terraform v0.13.5 or greater to work with this state
```
I'm not sure what/where to upgrade!

**Comment by rsignell-usgs** [comment]
Ah, okay.   I see that I have `terraform=0.13.5` installed in my `qhub` custom Conda environment. 
I downgraded terraform there, but now I get the same failure when I try to run `qhub deploy`.   

I'm guessing I need to start over.
