### ISSUE TITLE
Cypress test failing in Python (JHub) subroutine [bug]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#953]
## Describe the bug

In the AWS integration test at the very least, Cypress is failing with the error:
```
INFO:jhub_client.api:created token for username=example-user
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.7/dist-packages/jhub_client/api.py", line 38, in __aenter__
    self.api_token = await self.create_token(self.username)
  File "/usr/local/lib/python3.7/dist-packages/jhub_client/api.py", line 119, in create_token
    return (await response.json())["token"]
KeyError: 'token'
ERROR:asyncio:Unclosed client session
...
```

## Expected behaviour

It should process the notebook successfully in JupyterLab.

## Actual behaviour

It fails as above.

## How to reproduce

Set up a QHub on AWS and run the Cypress tests as [described here](https://docs.qhub.dev/en/latest/source/dev_guide/testing.html#cypress-tests).

**You must also set the env var CYPRESS_JHUB_CLIENT_PYTHON_PATH to your Python interpreter.**

Only if that env var is set (see [code here](https://github.com/Quansight/qhub/blob/c8853ad94eebee72850dc2512086a1d1edee0c61/tests_e2e/cypress/integration/main.js#L65)), it runs [jhub-client](https://github.com/Quansight/jhub-client) on a notebook to check it gets the results expected.

The jhub-client command is run in this support routine [here](https://github.com/Quansight/qhub/blob/c8853ad94eebee72850dc2512086a1d1edee0c61/tests_e2e/cypress/support/index.js#L47).

The reason for running within Cypress (even though this particular test is not browser-based) is so that we can run this after starting JupyterLab (and before shutting it down).

It might be better to run this as a separate test directly in Python/Bash.

To try this, maybe remove CYPRESS_JHUB_CLIENT_PYTHON_PATH from the integration test setup and add a separate step to run jhub with `--daemonize --stop-server` flags or similar.

Maybe pytest should orchestrate this. See tests_deployment in the QHub repo for ideas, although I'm not sure if that is currently working outside of a local cluster.

### OS

Ubuntu etc

**Comment by danlester** [comment]
BTW not sure why we are seeing the token error in the first place. It's possible you'd get the same running jhubclient directly too. If jhub-client works on the command line, let's see if we can switch to that and we don't need to worry why Cypress was unable to complete it.

**Comment by viniciusdc** [comment]
As we are now using Keycloak for managing users and `qhub keycloak` to add new-user when testing. I think we can close this issue as it seems to be now outdated. c.c @danlester

**Comment by danlester** [comment]
We think there are new pytest tests that are part of the integration test suites again.
