### ISSUE TITLE
[enhancement]  jupyter-resource-usage

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#965]
## Description
It would be great to add the [Jupyter resource usage lab extension to Qhub](https://github.com/jupyter-server/jupyter-resource-usage).   Just a handy little add-on I like to keep track of memory usage!

**Comment by trallard** [comment]
Definitely @costrouc  - might be worth looking at adding <https://github.com/jtpio/jupyterlab-system-monitor> which is based on the Jupyter resource extension but has some additional niceties

**Comment by costrouc** [comment]
We have two actions for addressing this issue before adding the package:
  - establish a process for what belongs in the default QHub jupyterlab image
  - separate and document the separation of docker image from QHub #1145

**Comment by peytondmurray** [comment]
Hi @rsignell-usgs, what version of QHub are you using? The resource usage lab extension was [added a little while back](https://github.com/Quansight/qhub/pull/730), and should be available in `qhub >= v0.3.13`.

@trallard jupyterlab-system-monitor looks promising, but currently it is incompatible with the existing qhub jupyterlab `environment.yaml`. The recipe is [here](https://github.com/conda-forge/jupyterlab-system-monitor-feedstock/blob/main/recipe/meta.yaml), and you can see it pins to an old version of jupyter-resource-usage. For now I'll mark this issue as closed, but if we want to include jupyterlab-system-monitor it might require a PR to bring it up to date with the latest versions of its dependencies.
