### ISSUE TITLE
Testing criteria for new deployments

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#97]
- Ensure qhub deploys on AWS, GCP, DO
- Ensure dask_gateway works
- Check for existence of the conda environment

**Comment by laisbsc** [comment]
@tylerpotts is this issue still relevant?

**Comment by brl0** [comment]
I think this is still relevant.

**Comment by costrouc** [comment]
We have had `Ensure qhub deploys on AWS, GCP, DO` done for awhile and this is being tested each week. 

We are still working on automating the dask_gateway testing and checking for creation of conda environments.

**Comment by viniciusdc** [comment]
> We have had `Ensure qhub deploys on AWS, GCP, DO` done for awhile and this is being tested each week.
> 
> We are still working on automating the dask_gateway testing and checking for creation of conda environments.

@costrouc I think @danlester is currently working on a solution to the dask-gateway testing (integration tests) and I think that your latest work with conda-store might solve the rest, right?
