### ISSUE TITLE
[documentation] Review QHub architecture diagram for Azure Provider

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#971]
I have been trying to sketch a more detailed qhub architecture diagram for some of the services and integration (focusing on network traffic) that we deploy and create on Azure. I would love to have some feedback and any ideas are welcome.

![QHub - Cloud architecture](https://user-images.githubusercontent.com/51954708/146042959-5ed4b816-50e3-43fd-9be2-bdd4f2b1cd49.png)

The orange ones are optional features that can be enabled during deployment.

**Comment by viniciusdc** [comment]
Hi @trallard, if you have some time could you have a look ?

**Comment by dharhas** [comment]
Is Azure pipelines a requirement or optional. Can't we also use gilab runners, github actions?

**Comment by trallard** [comment]
Should be optional - I would suggest  replacing CI/CD (as a word) and add also icons for GH and GitLab

Same in container registry - Add the Docker logo (right now I can only see the  ACR logo which might be misleading too)

Question @viniciusdc  do the arrow colours and rectangles have a specific meaning (i.e authentication required, automated process) if so maybe add a legend on the side to clarify

**Comment by viniciusdc** [comment]
> Should be optional - I would suggest replacing CI/CD (as a word) and add also icons for GH and GitLab
> 

Hi @dharhas , the idea of using the Azure pipelines would be an optional feature in the case we are deploying using an Azure repo and not Github. 

> Same in container registry - Add the Docker logo (right now I can only see the ACR logo which might be misleading too)
> 
For the container registry that's the registry where we store the images pulled during deploymeny and store to k8s use, docker or others can still be used independently.

> Question @viniciusdc do the arrow colours and rectangles have a specific meaning (i.e authentication required, automated process) if so maybe add a legend on the side to clarify

Will do that, thanks :smile:

**Comment by trallard** [comment]
Hey @viniciusdc  have you managed to make the above changes to the schematic?

Please post the diagram here when updated so we can add it to the docs

**Comment by costrouc** [comment]
@viniciusdc do you mind giving an update on this issue and closing it with a PR.

**Comment by kcpevey** [comment]
Closing in favor of #1031
