### ISSUE TITLE
Testing main on windows leads to some depency errors...

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#982]
Hi folks, recently I needed to deploy Qhub on a windows machine and I easily succeeded using the `v0.3.13`. But I wanted to test if main was also an option there but noticed that we recently included some module functions that are not covered on windows... such as `subprocess.Popen`  and `os.setsids`:

see for reference  
https://github.com/Quansight/qhub/blob/29f398af3542143751d52252b8a2204cd9c1e5cf/qhub/utils.py#L84

Is there a quick way we can work around that?

Also, for windows, we have a bug presented here 
https://github.com/Quansight/qhub/blob/29f398af3542143751d52252b8a2204cd9c1e5cf/qhub/provider/terraform.py#L34
which is, there is no key in the above dictionary that matches the available version for `AMD64` present on Hashicorp domain... which leads to an incomplete download. Also, for windows the binary ends with `.exe` wich need to be included here as well:
https://github.com/Quansight/qhub/blob/29f398af3542143751d52252b8a2204cd9c1e5cf/qhub/provider/terraform.py#L42

Or the file will not be recognized by the system.

**Comment by dharhas** [comment]
Why are we trying to make QHub compatible with windows? Seems like it would be hard to maintain compatibility long term?

**Comment by costrouc** [comment]
@viniciusdc was doing deployments for a client from a windows machine. This is solvable since there are only a few areas where this needs to be fixed. Help would be appreciated! We are putting this as low priority.
