### ISSUE TITLE
Remove Keycloak Client from jupyterhub_config.py.j2 [enhancement]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#994]
## Description

The jupyterhub_config.py.j2 file uses OAuth for login from Keycloak, but also fetches group and user info directly from keycloak via its own REST API. It doesn't need to do that because these details should be provided through userinfo in OAuth2, if configured correctly.

That would need to include showing group attributes so that profile lists are present.

## Value/benefit

This will simplify the code, make it more secure and less likely to fall over. It will also speed things up.

**Comment by costrouc** [comment]
@danlester this was resolved with the #1003 PR. keycloak client is no longer used and userinfo is directly used.
