### ISSUE TITLE
[documentation] Keycloak docs

### ISSUE THREAD

**Issue by magsol** [Quansight/qhub#999]
Need to add some details to the online documentation around Keycloak, particularly from the dev side: what questions does Keycloak answer, and why did we choose Keycloak in particular?

**Comment by trallard** [comment]
Is this related to #1030?

**Comment by magsol** [comment]
How to add users to Keycloak.

**Comment by costrouc** [comment]
Things that are currently missing from the docs and need to be ready for the 0.4 release:
 - ensure that the user is added to the group `/viewer`, `/developer`, or `/admin`. Viewer is readonly and does not have jupyterlab access. If this is not set the user wlll not be able to access resources
 - how to add new groups. New groups must be added to `/projects/<group-name>` in the heigharchy. When a user is added to the group they must reauth (login/logout) to refresh their keycloak credentials/userinfo. 
 - how to add users to a given group
